Repository godotengine/godot-demo-projects, pull requests merged in 2020-02, with the labels that each got.

#393 Update remaining Viewport demos to Godot 3.1.2
  viewport/3d_in_2d/3d_in_2d.gd
  viewport/3d_in_2d/3d_in_2d.tscn
  viewport/3d_in_2d/player.gd
  viewport/3d_in_2d/player.scn
  viewport/3d_in_2d/project.godot
  viewport/3d_in_2d/robot_3d.gd
  viewport/3d_in_2d/robot_3d.tscn
  viewport/gui_in_3d/gui_3d.gd
  viewport/gui_in_3d/gui_in_3d.tscn
  viewport/gui_in_3d/gui_panel_3d.tscn
  viewport/screen_capture/project.godot
  viewport/screen_capture/screen_capture.gd
  viewport/screen_capture/screen_capture.tscn
Labels: enhancement, update

#394 Update and improve all Pong demos
  2d/pong/ball.gd
  2d/pong/ceiling_floor.gd
  2d/pong/paddle.gd
  2d/pong/pong.tscn
  2d/pong/project.godot
  2d/pong/scripts/ball.gd
  2d/pong/scripts/ceiling_floor.gd
  2d/pong/scripts/paddle.gd
  2d/pong/scripts/wall.gd
  mono/pong/Scripts/Ball.cs
  mono/pong/project.godot
  networking/multiplayer_pong/ball.gd
  networking/multiplayer_pong/ball.tscn
  networking/multiplayer_pong/lobby.gd
  networking/multiplayer_pong/lobby.tscn
  networking/multiplayer_pong/paddle.gd
  networking/multiplayer_pong/paddle.tscn
  networking/multiplayer_pong/pong.gd
  networking/multiplayer_pong/pong.tscn
  networking/multiplayer_pong/project.godot
  networking/multiplayer_pong/scripts/ball.gd
  networking/multiplayer_pong/scripts/lobby.gd
  networking/multiplayer_pong/scripts/paddle.gd
  networking/multiplayer_pong/scripts/pong.gd
  visual_script/circle_pop/Main.tscn
  visual_script/circle_pop/Main.vs
  visual_script/circle_pop/default_env.tres
  visual_script/multitouch_view/Main.tscn
  visual_script/multitouch_view/Main.vs
  visual_script/multitouch_view/default_env.tres
  visual_script/pong/ball.png
  visual_script/pong/ball.png.import
  visual_script/pong/icon.png
  visual_script/pong/icon.png.import
  visual_script/pong/left_pallete.png
  visual_script/pong/left_pallete.png.import
  visual_script/pong/pong.tscn
  visual_script/pong/project.godot
  visual_script/pong/right_pallete.png
  visual_script/pong/right_pallete.png.import
  visual_script/pong/scripts/ball.vs
  visual_script/pong/scripts/ceiling_floor.vs
  visual_script/pong/scripts/paddle.vs
  visual_script/pong/scripts/wall.vs
  visual_script/pong/separator.png
  visual_script/pong/separator.png.import
  visual_script/visual_pong/ball.vs
  visual_script/visual_pong/ceiling_floor.vs
  visual_script/visual_pong/paddle.vs
  visual_script/visual_pong/pong.tscn
  visual_script/visual_pong/wall.vs
Labels: enhancement, update

#395 Improve GUI demos
  gui/drag_and_drop/drag_and_drop.tscn
  gui/drag_and_drop/drag_drop_script.gd
  gui/input_mapping/controls.gd
  gui/input_mapping/controls.tscn
  gui/rich_text_bbcode/rich_text_bbcode.gd
  gui/rich_text_bbcode/rich_text_bbcode.tscn
  gui/translation/controls.gd
  gui/translation/controls.tscn
  gui/translation/noto.fnt
  gui/translation/project.godot
  gui/translation/translation_demo.gd
  gui/translation/translation_demo.tscn
Labels: enhancement

#398 Update Finite State Machine demo to Godot 3.1.2
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/debug/ControlsPanel.tscn
  2d/finite_state_machine/debug/states_stack_displayer.gd
  2d/finite_state_machine/player/Player.tscn
  2d/finite_state_machine/player/bullet/Bullet.tscn
  2d/finite_state_machine/player/bullet/bullet.gd
  2d/finite_state_machine/player/bullet/bullet_spawner.gd
  2d/finite_state_machine/player/player_controller.gd
  2d/finite_state_machine/player/player_state_machine.gd
  2d/finite_state_machine/player/states/combat/attack.gd
  2d/finite_state_machine/player/states/combat/stagger.gd
  2d/finite_state_machine/player/states/debug/state_name_displayer.gd
  2d/finite_state_machine/player/states/die.gd
  2d/finite_state_machine/player/states/motion/in_air/jump.gd
  2d/finite_state_machine/player/states/motion/motion.gd
  2d/finite_state_machine/player/states/motion/on_ground/idle.gd
  2d/finite_state_machine/player/states/motion/on_ground/move.gd
  2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd
  2d/finite_state_machine/player/weapon/Sword.tscn
  2d/finite_state_machine/player/weapon/sword.gd
  2d/finite_state_machine/player/weapon/weapon_pivot.gd
  2d/finite_state_machine/project.godot
  2d/finite_state_machine/state_machine/state.gd
  2d/finite_state_machine/state_machine/state_machine.gd
  3d/platformer/stage.tscn
Labels: enhancement, update

#397 Update and improve misc demos for Godot 3.1.2
  misc/android_iap/iap.gd
  misc/android_iap/iap_demo.gd
  misc/android_iap/icon.png
  misc/android_iap/project.godot
  misc/instancing/ball.tscn
  misc/instancing/ball_factory.gd
  misc/instancing/project.godot
  misc/instancing/scene_instancing.tscn
  misc/joypads/joypads.gd
  misc/multitouch_cubes/CubeScene.tscn
  misc/multitouch_cubes/GestureArea.gd
  misc/multitouch_cubes/Main.tscn
  misc/multitouch_cubes/default_env.tres
  misc/multitouch_view/Main.gd
  misc/multitouch_view/Main.tscn
  misc/multitouch_view/default_env.tres
  misc/multitouch_view/icon.png.import
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.gd
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.shader
  misc/pause/pause_button.gd
  misc/pause/spinpause.gd
  misc/pause/spinpause.tscn
  misc/regex/regex.gd
  misc/regex/regex.tscn
  misc/tween/main.gd
  misc/tween/main.tscn
  misc/window_management/control.gd
  misc/window_management/observer/observer.gd
  misc/window_management/observer/observer.tscn
  misc/window_management/project.godot
  misc/window_management/window_management.tscn
Labels: enhancement, update

#399 Update 2D role playing game
  2d/role_playing_game/Game.gd
  2d/role_playing_game/Game.tscn
  2d/role_playing_game/dialogue/dialogue_player/DialoguePlayer.gd
  2d/role_playing_game/dialogue/dialogue_player/DialoguePlayer.tscn
  2d/role_playing_game/dialogue/interface/Interface.gd
  2d/role_playing_game/dialogue/interface/Interface.tscn
  2d/role_playing_game/grid_movement/grid/Grid.gd
  2d/role_playing_game/grid_movement/pawns/Actor.gd
  2d/role_playing_game/grid_movement/pawns/Character.gd
  2d/role_playing_game/grid_movement/pawns/Character.tscn
  2d/role_playing_game/grid_movement/pawns/IdleActor.gd
  2d/role_playing_game/grid_movement/pawns/Pawn.gd
  2d/role_playing_game/grid_movement/pawns/RandomActor.gd
  2d/role_playing_game/grid_movement/pawns/Walker.gd
  2d/role_playing_game/project.godot
  2d/role_playing_game/screens/combat/Combat.gd
  2d/role_playing_game/screens/combat/actors/Actor.tscn
  2d/role_playing_game/screens/combat/actors/Opponent.tscn
  2d/role_playing_game/screens/combat/actors/Player.tscn
  2d/role_playing_game/screens/combat/interface/ActorInfo.tscn
  2d/role_playing_game/screens/combat/interface/Info.tscn
  2d/role_playing_game/screens/combat/interface/UI.gd
  2d/role_playing_game/theme/Theme.tscn
  2d/role_playing_game/theme/labels/Title.tscn
  2d/role_playing_game/turn_combat/combatants/Combatant.gd
  2d/role_playing_game/turn_combat/combatants/Opponent.tscn
  2d/role_playing_game/turn_combat/combatants/Player.tscn
  2d/role_playing_game/turn_combat/combatants/health/Health.gd
  2d/role_playing_game/turn_combat/combatants/health/Health.tscn
  2d/role_playing_game/turn_combat/combatants/sprites/Sprite.tscn
  2d/role_playing_game/turn_combat/turn_queue/TurnQueue.gd
  2d/role_playing_game/turn_combat/turn_queue/TurnQueue.tscn
Labels: enhancement, update

#400 Update 2D physics platformer
  2d/particles/particles.tscn
  2d/physics_platformer/Stage.tscn
  2d/physics_platformer/Stage2.tscn
  2d/physics_platformer/TilesetEdit.tscn
  2d/physics_platformer/background/ParallaxBg.tscn
  2d/physics_platformer/coin/Coin.tscn
  2d/physics_platformer/coin/coin.gd
  2d/physics_platformer/enemy/Enemy.tscn
  2d/physics_platformer/enemy/enemy.gd
  2d/physics_platformer/platform/MovingPlatform.tscn
  2d/physics_platformer/platform/OneWayPlatform.tscn
  2d/physics_platformer/platform/moving_platform.gd
  2d/physics_platformer/player/Bullet.tscn
  2d/physics_platformer/player/Player.tscn
  2d/physics_platformer/player/bullet.gd
  2d/physics_platformer/player/player.gd
  2d/physics_platformer/project.godot
Labels: enhancement, update

#404 Update README and LICENSE for Godot 3.2
  LICENSE.md
  README.md
Labels: enhancement

#366 Add Matrix Transform demo
  misc/matrix_transform/2D.tscn
  misc/matrix_transform/3D.tscn
  misc/matrix_transform/README.md
  misc/matrix_transform/default_env.tres
  misc/matrix_transform/icon.png
  misc/matrix_transform/icon.png.import
  misc/matrix_transform/marker/AxisMarker2D.gd
  misc/matrix_transform/marker/AxisMarker2D.svg
  misc/matrix_transform/marker/AxisMarker2D.svg.import
  misc/matrix_transform/marker/AxisMarker2D.tscn
  misc/matrix_transform/marker/AxisMarker3D.gd
  misc/matrix_transform/marker/AxisMarker3D.svg
  misc/matrix_transform/marker/AxisMarker3D.svg.import
  misc/matrix_transform/marker/AxisMarker3D.tscn
  misc/matrix_transform/project.godot
  misc/matrix_transform/screenshots/.gdignore
  misc/matrix_transform/screenshots/2D.png
  misc/matrix_transform/screenshots/3D.png
Labels: enhancement, new demo

#392 Tweak 3D settings in various demos
  3d/kinematic_character/cubelib.tres
  3d/kinematic_character/level.tscn
  3d/kinematic_character/project.godot
  3d/platformer/project.godot
  3d/platformer/stage.tscn
  3d/platformer/tiles.tres
  misc/multitouch_cubes/Main.tscn
  misc/pause/project.godot
  misc/window_management/observer/observer.tscn
  misc/window_management/project.godot
  viewport/gui_in_3d/project.godot
Labels: enhancement

#358 Revamp Input Remap demo simplifying it
  gui/input_mapping/ActionRemapButton.gd
  gui/input_mapping/ActionRemapButton.tscn
  gui/input_mapping/InputRemapMenu.tscn
  gui/input_mapping/controls.gd
  gui/input_mapping/controls.tscn
  gui/input_mapping/project.godot
Labels: enhancement

#416 Tweak the 2D platformer demos, particularly Physics Platformer
  2d/physics_platformer/Stage2.tscn
  2d/physics_platformer/enemy/Enemy.tscn
  2d/physics_platformer/enemy/enemy.gd
  2d/physics_platformer/player/player.gd
  2d/physics_platformer/project.godot
  2d/platformer/project.godot
  2d/platformer/src/Actors/Actor.gd
  2d/platformer/src/Actors/Enemy.tscn
  2d/platformer/src/Actors/Player.tscn
Labels: enhancement

#413 Add a viewport 3D scaling demo
  viewport/3d_scaling/README.md
  viewport/3d_scaling/default_env.tres
  viewport/3d_scaling/hud.gd
  viewport/3d_scaling/hud.tscn
  viewport/3d_scaling/icon.png
  viewport/3d_scaling/icon.png.import
  viewport/3d_scaling/noto_sans_ui_regular.ttf
  viewport/3d_scaling/project.godot
  viewport/3d_scaling/spatial.tscn
Labels: enhancement, new demo

#421 Update Platformer 3D to use AnimationTree and organize into subfolders
  3d/platformer/coin/coin.gd
  3d/platformer/coin/coin.tscn
  3d/platformer/coin/sound_coin.wav
  3d/platformer/coin/sound_coin.wav.import
  3d/platformer/cutout.png
  3d/platformer/enemy/enemy.gd
  3d/platformer/enemy/enemy.tscn
  3d/platformer/enemy/robot_walk.wav
  3d/platformer/enemy/robot_walk.wav.import
  3d/platformer/enemy/shine.png
  3d/platformer/enemy/shine.png.import
  3d/platformer/enemy/sound_explode.wav
  3d/platformer/enemy/sound_explode.wav.import
  3d/platformer/enemy/sound_hit.wav
  3d/platformer/enemy/sound_hit.wav.import
  3d/platformer/player/bullet/bullet.gd
  3d/platformer/player/bullet/bullet.tscn
  3d/platformer/player/controls/osb_down.png
  3d/platformer/player/controls/osb_down.png.import
  3d/platformer/player/controls/osb_fire.png
  3d/platformer/player/controls/osb_fire.png.import
  3d/platformer/player/controls/osb_jump.png
  3d/platformer/player/controls/osb_jump.png.import
  3d/platformer/player/controls/osb_left.png
  3d/platformer/player/controls/osb_left.png.import
  3d/platformer/player/controls/osb_right.png
  3d/platformer/player/controls/osb_right.png.import
  3d/platformer/player/controls/osb_up.png
  3d/platformer/player/controls/osb_up.png.import
  3d/platformer/player/follow_camera.gd
  3d/platformer/player/player.gd
  3d/platformer/player/player.tscn
  3d/platformer/player/sound_jump.wav
  3d/platformer/player/sound_jump.wav.import
  3d/platformer/player/sound_shoot.wav
  3d/platformer/player/sound_shoot.wav.import
  3d/platformer/project.godot
  3d/platformer/sb.cube
  3d/platformer/stage.tscn
  3d/platformer/stage/panorama.png
  3d/platformer/stage/panorama.png.import
  3d/platformer/stage/stage.tscn
  3d/platformer/stage/texture.png
  3d/platformer/stage/texture.png.import
  3d/platformer/stage/texturemr.png
  3d/platformer/stage/texturemr.png.import
  3d/platformer/stage/tiles.tres
  3d/platformer/stage/tiles.tscn
  3d/platformer/texture.png.import
Labels: enhancement, refactor, update

#419 Update networking and multiplayer demos
  networking/multiplayer_bomber/bomb.gd
  networking/multiplayer_bomber/bomb.tscn
  networking/multiplayer_bomber/gamestate.gd
  networking/multiplayer_bomber/lobby.gd
  networking/multiplayer_bomber/lobby.tscn
  networking/multiplayer_bomber/project.godot
  networking/multiplayer_bomber/rock.gd
  networking/multiplayer_bomber/rock.tscn
  networking/multiplayer_bomber/score.gd
  networking/multiplayer_bomber/tile_scene.tscn
  networking/multiplayer_bomber/world.tscn
  networking/webrtc_minimal/chat.gd
  networking/webrtc_minimal/main.tscn
  networking/webrtc_minimal/minimal.gd
  networking/webrtc_minimal/minimal.tscn
  networking/webrtc_signaling/client/multiplayer_client.gd
  networking/webrtc_signaling/client/ws_webrtc_client.gd
  networking/webrtc_signaling/demo/client_ui.gd
  networking/webrtc_signaling/demo/client_ui.tscn
  networking/webrtc_signaling/demo/main.gd
  networking/webrtc_signaling/demo/main.tscn
  networking/webrtc_signaling/server/ws_webrtc_server.gd
  networking/websocket_chat/client/client.gd
  networking/websocket_chat/client/client.tscn
  networking/websocket_chat/client/client_ui.gd
  networking/websocket_chat/combo/combo.tscn
  networking/websocket_chat/server/server.gd
  networking/websocket_chat/server/server_ui.gd
  networking/websocket_chat/utils.gd
  networking/websocket_minimal/Main.tscn
  networking/websocket_minimal/client.gd
  networking/websocket_minimal/server.gd
  networking/websocket_multiplayer/default_env.tres
  networking/websocket_multiplayer/scene/game.tscn
  networking/websocket_multiplayer/scene/main.tscn
  networking/websocket_multiplayer/script/game.gd
  networking/websocket_multiplayer/script/main.gd
Labels: enhancement, topic:networking, update

#424 Add instructions on importing all projects at once in the README
  README.md
Labels: enhancement
