Repository godotengine/godot-demo-projects, pull requests merged in 2020-07, with the labels that each got.

#494 Progressively interrupt the jump in the 2D platformer demo
  2d/platformer/src/Actors/Player.gd
Labels: enhancement

#493 Disable antialiasing on the font in the 2D platformer demo
  2d/platformer/assets/theme/fonts/kenney_mini_square.tres
  2d/platformer/assets/theme/user_interface.tres
Labels: enhancement

#492 Remove useless "_find_free_pointer_id" method in Multitouch View
  misc/multitouch_view/TouchHelper.gd
  visual_script/multitouch_view/TouchHelper.gd
Labels: enhancement

#497 Add memory usage to the Voxel demo
  3d/voxel/menu/debug.gd
Labels: enhancement

#499 3D NavMesh Demo - fix for navmesh (re)baking issue
  3d/navmesh/navmesh.gd
  3d/navmesh/navmesh.tscn
Labels: bug

#500 Tweak CI to more closely match the main repo
  .github/workflows/static_checks.yml
  2d/gd_paint/paint_control.gd
  file_format.sh
  mono/2.5d/addons/node25d-cs/Node25D.cs
  mono/2.5d/addons/node25d-cs/ShadowMath25D.cs
Labels: enhancement

#498 Mono Android IAP Demo Project
  mono/android_iap/Android IAP with C#.csproj
  mono/android_iap/Android IAP with C#.sln
  mono/android_iap/GodotGooglePlayBilling/BillingResult.cs
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBillingUtils.cs
  mono/android_iap/GodotGooglePlayBilling/Purchase.cs
  mono/android_iap/GodotGooglePlayBilling/PurchasesResult.cs
  mono/android_iap/GodotGooglePlayBilling/SkuDetails.cs
  mono/android_iap/Main.cs
  mono/android_iap/Main.tscn
  mono/android_iap/Properties/AssemblyInfo.cs
  mono/android_iap/README.md
  mono/android_iap/default_env.tres
  mono/android_iap/icon.png
  mono/android_iap/icon.png.import
  mono/android_iap/project.godot
  mono/android_iap/screenshots/.gdignore
  mono/android_iap/screenshots/1.jpg
  mono/android_iap/screenshots/2.jpg
  mono/android_iap/screenshots/3.jpg
  mono/android_iap/screenshots/4.jpg
Labels: new demo
