Repository godotengine/godot-demo-projects, pull requests merged in 2020-06, with the labels that each got.

#477 Replace _input with _unhandled_input in most places
  2d/finite_state_machine/player/bullet/bullet_spawner.gd
  2d/finite_state_machine/player/player_state_machine.gd
  2d/finite_state_machine/player/weapon/sword.gd
  2d/finite_state_machine/state_machine/state_machine.gd
  2d/hdr/beach_cave.gd
  2d/navigation/navigation.gd
  2d/navigation_astar/character.gd
  2d/navigation_astar/pathfind_astar.gd
  2d/platformer/assets/art/tileset/tileset.tres
  2d/platformer/project.godot
  2d/platformer/src/Main/Game.gd
  3d/ik/fps/example_player.gd
  3d/ik/fps/weapon_pistol.dae.import
  3d/ik/godot_battle_bot.dae.import
  3d/navmesh/navmesh.gd
  misc/window_management/control.gd
  misc/window_management/observer/observer.gd
  viewport/3d_scaling/hud.gd
  viewport/gui_in_3d/gui_3d.gd
Labels: enhancement

#478 Update Android IAP demo for 3.2.2
  misc/android_iap/iap.gd
  misc/android_iap/iap_demo.gd
  misc/android_iap/main.tscn
  misc/android_iap/project.godot
Labels: enhancement

#473 Add Physics Tests project
  3d/physics_tests/README.md
  3d/physics_tests/assets/robot_head/godot3_robot_head.mesh
  3d/physics_tests/assets/robot_head/godot3_robot_head_collision.tres
  3d/physics_tests/assets/robot_head/readme.txt
  3d/physics_tests/default_env.tres
  3d/physics_tests/icon.png
  3d/physics_tests/icon.png.import
  3d/physics_tests/main.tscn
  3d/physics_tests/project.godot
  3d/physics_tests/screenshots/.gdignore
  3d/physics_tests/screenshots/screenshot.png
  3d/physics_tests/test.gd
  3d/physics_tests/tests.gd
  3d/physics_tests/tests/functional/test_compound_shapes.tscn
  3d/physics_tests/tests/functional/test_friction.tscn
  3d/physics_tests/tests/functional/test_shapes.tscn
  3d/physics_tests/tests/performance/test_perf_contacts.gd
  3d/physics_tests/tests/performance/test_perf_contacts.tscn
  3d/physics_tests/tests/static_scene.tscn
  3d/physics_tests/tests/test_options.tscn
  3d/physics_tests/tests_menu.gd
  3d/physics_tests/utils/camera_orbit.gd
  3d/physics_tests/utils/container_log.gd
  3d/physics_tests/utils/control3d.gd
  3d/physics_tests/utils/exception_cylinder.gd
  3d/physics_tests/utils/label_engine.gd
  3d/physics_tests/utils/label_fps.gd
  3d/physics_tests/utils/label_test.gd
  3d/physics_tests/utils/label_version.gd
  3d/physics_tests/utils/option_menu.gd
  3d/physics_tests/utils/scroll_log.gd
  3d/physics_tests/utils/system.gd
  3d/physics_tests/utils/system_log.gd
Labels: new demo

#480 Remove trailing space characters in the formatting script
  2d/finite_state_machine/debug/Explanations.tscn
  2d/isometric/README.md
  2d/navigation/README.md
  2d/physics_platformer/platform/moving_platform.gd
  3d/physics_tests/README.md
  3d/platformer/player/player.gd
  LICENSE.md
  audio/bpm_sync/bpm_sync.gd
  format.sh
  gui/translation/LICENSE.DroidSans.txt
  loading/threads/README.md
  misc/2.5d/assets/ui/overlay.tscn
  misc/2.5d/assets/ui/overlay_cube.tscn
  misc/instancing/README.md
  misc/joypads/README.md
  misc/regex/README.md
  misc/sensors/main.gd
  misc/tween/README.md
  misc/window_management/README.md
  mono/2.5d/addons/node25d-cs/Node25D.cs
  mono/2.5d/addons/node25d-cs/main_screen/.broken-cs-files/Viewport25D.cs
  mono/2.5d/assets/ui/overlay.tscn
  mono/2.5d/assets/ui/overlay_cube.tscn
  mono/dodge_the_creeps/Main.cs
  mono/dodge_the_creeps/Mob.cs
  networking/multiplayer_bomber/README.md
  networking/multiplayer_pong/README.md
  networking/multiplayer_pong/scripts/ball.gd
  networking/multiplayer_pong/scripts/pong.gd
  networking/webrtc_signaling/server_node/.eslintrc.json
  viewport/2d_in_3d/README.md
  viewport/3d_in_2d/README.md
  viewport/dynamic_split_screen/CameraController.gd
  viewport/dynamic_split_screen/README.md
  viewport/screen_capture/README.md
  visual_script/circle_pop/README.md
Labels: enhancement

#481 Switch continuous integration from Travis CI to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  format.sh
Labels: enhancement

#482 Update Android IAP demo to reflect recent changes
  misc/android_iap/iap_demo.gd
Labels: enhancement

#484 Add an operating system testing demo
  misc/os_test/actions.gd
  misc/os_test/default_env.tres
  misc/os_test/icon.png
  misc/os_test/icon.png.import
  misc/os_test/noto_sans_ui_bold.ttf
  misc/os_test/noto_sans_ui_regular.ttf
  misc/os_test/os_test.gd
  misc/os_test/os_test.tscn
  misc/os_test/project.godot
Labels: new demo

#486 Add Mono C# preprocessor defines, README, and screenshots to OS testing demo
  misc/os_test/MonoTest.cs
  misc/os_test/Operating System Testing.csproj
  misc/os_test/Operating System Testing.sln
  misc/os_test/Properties/AssemblyInfo.cs
  misc/os_test/README.md
  misc/os_test/actions.gd
  misc/os_test/os_test.gd
  misc/os_test/os_test.tscn
  misc/os_test/screenshots/.gdignore
  misc/os_test/screenshots/mono.png
  misc/os_test/screenshots/top-hidpi.png
Labels: enhancement

#488 Clean up unused and outdated environment files
  2d/dodge_the_creeps/default_env.tres
  2d/dodge_the_creeps/project.godot
  2d/finite_state_machine/default_env.tres
  2d/finite_state_machine/project.godot
  2d/gd_paint/default_env.tres
  2d/gd_paint/project.godot
  2d/navigation_astar/default_env.tres
  2d/navigation_astar/project.godot
  2d/role_playing_game/default_env.tres
  2d/role_playing_game/project.godot
  2d/sprite_shaders/default_env.tres
  2d/sprite_shaders/project.godot
  3d/material_testers/models/godot_ball.dae.import
  3d/material_testers/models/test_bed/test_bed.glb.import
  3d/material_testers/models/test_bed/test_bed.tscn
  3d/physics_tests/default_env.tres
  3d/physics_tests/project.godot
  3d/truck_town/default_env.tres
  audio/device_changer/default_env.tres
  audio/device_changer/project.godot
  audio/mic_record/default_env.tres
  audio/mic_record/project.godot
  loading/multiple_threads_loading/default_env.tres
  loading/multiple_threads_loading/project.godot
  misc/2.5d/default_env.tres
  misc/2.5d/project.godot
  misc/multitouch_view/default_env.tres
  misc/multitouch_view/project.godot
  misc/os_test/default_env.tres
  misc/os_test/project.godot
  misc/sensors/cube_6.png.import
  misc/sensors/default_env.tres
  misc/sensors/icon.png.import
  misc/sensors/main.tscn
  mono/2.5d/default_env.tres
  mono/2.5d/project.godot
  mono/dodge_the_creeps/default_env.tres
  mono/dodge_the_creeps/project.godot
  networking/websocket_multiplayer/default_env.tres
  networking/websocket_multiplayer/project.godot
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/2d_in_3d/default_env.tres
  viewport/3d_in_2d/default_env.tres
  viewport/3d_in_2d/project.godot
  viewport/dynamic_split_screen/SplitScreen.tscn
  viewport/dynamic_split_screen/default_env.tres
  viewport/gui_in_3d/default_env.tres
  viewport/screen_capture/default_env.tres
  viewport/screen_capture/project.godot
  visual_script/circle_pop/default_env.tres
  visual_script/circle_pop/project.godot
  visual_script/multitouch_view/default_env.tres
  visual_script/multitouch_view/project.godot
Labels: enhancement, update

#490 Misc fixes and tweaks to many demos for 3.2.2
  2d/hexagonal_map/troll.tscn
  2d/isometric/tileset.tres
  2d/navigation_astar/Game.tscn
  2d/particles/particles.tscn
  2d/physics_platformer/Tileset.tres
  2d/physics_platformer/background/Seesaw.tscn
  3d/kinematic_character/default_env.tres
  3d/kinematic_character/level.tscn
  3d/kinematic_character/project.godot
  3d/kinematic_character/purple_cube.tscn
  3d/navmesh/default_env.tres
  3d/navmesh/navmesh.tscn
  3d/navmesh/project.godot
  3d/voxel/project.godot
  gui/translation/text.en.translation
  gui/translation/text.es.translation
  gui/translation/text.ja.translation
  loading/autoload/global.gd
  loading/autoload/scene_b.tscn
  misc/android_iap/iap_demo.gd
  viewport/2d_in_3d/2D_in_3D.gd
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/2d_in_3d/pong.gd
  viewport/3d_scaling/cubes.tscn
  viewport/3d_scaling/hud.tscn
  viewport/dynamic_split_screen/camera_controller.gd
  viewport/dynamic_split_screen/player.gd
  viewport/dynamic_split_screen/project.godot
  viewport/dynamic_split_screen/split_screen.shader
  viewport/dynamic_split_screen/split_screen.tscn
  viewport/dynamic_split_screen/wall_coloring.gd
Labels: enhancement, update

#489 Tweak the 3D platformer demo
  3d/platformer/default_env.tres
  3d/platformer/project.godot
  3d/platformer/stage/floor_mesh.tres
  3d/platformer/stage/stage.tscn
  3d/platformer/stage/tiles.tres
  3d/platformer/stage/tiles.tscn
Labels: enhancement
