Repository godotengine/godot-demo-projects, pull requests merged in 2020-01, with the labels that each got.

#370 Disable ETC2 texture compression in the Material Testers demo
  3d/material_testers/project.godot
Labels: enhancement

#331 Update and optimize 3D KC demo
  3d/kinematic_character/cubelib.res
  3d/kinematic_character/cubelib.tres
  3d/kinematic_character/cubio.gd
  3d/kinematic_character/cubio.tscn
  3d/kinematic_character/follow_camera.gd
  3d/kinematic_character/level.scn
  3d/kinematic_character/level.tscn
  3d/kinematic_character/project.godot
  3d/kinematic_character/purplecube.scn
  3d/kinematic_character/purplecube.tscn
Labels: enhancement

#374 Update Audio Device Changer demo to Godot 3.1.2
  audio/device_changer/Changer.gd
  audio/device_changer/Changer.tscn
  audio/device_changer/Control.gd
  audio/device_changer/Control.tscn
  audio/device_changer/default_env.tres
  audio/device_changer/icon.png.import
  audio/device_changer/project.godot
Labels: update

#337 Extract shader code from 2D shader demos
  2d/screen_space_shaders/screen_shaders.tscn
  2d/screen_space_shaders/shaders/BCS.shader
  2d/screen_space_shaders/shaders/blur.shader
  2d/screen_space_shaders/shaders/contrasted.shader
  2d/screen_space_shaders/shaders/mirage.shader
  2d/screen_space_shaders/shaders/negative.shader
  2d/screen_space_shaders/shaders/normalized.shader
  2d/screen_space_shaders/shaders/old_film.shader
  2d/screen_space_shaders/shaders/pixelize.shader
  2d/screen_space_shaders/shaders/sepia.shader
  2d/screen_space_shaders/shaders/vignette.shader
  2d/screen_space_shaders/shaders/whirl.shader
  2d/sprite_shaders/shaders/aura.shader
  2d/sprite_shaders/shaders/blur.shader
  2d/sprite_shaders/shaders/dissintegrate.shader
  2d/sprite_shaders/shaders/dropshadow.shader
  2d/sprite_shaders/shaders/fatty.shader
  2d/sprite_shaders/shaders/glow.shader
  2d/sprite_shaders/shaders/offsetshadow.shader
  2d/sprite_shaders/shaders/outline.shader
  2d/sprite_shaders/shaders/silouette.shader
  2d/sprite_shaders/sprite_shaders.tscn
Labels: enhancement, topic:shaders

#323 Make the Platformer 2D demo work with ultrawide displays
  2d/platformer/Stage.tscn
  2d/platformer/background/ParallaxBg.tscn
  2d/platformer/background/scroll_bg_fg_1.png
  2d/platformer/background/scroll_bg_fg_1.png.import
  2d/platformer/background/scroll_bg_fg_2.png
  2d/platformer/background/scroll_bg_fg_2.png.import
  2d/platformer/player/Player.tscn
  2d/platformer/project.godot
Labels: enhancement

#89 Added a simple drawing demo (GD paint)
  2d/gd_paint/PaintControl.gd
  2d/gd_paint/PaintTools.png
  2d/gd_paint/Paint_root.tscn
  2d/gd_paint/ToolsPanel.gd
  2d/gd_paint/default_env.tres
  2d/gd_paint/icon.png
  2d/gd_paint/project.godot
Labels: new demo

#324 Port 2d/role_playing_game to Godot 3.1
  2d/role_playing_game/Game.gd
  2d/role_playing_game/dialogue/dialogue_player/DialoguePlayer.tscn
  2d/role_playing_game/dialogue/interface/Interface.tscn
  2d/role_playing_game/grid_movement/grid/Grid.gd
  2d/role_playing_game/grid_movement/pawns/Actor.gd
  2d/role_playing_game/grid_movement/pawns/Actor.tscn
  2d/role_playing_game/grid_movement/pawns/Character.tscn
  2d/role_playing_game/grid_movement/pawns/Pawn.gd
  2d/role_playing_game/grid_movement/pawns/Walker.gd
  2d/role_playing_game/grid_movement/pawns/character.png.import
  2d/role_playing_game/grid_movement/tilesets/grid/GridTiles.tscn
  2d/role_playing_game/grid_movement/tilesets/grid/actor.png.import
  2d/role_playing_game/grid_movement/tilesets/grid/object.png.import
  2d/role_playing_game/grid_movement/tilesets/grid/obstacle.png.import
  2d/role_playing_game/grid_movement/tilesets/grid_lines/GridLinesTiles.tscn
  2d/role_playing_game/grid_movement/tilesets/grid_lines/grid_lines.png.import
  2d/role_playing_game/project.godot
  2d/role_playing_game/screens/combat/Combat.tscn
  2d/role_playing_game/screens/combat/actors/Actor.tscn
  2d/role_playing_game/screens/combat/actors/Opponent.tscn
  2d/role_playing_game/screens/combat/actors/Player.tscn
  2d/role_playing_game/screens/combat/actors/sprites/Sprite.tscn
  2d/role_playing_game/screens/combat/actors/sprites/blue.png.import
  2d/role_playing_game/screens/combat/actors/sprites/green.png.import
  2d/role_playing_game/screens/combat/actors/sprites/shadow.png.import
  2d/role_playing_game/screens/combat/interface/ActorInfo.tscn
  2d/role_playing_game/screens/combat/interface/Info.tscn
  2d/role_playing_game/theme/Theme.tscn
  2d/role_playing_game/theme/button/button_rect.png.import
  2d/role_playing_game/theme/button/button_rect_pressed.png.import
  2d/role_playing_game/theme/labels/Title.tscn
  2d/role_playing_game/theme/panel/panel_rect.png.import
  2d/role_playing_game/theme/progressbar/background.png.import
  2d/role_playing_game/theme/progressbar/foreground_blue.png.import
  2d/role_playing_game/theme/progressbar/foreground_red.png.import
  2d/role_playing_game/turn_combat/combatants/Combatant.tscn
  2d/role_playing_game/turn_combat/combatants/Opponent.tscn
  2d/role_playing_game/turn_combat/combatants/Player.tscn
  2d/role_playing_game/turn_combat/combatants/health/Health.gd
  2d/role_playing_game/turn_combat/combatants/health/Health.tscn
  2d/role_playing_game/turn_combat/combatants/sprites/Sprite.tscn
  2d/role_playing_game/turn_combat/turn_queue/TurnQueue.tscn
Labels: enhancement, update

#376 Update and improve plugin demos
  README.md
  plugins/README.md
  plugins/custom_dock/custom_dock.tscn
  plugins/custom_dock/dock_plugin.gd
  plugins/custom_dock/plugin.cfg
  plugins/custom_import_plugin/test.mtxt.import
  plugins/custom_material_creator/custom_material_dock.tscn
  plugins/custom_material_creator/silly_material_creator.gd
  plugins/custom_node/README.md
  plugins/custom_node/heart.gd
  plugins/custom_node/heart.png.import
  plugins/custom_node/heart_icon.png.import
  plugins/custom_node/heart_plugin.gd
  plugins/custom_node/plugin.cfg
  plugins/material_creator/README.md
  plugins/material_creator/material_creator.gd
  plugins/material_creator/material_dock.tscn
  plugins/material_creator/material_plugin.gd
  plugins/material_creator/material_resource.gd
  plugins/material_creator/plugin.cfg
  plugins/material_import_plugin/README.md
  plugins/material_import_plugin/import.gd
  plugins/material_import_plugin/plugin.cfg
  plugins/material_import_plugin/plugin.gd
  plugins/material_import_plugin/test.mtxt
  plugins/material_import_plugin/test.mtxt.import
  plugins/readme.txt
Labels: enhancement

#379 Update 2D in 3D demo to Godot 3.1.2
  viewport/2d_in_3d/2D_in_3D.gd
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/2d_in_3d/ball.png.import
  viewport/2d_in_3d/default_env.tres
  viewport/2d_in_3d/icon.png.import
  viewport/2d_in_3d/left_pallete.png.import
  viewport/2d_in_3d/pong.gd
  viewport/2d_in_3d/right_pallete.png.import
  viewport/2d_in_3d/separator.png.import
Labels: update

#356 Add Ball Factory
  misc/instancing/ball_factory.gd
  misc/instancing/bowling_ball.png.import
  misc/instancing/container.png
  misc/instancing/container.png.import
  misc/instancing/container.tscn
  misc/instancing/icon.png.import
Labels: enhancement

#357 Improve Pause demo
  misc/pause/pause_button.gd
  misc/pause/spinpause.tscn
Labels: enhancement

#371 Add dynamic split screen demo
  viewport/dynamic_split_screen/CameraController.gd
  viewport/dynamic_split_screen/PlayerMovement.gd
  viewport/dynamic_split_screen/README.md
  viewport/dynamic_split_screen/SplitScreen.shader
  viewport/dynamic_split_screen/SplitScreen.tscn
  viewport/dynamic_split_screen/Walls.gd
  viewport/dynamic_split_screen/default_env.tres
  viewport/dynamic_split_screen/icon.png
  viewport/dynamic_split_screen/icon.png.import
  viewport/dynamic_split_screen/project.godot
Labels: enhancement, new demo

#381 Move loading demos to their own folder
  loading/autoload/global.gd
  loading/autoload/project.godot
  loading/autoload/scene_a.gd
  loading/autoload/scene_a.tscn
  loading/autoload/scene_b.gd
  loading/autoload/scene_b.tscn
  loading/background_load/background_load.gd
  loading/background_load/background_load.tscn
  loading/background_load/paintings.gd
  loading/background_load/paintings.tscn
  loading/background_load/paintings/painting_babel.jpg
  loading/background_load/paintings/painting_babel.jpg.import
  loading/background_load/paintings/painting_las_meninas.png
  loading/background_load/paintings/painting_las_meninas.png.import
  loading/background_load/paintings/painting_mona_lisa.jpg
  loading/background_load/paintings/painting_mona_lisa.jpg.import
  loading/background_load/paintings/painting_old_guitarist.jpg
  loading/background_load/paintings/painting_old_guitarist.jpg.import
  loading/background_load/paintings/painting_parasol.jpg
  loading/background_load/paintings/painting_parasol.jpg.import
  loading/background_load/paintings/painting_the_swing.jpg
  loading/background_load/paintings/painting_the_swing.jpg.import
  loading/background_load/project.godot
  loading/background_load/sculptures.gd
  loading/background_load/sculptures.tscn
  loading/background_load/sculptures/sculpture_david.jpg
  loading/background_load/sculptures/sculpture_david.jpg.import
  loading/background_load/sculptures/sculpture_fountain.jpg
  loading/background_load/sculptures/sculpture_fountain.jpg.import
  loading/background_load/sculptures/sculpture_four_parts_of_earth.jpg
  loading/background_load/sculptures/sculpture_four_parts_of_earth.jpg.import
  loading/background_load/sculptures/sculpture_lincoln.jpg
  loading/background_load/sculptures/sculpture_lincoln.jpg.import
  loading/background_load/sculptures/sculpture_thinker.jpg
  loading/background_load/sculptures/sculpture_thinker.jpg.import
  loading/background_load/sculptures/sculpture_venus.png
  loading/background_load/sculptures/sculpture_venus.png.import
  loading/scene_changer/project.godot
  loading/scene_changer/scene_a.gd
  loading/scene_changer/scene_a.tscn
  loading/scene_changer/scene_b.gd
  loading/scene_changer/scene_b.tscn
  loading/threads/mona.png
  loading/threads/mona.png.import
  loading/threads/project.godot
  loading/threads/thread.gd
  loading/threads/thread.tscn
Labels: enhancement, update

#383 Update Platformer 3D demo to Godot 3.1.2
  3d/platformer/bullet.gd
  3d/platformer/bullet.scn
  3d/platformer/bullet.tscn
  3d/platformer/coin.gd
  3d/platformer/coin.scn
  3d/platformer/coin.tscn
  3d/platformer/default_bus_layout.tres
  3d/platformer/enemy.gd
  3d/platformer/enemy.scn
  3d/platformer/enemy.tscn
  3d/platformer/follow_camera.gd
  3d/platformer/player.gd
  3d/platformer/player.scn
  3d/platformer/player.tscn
  3d/platformer/project.godot
  3d/platformer/robotrigged.scn
  3d/platformer/stage.scn
  3d/platformer/stage.tscn
  3d/platformer/tiles.res
  3d/platformer/tiles.scn
  3d/platformer/tiles.tres
  3d/platformer/tiles.tscn
Labels: enhancement, update

#384 Update 3D navmesh demo to Godot 3.1.2
  3d/navmesh/navmesh.gd
  3d/navmesh/navmesh.scn
  3d/navmesh/navmesh.tscn
  3d/navmesh/project.godot
Labels: update

#385 Update and improve Truck Town for Godot 3.1.2
  3d/truck_town/car_base.tscn
  3d/truck_town/car_select.gd
  3d/truck_town/car_select.tscn
  3d/truck_town/follow_camera.gd
  3d/truck_town/project.godot
  3d/truck_town/tow_truck.tscn
  3d/truck_town/town_mesh.tscn
  3d/truck_town/town_scene.tscn
  3d/truck_town/trailer_truck.tscn
  3d/truck_town/vehicle.gd
Labels: enhancement, update
