Repository godotengine/godot-demo-projects, pull requests merged in 2020-03, with the labels that each got.

#426 Convert most demos to GLES 2 and update to Godot 3.2
  3d/ik/fabrik_ik.tscn
  3d/ik/fps/fps_example.tscn
  3d/ik/look_at_ik.tscn
  3d/ik/skeleton_ik.tscn
  3d/navmesh/navmesh.tscn
  3d/truck_town/project.godot
  audio/bpm_sync/bpm_sync.gd
  audio/bpm_sync/bpm_sync.tscn
  audio/bpm_sync/project.godot
  audio/device_changer/project.godot
  audio/generator/project.godot
  audio/mic_record/project.godot
  audio/spectrum/project.godot
  gui/drag_and_drop/project.godot
  gui/input_mapping/project.godot
  gui/rich_text_bbcode/project.godot
  gui/translation/project.godot
  loading/autoload/project.godot
  loading/background_load/project.godot
  loading/scene_changer/project.godot
  loading/threads/project.godot
  misc/android_iap/project.godot
  misc/instancing/project.godot
  misc/joypads/project.godot
  misc/matrix_transform/project.godot
  misc/multitouch_cubes/project.godot
  misc/multitouch_view/project.godot
  misc/pause/project.godot
  misc/regex/project.godot
  misc/sensors/project.godot
  misc/tween/main.tscn
  misc/tween/project.godot
  misc/window_management/project.godot
  mono/dodge_the_creeps/Dodge the Creeps C#.csproj
  mono/pong/Pong with C#.csproj
  mono/pong/project.godot
  networking/multiplayer_bomber/icon.png
  networking/multiplayer_bomber/icon.png.import
  networking/multiplayer_bomber/project.godot
  networking/multiplayer_pong/project.godot
  networking/webrtc_minimal/project.godot
  networking/webrtc_signaling/project.godot
  networking/websocket_chat/project.godot
  networking/websocket_minimal/client.gd
  networking/websocket_minimal/project.godot
  networking/websocket_minimal/server.gd
  networking/websocket_multiplayer/project.godot
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/2d_in_3d/project.godot
  viewport/3d_scaling/hud.gd
  viewport/3d_scaling/hud.tscn
  viewport/3d_scaling/project.godot
  viewport/screen_capture/project.godot
  visual_script/circle_pop/project.godot
  visual_script/multitouch_view/project.godot
  visual_script/pong/project.godot
Labels: enhancement, update

#427 Refactor the Joypads demo
  misc/joypads/joypad_diagram.tscn
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
Labels: refactor

#428 Add a splitscreen mode to the 2D platformer.
  2d/platformer/project.godot
  2d/platformer/src/Actors/Player.gd
  2d/platformer/src/Actors/Player.tscn
  2d/platformer/src/Level/Level.gd
  2d/platformer/src/Level/Level.tscn
  2d/platformer/src/Level/Music.gd
  2d/platformer/src/Main/Game.gd
  2d/platformer/src/Main/Game.tscn
  2d/platformer/src/Main/Splitscreen.tscn
  2d/platformer/src/UserInterface/PauseMenu.gd
Labels: bug, enhancement

#431 Remove the grid based movement demo
  2d/grid_based_movement/Game.tscn
  2d/grid_based_movement/default_env.tres
  2d/grid_based_movement/grid/grid.gd
  2d/grid_based_movement/icon.png
  2d/grid_based_movement/icon.png.import
  2d/grid_based_movement/pawns/Actor.tscn
  2d/grid_based_movement/pawns/actor.gd
  2d/grid_based_movement/pawns/pawn.gd
  2d/grid_based_movement/pawns/sprites/character.png
  2d/grid_based_movement/pawns/sprites/character.png.import
  2d/grid_based_movement/pawns/sprites/character_grey.png
  2d/grid_based_movement/pawns/sprites/character_grey.png.import
  2d/grid_based_movement/pawns/sprites/star.png
  2d/grid_based_movement/pawns/sprites/star.png.import
  2d/grid_based_movement/project.godot
  2d/grid_based_movement/tilesets/grid/GridTiles.tscn
  2d/grid_based_movement/tilesets/grid/actor.png
  2d/grid_based_movement/tilesets/grid/actor.png.import
  2d/grid_based_movement/tilesets/grid/grid_tileset.tres
  2d/grid_based_movement/tilesets/grid/object.png
  2d/grid_based_movement/tilesets/grid/object.png.import
  2d/grid_based_movement/tilesets/grid/obstacle.png
  2d/grid_based_movement/tilesets/grid/obstacle.png.import
  2d/grid_based_movement/tilesets/grid_lines/GridLinesTiles.tscn
  2d/grid_based_movement/tilesets/grid_lines/grid_lines.png
  2d/grid_based_movement/tilesets/grid_lines/grid_lines.png.import
  2d/grid_based_movement/tilesets/grid_lines/grid_lines_tileset.tres
Labels: discussion

#435 Fix incorrect comment in hierarchical FSM demo script
  2d/finite_state_machine/state_machine/state_machine.gd
Labels: bug

#436 Some changes to Astar and Kinematic Character 3D
  2d/navigation_astar/character.gd
  2d/navigation_astar/pathfind_astar.gd
  3d/kinematic_character/cubio.gd
  3d/kinematic_character/project.godot
Labels: enhancement

#441 Improve the issue template and add a PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#443 Tweak 2D navigation polygon demo camera and remove RPG unused files
  2d/navigation/level.tscn
  2d/role_playing_game/grid_movement/tilesets/grid/GridTiles.tscn
  2d/role_playing_game/grid_movement/tilesets/grid_lines/GridLinesTiles.tscn
Labels: enhancement

#444 Convert materials to tres format in Truck Town
  3d/truck_town/Materials/car_blue_body.material
  3d/truck_town/Materials/car_blue_body.tres
  3d/truck_town/Materials/car_grill.material
  3d/truck_town/Materials/car_grill.tres
  3d/truck_town/Materials/car_orange_body.material
  3d/truck_town/Materials/car_orange_body.tres
  3d/truck_town/Materials/car_red_body.material
  3d/truck_town/Materials/car_red_body.tres
  3d/truck_town/Materials/car_window.material
  3d/truck_town/Materials/car_window.tres
  3d/truck_town/Materials/car_yellow_body.material
  3d/truck_town/Materials/car_yellow_body.tres
  3d/truck_town/Materials/cement.material
  3d/truck_town/Materials/cement.tres
  3d/truck_town/Materials/door.material
  3d/truck_town/Materials/door.tres
  3d/truck_town/Materials/grass.material
  3d/truck_town/Materials/grass.tres
  3d/truck_town/Materials/house.material
  3d/truck_town/Materials/house.tres
  3d/truck_town/Materials/roof.material
  3d/truck_town/Materials/roof.tres
  3d/truck_town/Materials/roof2.material
  3d/truck_town/Materials/roof2.tres
  3d/truck_town/Materials/windows.material
  3d/truck_town/Materials/windows.tres
  3d/truck_town/car_base.tscn
  3d/truck_town/tow_truck.tscn
  3d/truck_town/town_mesh.tscn
  3d/truck_town/trailer_truck.tscn
Labels: enhancement

#425 Multiple-threads loading
  loading/multiple_threads_loading/README.md
  loading/multiple_threads_loading/default_env.tres
  loading/multiple_threads_loading/icon.png
  loading/multiple_threads_loading/images/icon_1.png
  loading/multiple_threads_loading/images/icon_10.png
  loading/multiple_threads_loading/images/icon_11.png
  loading/multiple_threads_loading/images/icon_12.png
  loading/multiple_threads_loading/images/icon_13.png
  loading/multiple_threads_loading/images/icon_14.png
  loading/multiple_threads_loading/images/icon_15.png
  loading/multiple_threads_loading/images/icon_16.png
  loading/multiple_threads_loading/images/icon_17.png
  loading/multiple_threads_loading/images/icon_18.png
  loading/multiple_threads_loading/images/icon_19.png
  loading/multiple_threads_loading/images/icon_2.png
  loading/multiple_threads_loading/images/icon_20.png
  loading/multiple_threads_loading/images/icon_21.png
  loading/multiple_threads_loading/images/icon_22.png
  loading/multiple_threads_loading/images/icon_23.png
  loading/multiple_threads_loading/images/icon_24.png
  loading/multiple_threads_loading/images/icon_25.png
  loading/multiple_threads_loading/images/icon_26.png
  loading/multiple_threads_loading/images/icon_27.png
  loading/multiple_threads_loading/images/icon_28.png
  loading/multiple_threads_loading/images/icon_29.png
  loading/multiple_threads_loading/images/icon_3.png
  loading/multiple_threads_loading/images/icon_30.png
  loading/multiple_threads_loading/images/icon_31.png
  loading/multiple_threads_loading/images/icon_32.png
  loading/multiple_threads_loading/images/icon_33.png
  loading/multiple_threads_loading/images/icon_34.png
  loading/multiple_threads_loading/images/icon_35.png
  loading/multiple_threads_loading/images/icon_36.png
  loading/multiple_threads_loading/images/icon_37.png
  loading/multiple_threads_loading/images/icon_38.png
  loading/multiple_threads_loading/images/icon_39.png
  loading/multiple_threads_loading/images/icon_4.png
  loading/multiple_threads_loading/images/icon_40.png
  loading/multiple_threads_loading/images/icon_5.png
  loading/multiple_threads_loading/images/icon_6.png
  loading/multiple_threads_loading/images/icon_7.png
  loading/multiple_threads_loading/images/icon_8.png
  loading/multiple_threads_loading/images/icon_9.png
  loading/multiple_threads_loading/main.tscn
  loading/multiple_threads_loading/preload.gd
  loading/multiple_threads_loading/preload.tscn
  loading/multiple_threads_loading/project.godot
  loading/multiple_threads_loading/resource_queue.gd
  loading/multiple_threads_loading/screenshots/screenshot.png
Labels: new demo

#448 Style tweaks and add import files to multiple threads loading demo
  loading/multiple_threads_loading/icon.png.import
  loading/multiple_threads_loading/images/.gitignore
  loading/multiple_threads_loading/preload.gd
  loading/multiple_threads_loading/preload.tscn
  loading/multiple_threads_loading/screenshots/.gdignore
Labels: enhancement

#445 Organize and simplify the Kinematic Character 2D demo
  2d/kinematic_character/README.md
  2d/kinematic_character/level/circle.png
  2d/kinematic_character/level/circle.png.import
  2d/kinematic_character/level/long_obstacle.png
  2d/kinematic_character/level/long_obstacle.png.import
  2d/kinematic_character/level/obstacle.png
  2d/kinematic_character/level/obstacle.png.import
  2d/kinematic_character/level/princess.gd
  2d/kinematic_character/level/princess.png
  2d/kinematic_character/level/princess.png.import
  2d/kinematic_character/player.gd
  2d/kinematic_character/player/player.gd
  2d/kinematic_character/player/player.png
  2d/kinematic_character/player/player.png.import
  2d/kinematic_character/player/player.tscn
  2d/kinematic_character/project.godot
  2d/kinematic_character/world.gd
  2d/kinematic_character/world.tscn
  2d/platformer/src/Actors/Player.gd
Labels: enhancement, refactor

#446 Move Dodge the Creeps license information into the README files
  2d/dodge_the_creeps/README.md
  2d/dodge_the_creeps/attributions.txt
  mono/dodge_the_creeps/README.md
Labels: enhancement

#447 Multitouch View tweaks
  misc/multitouch_view/TouchHelper.gd
  misc/multitouch_view/project.godot
  visual_script/multitouch_view/TouchHelper.gd
Labels: enhancement

#450 Add a formatting script for local checking and for Travis CI
  .travis.yml
  2d/dodge_the_creeps/fonts/LICENSE.txt
  format.sh
  gui/rich_text_bbcode/SIL Open Font License.txt
  gui/translation/text.csv
  networking/webrtc_minimal/Signaling.gd
Labels: enhancement

#451 simplifying steering to a single line with move_toward
  3d/truck_town/vehicle.gd
Labels: enhancement

#453 Refactor the plugin demos to be inside of a project and add main screen plugin demo
  plugins/README.md
  plugins/addons/README.md
  plugins/addons/custom_node/README.md
  plugins/addons/custom_node/heart.gd
  plugins/addons/custom_node/heart.png
  plugins/addons/custom_node/heart.png.import
  plugins/addons/custom_node/heart_icon.png
  plugins/addons/custom_node/heart_icon.png.import
  plugins/addons/custom_node/heart_plugin.gd
  plugins/addons/custom_node/plugin.cfg
  plugins/addons/main_screen/README.md
  plugins/addons/main_screen/handled_by_main_screen.gd
  plugins/addons/main_screen/main_panel.tscn
  plugins/addons/main_screen/main_screen_plugin.gd
  plugins/addons/main_screen/plugin.cfg
  plugins/addons/main_screen/print_hello.gd
  plugins/addons/material_creator/README.md
  plugins/addons/material_creator/material_creator.gd
  plugins/addons/material_creator/material_dock.tscn
  plugins/addons/material_creator/material_plugin.gd
  plugins/addons/material_creator/material_resource.gd
  plugins/addons/material_creator/plugin.cfg
  plugins/addons/material_import_plugin/README.md
  plugins/addons/material_import_plugin/import.gd
  plugins/addons/material_import_plugin/plugin.cfg
  plugins/addons/material_import_plugin/plugin.gd
  plugins/addons/material_import_plugin/test.mtxt
  plugins/addons/material_import_plugin/test.mtxt.import
  plugins/default_env.tres
  plugins/icon.png
  plugins/icon.png.import
  plugins/material_creator/README.md
  plugins/material_import_plugin/README.md
  plugins/project.godot
  plugins/test_scene.tscn
Labels: enhancement, refactor
