Repository godotengine/godot-demo-projects, pull requests merged in 2020-08, with the labels that each got.

#505 Mobile multitouch view fix
  mobile/multitouch_view/Main.gd
  mobile/multitouch_view/README.md
  mobile/multitouch_view/TouchHelper.gd
  mobile/multitouch_view/screenshots/multitouch.png
  visual_script/multitouch_view/TouchHelper.gd
Labels: bug

#504 Android IAP Response Code can now return null.
  mobile/android_iap/iap_demo.gd
  mono/android_iap/GodotGooglePlayBilling/BillingResult.cs
  mono/android_iap/Main.cs
Labels: discussion, enhancement, topic:mono

#507 Rewriting Mono Android IAP to match with GDScript
  mono/android_iap/Android IAP with C#.sln
  mono/android_iap/Android in-app purchases with C#.csproj
  mono/android_iap/Android in-app purchases with C#.sln
  mono/android_iap/GodotGooglePlayBilling/BillingResult.cs
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBillingUtils.cs
  mono/android_iap/GodotGooglePlayBilling/Purchase.cs
  mono/android_iap/GodotGooglePlayBilling/PurchasesResult.cs
  mono/android_iap/GodotGooglePlayBilling/SkuDetails.cs
  mono/android_iap/Main.cs
  mono/android_iap/Main.tscn
  mono/android_iap/Properties/AssemblyInfo.cs
  mono/android_iap/README.md
  mono/android_iap/main.tscn
  mono/android_iap/project.godot
  mono/android_iap/screenshots/.gdignore
  mono/android_iap/screenshots/1.jpg
  mono/android_iap/screenshots/2.jpg
  mono/android_iap/screenshots/3.jpg
  mono/android_iap/screenshots/4.jpg
Labels: enhancement, topic:mono

#506 Add a GUI theming override demo
  gui/theming_override/README.md
  gui/theming_override/icon.png
  gui/theming_override/icon.png.import
  gui/theming_override/project.godot
  gui/theming_override/screenshots/theming_override.png
  gui/theming_override/screenshots/theming_override.png.import
  gui/theming_override/test.gd
  gui/theming_override/test.tscn
Labels: new demo

#508 Tweak settings in various 3D demos
  3d/ik/default_env.tres
  3d/ik/look_at_ik.tscn
  3d/ik/project.godot
  3d/kinematic_character/cubio.gd
  3d/kinematic_character/default_env.tres
  3d/kinematic_character/level.tscn
  3d/material_testers/default_env.tres
  3d/material_testers/tester.gd
  3d/navmesh/navmesh.gd
  3d/navmesh/project.godot
  3d/physics_tests/project.godot
  3d/platformer/default_env.tres
  3d/platformer/stage/stage.tscn
  3d/truck_town/default_env.tres
  3d/truck_town/project.godot
  3d/voxel/project.godot
Labels: enhancement

#510 Fix minor problems with Dodge the Creeps metadata
  2d/dodge_the_creeps/project.godot
  mono/dodge_the_creeps/README.md
Labels: bug

#511 Add a normal map test in the 2D lights and shadows demo
  2d/lights_and_shadows/godot.png
  2d/lights_and_shadows/godot.png.import
  2d/lights_and_shadows/godot_normal.png
  2d/lights_and_shadows/godot_normal.png.import
  2d/lights_and_shadows/light_shadows.tscn
Labels: enhancement

#513 Avoid freeing network peer during signal emission.
  networking/multiplayer_bomber/gamestate.gd
  networking/multiplayer_pong/logic/lobby.gd
  networking/websocket_multiplayer/script/main.gd
Labels: bug, topic:networking
