Repository godotengine/godot-demo-projects, pull requests merged in 2020-10, with the labels that each got.

#524 Allow hiDPI in all demos that support multiple resolutions
  2d/finite_state_machine/project.godot
  2d/gd_paint/project.godot
  2d/hdr/project.godot
  2d/hexagonal_map/project.godot
  2d/instancing/project.godot
  2d/isometric/project.godot
  2d/kinematic_character/project.godot
  2d/light2d_as_mask/project.godot
  2d/lights_and_shadows/project.godot
  2d/navigation/project.godot
  2d/navigation_astar/project.godot
  2d/particles/project.godot
  2d/physics_platformer/project.godot
  2d/pong/project.godot
  2d/role_playing_game/project.godot
  2d/screen_space_shaders/project.godot
  2d/sprite_shaders/project.godot
  2d/tween/project.godot
  3d/ik/project.godot
  3d/material_testers/project.godot
  3d/physics_tests/project.godot
  3d/truck_town/project.godot
  3d/voxel/project.godot
  audio/mic_record/project.godot
  gui/drag_and_drop/project.godot
  gui/input_mapping/project.godot
  gui/regex/project.godot
  gui/rich_text_bbcode/project.godot
  gui/sdf_font/project.godot
  gui/theming_override/project.godot
  gui/translation/project.godot
  loading/autoload/project.godot
  loading/background_load/project.godot
  loading/scene_changer/project.godot
  loading/threads/project.godot
  misc/joypads/project.godot
  misc/opensimplexnoise/project.godot
  misc/os_test/project.godot
  misc/pause/project.godot
  misc/window_management/project.godot
  mobile/android_iap/project.godot
  mono/android_iap/project.godot
  mono/pong/project.godot
  networking/multiplayer_bomber/project.godot
  networking/multiplayer_pong/project.godot
  networking/webrtc_minimal/project.godot
  networking/webrtc_signaling/project.godot
  viewport/3d_in_2d/project.godot
  viewport/3d_scaling/project.godot
  viewport/screen_capture/project.godot
  visual_script/pong/project.godot
Labels: enhancement

#526 Update C# demos for Godot 3.2.3
  misc/os_test/MonoTest.cs
  misc/os_test/Operating System Testing.csproj
  misc/os_test/Operating System Testing.sln
  misc/os_test/os_test.gd
  mono/2.5d/2.5D Demo with C#.csproj
  mono/README.md
  mono/android_iap/Android in-app purchases with C#.csproj
  mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
  mono/pong/Pong with C#.csproj
Labels: topic:mono, update

#528 Remove Panel nodes that don't have panels
  gui/rich_text_bbcode/rich_text_bbcode.gd
  gui/rich_text_bbcode/rich_text_bbcode.tscn
  gui/translation/translation_demo.gd
  gui/translation/translation_demo.tscn
Labels: enhancement

#531 Update dodge_the_creeps to Godot 3.2.3 format
  .editorconfig
  2d/dodge_the_creeps/Main.gd
  2d/dodge_the_creeps/Main.tscn
  2d/dodge_the_creeps/Mob.gd
  2d/dodge_the_creeps/Mob.tscn
  2d/dodge_the_creeps/Player.gd
  mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
  mono/dodge_the_creeps/HUD.cs
  mono/dodge_the_creeps/Main.cs
  mono/dodge_the_creeps/Main.tscn
  mono/dodge_the_creeps/Mob.cs
  mono/dodge_the_creeps/Mob.tscn
  mono/dodge_the_creeps/Player.cs
  mono/dodge_the_creeps/Player.tscn
  mono/dodge_the_creeps/Properties/AssemblyInfo.cs
Labels: enhancement, topic:mono

#532 Dodge the Creeps: Remove unused asset
  2d/dodge_the_creeps/art/set3_tiles.png
  2d/dodge_the_creeps/art/set3_tiles.png.import
  2d/dodge_the_creeps/fonts/FONTLOG.txt
Labels: enhancement

#533 Improve Dodge the Creeps demo
  mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
Labels: enhancement, topic:mono

#537 Update C# project files in C# demos for Godot 3.2.3
  misc/os_test/Operating System Testing.csproj
  misc/os_test/Properties/AssemblyInfo.cs
  mono/2.5d/2.5D Demo with C#.csproj
  mono/2.5d/Properties/AssemblyInfo.cs
  mono/android_iap/Android in-app purchases with C#.csproj
  mono/android_iap/Properties/AssemblyInfo.cs
  mono/pong/Pong with C#.csproj
  mono/pong/Properties/AssemblyInfo.cs
Labels: topic:mono, update

#539 Check for updates to GitHub Actions every weekday
  .github/dependabot.yml
Labels: enhancement

#540 Re-write the navigation path-following code to be easier to read + add comments
  3d/navmesh/navmesh.gd
Labels: enhancement

#536 Change Dodge the Creeps to be more consistent with the docs
  2d/dodge_the_creeps/Main.gd
  2d/dodge_the_creeps/Main.tscn
  2d/dodge_the_creeps/Player.gd
  mono/dodge_the_creeps/Main.cs
  mono/dodge_the_creeps/Main.tscn
  mono/dodge_the_creeps/Player.cs
Labels: enhancement

#544 Add trailing commas to enums
  2d/gd_paint/paint_control.gd
  2d/physics_platformer/enemy/enemy.gd
  2d/platformer/src/Actors/Enemy.gd
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/GodotGooglePlayBilling/Purchase.cs
Labels: enhancement
