Repository godotengine/godot-demo-projects, pull requests merged in 2021-07, with the labels that each got.

#631 Use "not" instead of the exclamation mark in GDScript files
  2d/finite_state_machine/debug/states_stack_displayer.gd
  2d/finite_state_machine/player/states/debug/state_name_displayer.gd
  2d/navigation_astar/character.gd
  2d/physics_tests/tests/functional/test_collision_pairs.gd
  2d/physics_tests/tests/functional/test_raycasting.gd
  2d/physics_tests/tests/performance/test_perf_contacts.gd
  2d/pong/logic/paddle.gd
  2d/pong/project.godot
  2d/screen_space_shaders/screen_shaders.gd
  3d/material_testers/tester.gd
  3d/physics_tests/tests/functional/test_collision_pairs.gd
  3d/physics_tests/tests/performance/test_perf_contacts.gd
  3d/platformer/player/follow_camera.gd
  3d/platformer/player/player.gd
  3d/voxel/menu/debug.gd
  3d/voxel/menu/ingame/pause_menu.gd
  audio/bpm_sync/bpm_sync.gd
  misc/2.5d/addons/node25d/main_screen/gizmo_25d.gd
  misc/2.5d/addons/node25d/main_screen/viewport_25d.gd
  misc/2.5d/addons/node25d/node_25d.gd
  misc/2.5d/assets/player/player_math_25d.gd
  misc/2.5d/assets/player/player_sprite.gd
  misc/2.5d/assets/ui/control_hints.gd
  misc/window_management/control.gd
  misc/window_management/observer/observer.gd
  mobile/android_iap/iap_demo.gd
  mobile/multitouch_cubes/GestureArea.gd
  mono/2.5d/addons/node25d-cs/main_screen/viewport_25d.gd
  mono/2.5d/assets/ui/control_hints.gd
  networking/multiplayer_bomber/player.gd
Labels: enhancement

#633 Use the Jump sound already present in the Platformer 2D demo
  2d/platformer/src/Actors/Player.gd
Labels: enhancement

#632 Fix bullets in the Finite State Machine demo
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/player/Player.tscn
  2d/finite_state_machine/player/bullet/bullet_spawner.gd
Labels: bug, enhancement

#635 Minor tweaks to Pong and Dodge the Creeps
  2d/dodge_the_creeps/Main.gd
  2d/dodge_the_creeps/Mob.gd
  2d/dodge_the_creeps/README.md
  2d/pong/README.md
  2d/pong/logic/ball.gd
  3d/voxel/settings.gd
  mono/dodge_the_creeps/Main.cs
  mono/dodge_the_creeps/Mob.cs
  mono/dodge_the_creeps/README.md
  mono/pong/README.md
  networking/webrtc_minimal/chat.gd
  networking/webrtc_minimal/main.gd
Labels: enhancement

#634 Update impact, rigid groundcheck, moving platform
  3d/physics_tests/tests/functional/test_moving_platform.gd
  3d/physics_tests/tests/functional/test_moving_platform.tscn
  3d/physics_tests/tests/functional/test_rigidbody_ground_check.gd
  3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
  3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
Labels: enhancement, topic:physics
