Repository godotengine/godot-demo-projects, pull requests merged in 2021-04, with the labels that each got.

#604 Fix MIDI devices scanning
  misc/os_test/os_test.gd
Labels: bug

#606 Updated 2d/3d physics contact performance tests
  2d/physics_tests/test.gd
  2d/physics_tests/tests/functional/test_collision_pairs.gd
  2d/physics_tests/tests/functional/test_joints.gd
  2d/physics_tests/tests/functional/test_pyramid.gd
  2d/physics_tests/tests/functional/test_stack.gd
  2d/physics_tests/tests/performance/test_perf_broadphase.gd
  2d/physics_tests/tests/performance/test_perf_contacts.gd
  2d/physics_tests/tests/performance/test_perf_contacts.tscn
  2d/physics_tests/utils/option_menu.gd
  3d/physics_tests/test.gd
  3d/physics_tests/tests/functional/test_collision_pairs.gd
  3d/physics_tests/tests/functional/test_joints.gd
  3d/physics_tests/tests/performance/test_perf_broadphase.gd
  3d/physics_tests/tests/performance/test_perf_contacts.gd
  3d/physics_tests/tests/performance/test_perf_contacts.tscn
  3d/physics_tests/tests/performance/test_perf_contacts_extended.tscn
  3d/physics_tests/utils/option_menu.gd
Labels: enhancement, topic:physics

#607 Update README for the new 3.2 branch
  .editorconfig
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature---enhancement-request.md
  2d/physics_tests/README.md
  3d/physics_tests/README.md
  README.md
  networking/webrtc_signaling/README.md
Labels: update

#608 [2.1] Update README for the new 3.2 branch
  .editorconfig
  .gitattributes
  .gitignore
  LICENSE.md
  README.md
  gui/rich_text_bbcode/OFL.txt
Labels: update

#609 [3.0] Update README for the new 3.2 branch
  .editorconfig
  .gitattributes
  .gitignore
  2d/dodge_the_creeps/fonts/LICENSE.txt
  LICENSE.md
  README.md
Labels: update

#610 [3.1] Update README for the new 3.2 branch
  .editorconfig
  .gitattributes
  .gitignore
  2d/dodge_the_creeps/fonts/LICENSE.txt
  LICENSE.md
  README.md
  networking/webrtc_signaling/README.md
Labels: update

#611 [3.2] Update README for the new 3.2 branch
  README.md
Labels: update

#612 Physics Tests 3.3 update
  2d/physics_tests/tests/functional/test_shapes.tscn
  3d/physics_tests/test.gd
  3d/physics_tests/tests/functional/test_collision_pairs.tscn
  3d/physics_tests/tests/functional/test_raycasting.tscn
  3d/physics_tests/tests/functional/test_shapes.tscn
  3d/physics_tests/tests/performance/test_perf_contacts.tscn
  3d/physics_tests/tests/performance/test_perf_contacts_extended.tscn
  3d/physics_tests/utils/exception_cylinder.gd
Labels: bug, enhancement, topic:physics
