Repository godotengine/godot-demo-projects, pull requests merged in 2021-03, with the labels that each got.

#588 Port the Bullet Shower demo from Godot 2.1
  2d/bullet_shower/README.md
  2d/bullet_shower/bullet.png
  2d/bullet_shower/bullet.png.import
  2d/bullet_shower/bullets.gd
  2d/bullet_shower/face_happy.png
  2d/bullet_shower/face_happy.png.import
  2d/bullet_shower/face_sad.png
  2d/bullet_shower/face_sad.png.import
  2d/bullet_shower/icon.png
  2d/bullet_shower/icon.png.import
  2d/bullet_shower/player.gd
  2d/bullet_shower/project.godot
  2d/bullet_shower/screenshots/.gdignore
  2d/bullet_shower/screenshots/collision.png
  2d/bullet_shower/screenshots/no_collision.png
  2d/bullet_shower/shower.tscn
Labels: enhancement

#589 Improve the 3D platformer demo
  3d/platformer/enemy/enemy.gd
  3d/platformer/player/follow_camera.gd
  3d/platformer/player/player.gd
  3d/platformer/player/player.tscn
  3d/platformer/project.godot
  3d/platformer/stage/stage.tscn
  3d/platformer/stage/texturemr.png.import
Labels: enhancement

#586 Improve several demos' configuration
  3d/kinematic_character/project.godot
  3d/kinematic_character/purple_wood.png.import
  3d/kinematic_character/white_wood.png.import
  3d/material_testers/project.godot
  3d/material_testers/test_materials/aluminium_albedo.png.import
  3d/material_testers/test_materials/aluminium_flow.png.import
  3d/material_testers/test_materials/aluminium_normal.png.import
  3d/material_testers/test_materials/marble_albedo.png.import
  3d/material_testers/test_materials/rock_albedo.jpg.import
  3d/material_testers/test_materials/rock_ao.jpg.import
  3d/material_testers/test_materials/rock_depth.jpg.import
  3d/material_testers/test_materials/rock_metal.jpg.import
  3d/material_testers/test_materials/rock_rough.jpg.import
  3d/material_testers/test_materials/sand_albedo.jpg.import
  3d/material_testers/test_materials/sand_metal.jpg.import
  3d/material_testers/test_materials/sand_normal.jpg.import
  3d/material_testers/test_materials/sand_rough.jpg.import
  3d/material_testers/test_materials/sand_shine.jpg.import
  3d/material_testers/test_materials/texture_bricks.jpg.import
  3d/material_testers/test_materials/texture_bricks_depth.jpg.import
  3d/material_testers/test_materials/texture_bricks_metal.jpg.import
  3d/material_testers/test_materials/texture_bricks_normal.jpg.import
  3d/material_testers/test_materials/texture_cheese_albedo.png.import
  3d/material_testers/test_materials/texture_cheese_ao.png.import
  3d/material_testers/test_materials/texture_cheese_depth.png.import
  3d/material_testers/test_materials/texture_cheese_normal.png.import
  3d/material_testers/test_materials/texture_rock_albedo.png.import
  3d/material_testers/test_materials/texture_rock_ao.png.import
  3d/material_testers/test_materials/texture_rock_depth.png.import
  3d/material_testers/test_materials/texture_rock_metal.png.import
  3d/material_testers/test_materials/texture_rock_normal.png.import
  3d/material_testers/test_materials/texture_wood.png.import
  3d/material_testers/test_materials/wool_albedo.png.import
  3d/material_testers/test_materials/wool_depth.png.import
  3d/material_testers/test_materials/wool_normal.png.import
  3d/navmesh/project.godot
  3d/platformer/project.godot
  3d/platformer/stage/texture.png.import
  3d/platformer/stage/texturemr.png.import
  3d/truck_town/Images/cement.png.import
  3d/truck_town/Images/grass.png.import
  3d/truck_town/project.godot
  3d/voxel/project.godot
  3d/voxel/world/textures/texture_sheet.png.import
  mobile/android_iap/project.godot
  mobile/multitouch_cubes/project.godot
  viewport/dynamic_split_screen/project.godot
  viewport/dynamic_split_screen/split_screen.tscn
Labels: enhancement

#590 Improve the Kinematic Character 3D demo
  3d/kinematic_character/cubelib.tres
  3d/kinematic_character/cubio.tscn
  3d/kinematic_character/gi_probe_data.res
  3d/kinematic_character/icon.png
  3d/kinematic_character/level.tscn
  3d/kinematic_character/models/cube.glb
  3d/kinematic_character/models/cube.glb.import
  3d/kinematic_character/models/cube.mesh
  3d/kinematic_character/models/cube_material.tres
  3d/kinematic_character/models/mushroom.glb
  3d/kinematic_character/models/mushroom.glb.import
  3d/kinematic_character/models/white_cube_material.tres
  3d/kinematic_character/models/white_wood.png
  3d/kinematic_character/models/white_wood.png.import
  3d/kinematic_character/player/cubio.gd
  3d/kinematic_character/player/cubio.tscn
  3d/kinematic_character/player/follow_camera.gd
  3d/kinematic_character/project.godot
  3d/kinematic_character/purple_cube.tscn
  3d/kinematic_character/purple_wood.png
  3d/kinematic_character/purple_wood.png.import
  3d/kinematic_character/screenshots/editor.png
  3d/kinematic_character/screenshots/ingame.png
  3d/kinematic_character/white_wood.png
Labels: enhancement

#591 Misc improvements and tweaks for 3.2.3
  2d/dodge_the_creeps/Mob.tscn
  2d/finite_state_machine/player/Player.tscn
  2d/particles/particles.tscn
  2d/physics_tests/main.tscn
  2d/physics_tests/tests/functional/test_character_slopes.tscn
  2d/physics_tests/tests/functional/test_one_way_collision.tscn
  2d/pong/paddle.png.import
  2d/role_playing_game/grid_movement/pawns/Actor.tscn
  2d/role_playing_game/screens/combat/actors/sprites/Sprite.tscn
  2d/role_playing_game/screens/combat/interface/ActorInfo.tscn
  2d/role_playing_game/screens/combat/interface/Info.tscn
  2d/role_playing_game/theme/Theme.tscn
  2d/role_playing_game/theme/labels/Title.tscn
  2d/role_playing_game/turn_combat/combatants/Combatant.tscn
  2d/screen_space_shaders/screen_shaders.gd
  3d/ik/look_at_ik.tscn
  3d/material_testers/project.godot
  3d/physics_tests/main.tscn
  3d/platformer/project.godot
  3d/platformer/stage/stage.tscn
  3d/platformer/stage/tiles.tres
  3d/truck_town/project.godot
  3d/voxel/player/player.tscn
  3d/voxel/project.godot
  gui/drag_and_drop/drag_and_drop.tscn
  gui/input_mapping/InputRemapMenu.tscn
  loading/background_load/background_load.tscn
  loading/scene_changer/scene_a.tscn
  loading/scene_changer/scene_b.tscn
  misc/2.5d/assets/cube/cube.tscn
  misc/2.5d/assets/cube/cube_point.tscn
  misc/2.5d/assets/platform/platform.tscn
  misc/joypads/joypads.tscn
  misc/joypads/remap/remap_wizard.tscn
  mono/dodge_the_creeps/Mob.tscn
  mono/dodge_the_creeps/Player.tscn
  mono/multiplayer_pong/paddle.png.import
  mono/pong/ball.png.import
  mono/pong/paddle.png.import
  networking/multiplayer_bomber/player.gd
  networking/multiplayer_bomber/rock.gd
  networking/webrtc_minimal/Signaling.gd
  networking/websocket_chat/server/server.tscn
  plugins/addons/material_creator/material_dock.tscn
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/3d_scaling/hud.tscn
  visual_script/multitouch_view/project.godot
  visual_script/pong/paddle.png.import
Labels: enhancement

#592 Set the reset position from the initial start position in KC3D
  3d/kinematic_character/player/cubio.gd
Labels: bug

#593 Physics test cases, cancel previous running test properly
  2d/physics_tests/test.gd
  2d/physics_tests/tests/functional/test_character.gd
  2d/physics_tests/tests/functional/test_character_pixels.gd
  2d/physics_tests/tests/functional/test_character_tilemap.gd
  2d/physics_tests/tests/functional/test_one_way_collision.gd
Labels: bug, topic:physics

#594 Add links to the Asset Library after release 3.2-5c154da
  .github/CODEOWNERS
  2d/bullet_shower/README.md
  2d/physics_tests/README.md
  3d/waypoints/README.md
  gui/control_gallery/README.md
  loading/serialization/README.md
Labels: enhancement

#597 Handle up to 24 joypad buttons in the Joypads demo
  misc/joypads/joypad_diagram.tscn
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
Labels: bug

#595 Small improvement for Bullet Shower Demo
  2d/bullet_shower/bullets.gd
Labels: enhancement

#601 Use fewer ternary operators and decrease volume of Platformer 2D
  2d/finite_state_machine/player/states/motion/in_air/jump.gd
  2d/finite_state_machine/player/states/motion/on_ground/move.gd
  2d/platformer/src/Actors/Enemy.gd
  2d/platformer/src/Actors/Player.gd
  2d/platformer/src/Level/Music.gd
  2d/pong/logic/paddle.gd
  3d/voxel/menu/ingame/pause_menu.gd
  misc/joypads/remap/remap_wizard.gd
  networking/websocket_chat/utils.gd
Labels: enhancement
