Repository godotengine/godot-demo-projects, pull requests merged in 2021-05, with the labels that each got.

#614 Improve performance in GridMap demos by adjusting octant size
  3d/kinematic_character/level.tscn
  3d/kinematic_character/models/cube.glb.import
  3d/kinematic_character/models/mushroom.glb.import
  3d/platformer/stage/stage.tscn
  3d/voxel/player/player.tscn
  3d/voxel/project.godot
Labels: enhancement

#615 Fix hack to draw shapes in 3D physics tests
  3d/physics_tests/test.gd
Labels: enhancement, topic:physics

#621 Fixed project settings to match tutorial
  2d/dodge_the_creeps/project.godot
Labels: bug

#619 Additional 3D physics tests - RigidBody impact and ground check
  3d/physics_tests/tests.gd
  3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
  3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
  3d/physics_tests/utils/rigidbody_ground_check.gd
  3d/physics_tests/utils/rigidbody_pick.gd
Labels: enhancement, topic:physics

#622 Have waypoints check if the camera is current
  3d/physics_tests/utils/rigidbody_ground_check.gd
  3d/waypoints/waypoint.gd
Labels: enhancement
