Repository godotengine/godot-demo-projects, pull requests merged in 2021-02, with the labels that each got.

#575 [Joypads] Add SDL config re-mapping tool.
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
  misc/joypads/project.godot
  misc/joypads/remap/joy_mapping.gd
  misc/joypads/remap/remap_wizard.gd
  misc/joypads/remap/remap_wizard.tscn
Labels: enhancement

#580 Simplify the 3D scaling demo setup, enable filtering by default
  viewport/3d_scaling/README.md
  viewport/3d_scaling/hud.gd
  viewport/3d_scaling/hud.tscn
  viewport/3d_scaling/project.godot
Labels: enhancement

#581 Improve controls and camera handling in the Truck Town demo
  3d/truck_town/car_base.tscn
  3d/truck_town/car_select.gd
  3d/truck_town/car_select.tscn
  3d/truck_town/follow_camera.gd
  3d/truck_town/project.godot
  3d/truck_town/tow_truck.tscn
  3d/truck_town/trailer_truck.tscn
  3d/truck_town/vehicle.gd
Labels: enhancement

#583 Use a higher engine force when slow and add a spedometer in Truck Town
  3d/truck_town/car_base.tscn
  3d/truck_town/car_select.tscn
  3d/truck_town/project.godot
  3d/truck_town/spedometer.gd
  3d/truck_town/tow_truck.tscn
  3d/truck_town/town_scene.tscn
  3d/truck_town/trailer_truck.tscn
  3d/truck_town/vehicle.gd
Labels: enhancement

#584 Updated 2D character controller physics tests
  2d/physics_tests/main.tscn
  2d/physics_tests/tests.gd
  2d/physics_tests/tests/functional/test_character.gd
  2d/physics_tests/tests/functional/test_character_pixels.gd
  2d/physics_tests/tests/functional/test_character_pixels.tscn
  2d/physics_tests/tests/functional/test_character_slopes.tscn
  2d/physics_tests/tests/functional/test_character_tilemap.gd
  2d/physics_tests/tests/functional/test_character_tilemap.tscn
  2d/physics_tests/tests/functional/test_collision_pairs.gd
  2d/physics_tests/tests/functional/test_joints.gd
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/physics_tests/tests/functional/test_one_way_collision.tscn
  2d/physics_tests/tests/performance/test_perf_contacts.gd
  2d/physics_tests/utils/kinematicbody_controller.gd
  2d/physics_tests/utils/rigidbody_controller.gd
  2d/physics_tests/utils/scroll_log.gd
Labels: enhancement, topic:physics

#585 Added interpolation functionality to ik_look_at node
  3d/ik/addons/sade/ik_look_at.gd
Labels: enhancement

#582 Deploy exported HTML5 demos to GitHub Pages
  .github/dist/.nojekyll
  .github/dist/export_presets.cfg
  .github/dist/footer.html
  .github/dist/header.html
  .github/workflows/export_html5.yml
  .gitignore
Labels: enhancement

#587 Link to the web export in the README and format names nicer
  .github/dist/header.html
  .github/workflows/export_html5.yml
  README.md
Labels: enhancement, topic:buildsystem
