Repository godotengine/godot-demo-projects, pull requests merged in 2021-01, with the labels that each got.

#568 Update copyright statements for 2021
  LICENSE.md
Labels: update

#569 Add a control gallery demo
  gui/control_gallery/README.md
  gui/control_gallery/control_gallery.tscn
  gui/control_gallery/icon.png
  gui/control_gallery/icon.png.import
  gui/control_gallery/noto_sans_ui_regular.ttf
  gui/control_gallery/project.godot
  gui/control_gallery/screenshots/.gdignore
  gui/control_gallery/screenshots/control_gallery.png
Labels: new demo

#567 Add a 3D waypoints demo
  3d/waypoints/README.md
  3d/waypoints/camera.gd
  3d/waypoints/default_env.tres
  3d/waypoints/icon.png
  3d/waypoints/icon.png.import
  3d/waypoints/main.tscn
  3d/waypoints/noto_sans_regular.ttf
  3d/waypoints/project.godot
  3d/waypoints/screenshots/.gdignore
  3d/waypoints/screenshots/waypoints.png
  3d/waypoints/waypoint.gd
  3d/waypoints/waypoint.svg
  3d/waypoints/waypoint.svg.import
  3d/waypoints/waypoint.tscn
Labels: new demo

#570 Update the Drag and Drop demo and the Tween demo
  2d/tween/icon.png
  2d/tween/main.gd
  2d/tween/main.tscn
  2d/tween/noto_sans_ui_regular.ttf
  2d/tween/project.godot
  2d/tween/screenshots/tween.png
  3d/README.md
  3d/ik/fps/example_player.gd
  gui/drag_and_drop/drag_and_drop.tscn
  loading/multiple_threads_loading/resource_queue.gd
  misc/2.5d/assets/player/player_math_25d.gd
  misc/2.5d/assets/player/player_sprite.gd
  mobile/multitouch_cubes/GestureArea.gd
Labels: enhancement

#573 Add One Way Collision for 2D Physics tests
  2d/physics_tests/tests.gd
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/physics_tests/tests/functional/test_one_way_collision.tscn
  2d/physics_tests/utils/label_slider_value.gd
  2d/physics_tests/utils/option_menu.gd
  2d/physics_tests/utils/slider.gd
Labels: enhancement

#574 Support for pause in 2D/3D physics tests
  2d/physics_tests/main.tscn
  2d/physics_tests/project.godot
  2d/physics_tests/tests/functional/test_collision_pairs.tscn
  2d/physics_tests/tests/functional/test_one_way_collision.tscn
  2d/physics_tests/tests/functional/test_raycasting.tscn
  2d/physics_tests/tests/test_options.tscn
  2d/physics_tests/utils/label_pause.gd
  2d/physics_tests/utils/system.gd
  3d/physics_tests/main.tscn
  3d/physics_tests/project.godot
  3d/physics_tests/tests/functional/test_collision_pairs.tscn
  3d/physics_tests/tests/functional/test_raycasting.tscn
  3d/physics_tests/tests/test_options.tscn
  3d/physics_tests/utils/label_pause.gd
  3d/physics_tests/utils/system.gd
Labels: enhancement

#576 Update broadphase performance test in physics tests
  2d/physics_tests/project.godot
  2d/physics_tests/test.gd
  2d/physics_tests/tests/performance/test_perf_broadphase.gd
  2d/physics_tests/tests/performance/test_perf_broadphase.tscn
  3d/physics_tests/main.tscn
  3d/physics_tests/test.gd
  3d/physics_tests/tests/performance/test_perf_broadphase.gd
  3d/physics_tests/tests/performance/test_perf_broadphase.tscn
Labels: enhancement

#578 Changed key bindings in physics tests 2D/3D
  2d/physics_tests/main.tscn
  2d/physics_tests/project.godot
  3d/physics_tests/main.tscn
  3d/physics_tests/project.godot
Labels: enhancement

#577 Add physics tests for 2D character controller
  2d/physics_tests/assets/texture/godot-head.png
  2d/physics_tests/assets/texture/godot-head.png.import
  2d/physics_tests/assets/tileset/tiles_demo.png
  2d/physics_tests/assets/tileset/tiles_demo.png.import
  2d/physics_tests/assets/tileset/tileset.tres
  2d/physics_tests/project.godot
  2d/physics_tests/tests.gd
  2d/physics_tests/tests/functional/test_character.gd
  2d/physics_tests/tests/functional/test_character_slopes.tscn
  2d/physics_tests/tests/functional/test_character_tilemap.gd
  2d/physics_tests/tests/functional/test_character_tilemap.tscn
  2d/physics_tests/tests/functional/test_collision_pairs.tscn
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/physics_tests/tests/functional/test_raycasting.tscn
  2d/physics_tests/tests/functional/test_shapes.tscn
  2d/physics_tests/tests/performance/test_perf_contacts.tscn
  2d/physics_tests/tests/static_scene_flat.tscn
  2d/physics_tests/utils/kinematicbody_controller.gd
  2d/physics_tests/utils/rigidbody_controller.gd
Labels: enhancement
