Repository godotengine/godot-demo-projects, pull requests merged in 2021-08, with the labels that each got.

#640 Mono IAP signal method definition mismatch.
  mono/android_iap/Main.cs
Labels: bug, topic:mono

#642 Simplify and improve OpenSimplexNoise viewer
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.gd
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.tscn
Labels: bug, enhancement

#643 Google play billing method signature mismatch in demo with Godot's android billing plugin method
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/Main.cs
Labels: bug

#644 GitHub Actions: Update to Godot 3.3.3 for HTML5 deployment
  .github/workflows/export_html5.yml
Labels: enhancement

#645 Use `remotesync` instead of the deprecated `sync` in networking demos
  networking/multiplayer_bomber/player.gd
  networking/multiplayer_bomber/score.gd
  networking/multiplayer_pong/logic/ball.gd
  networking/multiplayer_pong/logic/pong.gd
  networking/websocket_multiplayer/script/game.gd
Labels: enhancement
