Repository godotengine/godot-demo-projects, pull requests merged in 2022-02, with the labels that each got.

#672 Remove GIProbe from 3D Kinematic Character demo to improve performance
  3d/kinematic_character/default_env.tres
  3d/kinematic_character/gi_probe_data.res
  3d/kinematic_character/level.tscn
Labels: enhancement

#656 Switch 2D Platformer and Multiplayer Bomber demos to GLES2
  2d/README.md
  2d/physics_platformer/README.md
  2d/physics_platformer/coin/Coin.tscn
  2d/physics_platformer/enemy/Enemy.tscn
  2d/physics_platformer/player/Bullet.tscn
  2d/physics_platformer/player/Player.tscn
  2d/physics_platformer/project.godot
  2d/platformer/README.md
  2d/platformer/project.godot
  2d/platformer/src/Actors/Enemy.tscn
  2d/platformer/src/Objects/Bullet.tscn
  networking/README.md
  networking/multiplayer_bomber/README.md
  networking/multiplayer_bomber/bomb.tscn
  networking/multiplayer_bomber/project.godot
Labels: enhancement

#680 Misc minor fixes
  .gitignore
  2d/platformer/assets/art/background/cloud_1.png.import
  2d/platformer/assets/art/background/cloud_2.png.import
  2d/platformer/assets/art/background/cloud_3.png.import
  2d/platformer/assets/art/background/distant_platforms_1.png.import
  2d/platformer/assets/art/background/distant_platforms_2.png.import
  2d/platformer/assets/art/background/sky.png.import
  2d/platformer/assets/art/coin/coin.png.import
  2d/platformer/assets/art/enemy/enemy.png.import
  2d/platformer/assets/art/platforms/moving_platform.png.import
  2d/platformer/assets/art/platforms/one_way_platform.png.import
  2d/platformer/assets/art/player/bullet/bullet.png.import
  2d/platformer/assets/art/player/robot_demo.png.import
  2d/platformer/assets/art/tileset/tiles_demo.png.import
  2d/platformer/assets/art/ui/touch_button_fire.png.import
  2d/platformer/assets/art/ui/touch_button_jump.png.import
  2d/platformer/assets/art/ui/touch_button_left.png.import
  2d/platformer/assets/art/ui/touch_button_right.png.import
  2d/platformer/icon.png.import
  2d/platformer/src/Actors/Player.gd
  2d/platformer/src/Main/Splitscreen.tscn
  2d/platformer/src/UserInterface/CoinsCounter.gd
  3d/global_illumination/icon.png
  3d/kinematic_character/level.tscn
Labels: bug

#674 Add a MIDI Piano Demo
  audio/midi_piano/README.md
  audio/midi_piano/icon.png
  audio/midi_piano/icon.png.import
  audio/midi_piano/piano.gd
  audio/midi_piano/piano.tscn
  audio/midi_piano/piano_keys/A440.wav
  audio/midi_piano/piano_keys/A440.wav.import
  audio/midi_piano/piano_keys/black_piano_key.tscn
  audio/midi_piano/piano_keys/piano_key.gd
  audio/midi_piano/piano_keys/piano_key_color.gd
  audio/midi_piano/piano_keys/white_piano_key.tscn
  audio/midi_piano/project.godot
  audio/midi_piano/screenshots/.gdignore
  audio/midi_piano/screenshots/piano-pressed.png
Labels: new demo, topic:audio

#681 Don't export global illumination demo to HTML5
  .github/dist/footer.html
  .github/workflows/export_html5.yml
Labels: bug

#683 Fix broken links for the your first 2D game tutorial
  2d/dodge_the_creeps/README.md
  2d/dodge_the_creeps/project.godot
  mono/dodge_the_creeps/README.md
  mono/dodge_the_creeps/project.godot
Labels: bug

#678 Added Alpha effect to joystick indicators
  misc/joypads/joypads.gd
Labels: enhancement
