Repository godotengine/godot-demo-projects, pull requests merged in 2022-03, with the labels that each got.

#687 Dodge the Creeps: Set the physics parameters of the mob before adding it to the scene tree
  2d/dodge_the_creeps/Main.gd
Labels: enhancement

#686 2d platformer gun cooldown fix
  2d/platformer/src/Actors/Gun.gd
Labels: bug

#684 Add axis label highlighting to the Joypads demo
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
Labels: enhancement

#675 Add a 3D Rigidbody character demo
  3d/rigidbody_character/README.md
  3d/rigidbody_character/cube_rigidbody.tscn
  3d/rigidbody_character/cubelib.tres
  3d/rigidbody_character/default_env.tres
  3d/rigidbody_character/gi_probe_data.res
  3d/rigidbody_character/icon.png
  3d/rigidbody_character/icon.png.import
  3d/rigidbody_character/level.gd
  3d/rigidbody_character/level.tscn
  3d/rigidbody_character/models/cube.glb
  3d/rigidbody_character/models/cube.glb.import
  3d/rigidbody_character/models/cube.mesh
  3d/rigidbody_character/models/cube_material.tres
  3d/rigidbody_character/models/mushroom.glb
  3d/rigidbody_character/models/mushroom.glb.import
  3d/rigidbody_character/models/white_cube_material.tres
  3d/rigidbody_character/models/white_wood.png
  3d/rigidbody_character/models/white_wood.png.import
  3d/rigidbody_character/player/cubio.gd
  3d/rigidbody_character/player/cubio.tscn
  3d/rigidbody_character/player/follow_camera.gd
  3d/rigidbody_character/project.godot
  3d/rigidbody_character/screenshots/.gdignore
  3d/rigidbody_character/screenshots/editor.png
  3d/rigidbody_character/screenshots/ingame.png
Labels: new demo

#689 Update README files after release 3.4-b0d4a7c
  .github/PULL_REQUEST_TEMPLATE.md
  3d/global_illumination/README.md
  3d/rigidbody_character/README.md
  README.md
  audio/midi_piano/README.md
Labels: update

#637 Add pseudolocalization demo
  gui/pseudolocalization/Pseudolocalization.gd
  gui/pseudolocalization/Pseudolocalization.tscn
  gui/pseudolocalization/README.md
  gui/pseudolocalization/default_env.tres
  gui/pseudolocalization/icon.png
  gui/pseudolocalization/icon.png.import
  gui/pseudolocalization/project.godot
  gui/pseudolocalization/screenshots/.gdignore
  gui/pseudolocalization/screenshots/pseudolocalization.png
Labels: new demo

#670 feat: update websocket-minimal to gdscript2.0
  networking/websocket_minimal/Main.tscn
  networking/websocket_minimal/client.gd
  networking/websocket_minimal/project.godot
  networking/websocket_minimal/server.gd
Labels: update

#658 Add a volumetric fog demo
  3d/volumetric_fog/README.md
  3d/volumetric_fog/camera.gd
  3d/volumetric_fog/icon_outlined.png
  3d/volumetric_fog/icon_outlined.png.import
  3d/volumetric_fog/project.godot
  3d/volumetric_fog/screenshots/.gdignore
  3d/volumetric_fog/screenshots/volumetric_fog.png
  3d/volumetric_fog/volumetric_fog.tscn
Labels: new demo

#692 Update Viewport demos to Godot 4
  viewport/2d_in_3d/2D_in_3D.gd
  viewport/2d_in_3d/2D_in_3D.tscn
  viewport/2d_in_3d/ball.png.import
  viewport/2d_in_3d/icon.png.import
  viewport/2d_in_3d/left_pallete.png.import
  viewport/2d_in_3d/project.godot
  viewport/2d_in_3d/right_pallete.png.import
  viewport/2d_in_3d/separator.png.import
  viewport/3d_in_2d/3d_in_2d.tscn
  viewport/3d_in_2d/icon.png.import
  viewport/3d_in_2d/project.godot
  viewport/3d_in_2d/robot_3d.tscn
  viewport/3d_in_2d/robot_demo.png.import
  viewport/3d_scaling/cubes.tscn
  viewport/3d_scaling/hud.gd
  viewport/3d_scaling/hud.tscn
  viewport/3d_scaling/icon.png.import
  viewport/3d_scaling/noto_sans_ui_regular.ttf.import
  viewport/3d_scaling/project.godot
  viewport/dynamic_split_screen/camera_controller.gd
  viewport/dynamic_split_screen/default_env.tres
  viewport/dynamic_split_screen/icon.png.import
  viewport/dynamic_split_screen/player.gd
  viewport/dynamic_split_screen/project.godot
  viewport/dynamic_split_screen/split_screen.tscn
  viewport/gui_in_3d/gui_3d.gd
  viewport/gui_in_3d/gui_in_3d.tscn
  viewport/gui_in_3d/gui_panel_3d.tscn
  viewport/gui_in_3d/icon.png.import
  viewport/gui_in_3d/project.godot
  viewport/screen_capture/icon.png.import
  viewport/screen_capture/mountains.png.import
  viewport/screen_capture/project.godot
  viewport/screen_capture/screen_capture.gd
  viewport/screen_capture/screen_capture.tscn
Labels: update

#693 Update Audio demos to Godot 4
  audio/bpm_sync/bpm_sync.gd
  audio/bpm_sync/bpm_sync.tscn
  audio/bpm_sync/icon.png.import
  audio/bpm_sync/lcd.ttf.import
  audio/bpm_sync/play_sound_button.png.import
  audio/bpm_sync/play_sound_button_hl.png.import
  audio/bpm_sync/play_system_button.png.import
  audio/bpm_sync/play_system_button_hl.png.import
  audio/bpm_sync/project.godot
  audio/bpm_sync/the_comeback2.ogg.import
  audio/device_changer/Changer.tscn
  audio/device_changer/Intro.ogg.import
  audio/device_changer/icon.png.import
  audio/device_changer/project.godot
  audio/generator/generator.tscn
  audio/generator/project.godot
  audio/mic_record/Intro.ogg.import
  audio/mic_record/MicRecord.tscn
  audio/mic_record/default_bus_layout.tres
  audio/mic_record/icon.png.import
  audio/mic_record/project.godot
  audio/midi_piano/icon.png.import
  audio/midi_piano/piano.tscn
  audio/midi_piano/piano_keys/A440.wav.import
  audio/midi_piano/project.godot
  audio/spectrum/default_bus_layout.tres
  audio/spectrum/icon.png.import
  audio/spectrum/maldita.ogg.import
  audio/spectrum/project.godot
  audio/spectrum/show_spectrum.gd
  audio/spectrum/show_spectrum.tscn
Labels: update

#694 Update Voxel demo to Godot 4
  3d/voxel/default_bus_layout.tres
  3d/voxel/default_env.tres
  3d/voxel/icon.png.import
  3d/voxel/menu/button.png.import
  3d/voxel/menu/ingame/pause_menu.tscn
  3d/voxel/menu/main/dark_dirt.png.import
  3d/voxel/menu/main/main_menu.tscn
  3d/voxel/menu/main/splash_text.gd
  3d/voxel/menu/main/title.png.import
  3d/voxel/menu/options/option_buttons.gd
  3d/voxel/menu/options/options.tscn
  3d/voxel/menu/theme/TinyUnicode.tres
  3d/voxel/menu/theme/TinyUnicode.ttf.import
  3d/voxel/player/crosshair.svg.import
  3d/voxel/player/player.gd
  3d/voxel/player/player.tscn
  3d/voxel/project.godot
  3d/voxel/settings.gd
  3d/voxel/world/chunk.gd
  3d/voxel/world/environment.gd
  3d/voxel/world/terrain_generator.gd
  3d/voxel/world/textures/material.tres
  3d/voxel/world/textures/texture_sheet.png.import
  3d/voxel/world/voxel_world.gd
  3d/voxel/world/world.tscn
Labels: update
