Repository godotengine/godot-demo-projects, pull requests merged in 2022-04, with the labels that each got.

#705 Fixes layout, nodes and theming for Control Gallery Demo - 4.0 dev
  gui/control_gallery/README.md
  gui/control_gallery/control_gallery.tscn
  gui/control_gallery/icon.png.import
  gui/control_gallery/noto_sans_ui_regular.ttf.import
  gui/control_gallery/project.godot
  gui/control_gallery/screenshots/control_gallery.png
Labels: update

#707 Tested and Fixed Pong with GDScript Demo for 4.0-dev
  2d/pong/README.md
  2d/pong/ball.png.import
  2d/pong/icon.png.import
  2d/pong/paddle.png.import
  2d/pong/pong.tscn
  2d/pong/project.godot
  2d/pong/separator.png.import
Labels: update

#701 Fixing Pause Demo - Object not rotating + 4.0 changes
  misc/pause/README.md
  misc/pause/icon.png.import
  misc/pause/pause_button.gd
  misc/pause/project.godot
  misc/pause/spinpause.tscn
Labels: bug, update

#702 Prepared Autoload(Singletons) demo for Godot 4
  loading/autoload/README.md
  loading/autoload/project.godot
  loading/autoload/scene_a.tscn
  loading/autoload/scene_b.tscn
Labels: update

#704 Fixed Translation Demo not working in 4.0-dev
  gui/translation/README.md
  gui/translation/flag_japan.png.import
  gui/translation/flag_spain.png.import
  gui/translation/flag_uk.png.import
  gui/translation/font/DroidSans.ttf.import
  gui/translation/font/DroidSansArabic.ttf.import
  gui/translation/font/DroidSansFallback.ttf.import
  gui/translation/font/DroidSansHebrew.ttf.import
  gui/translation/font/DroidSansJapanese.ttf.import
  gui/translation/font/DroidSansThai.ttf.import
  gui/translation/hello_en.wav.import
  gui/translation/hello_es.wav.import
  gui/translation/hello_jp.wav.import
  gui/translation/icon.png.import
  gui/translation/project.godot
  gui/translation/speaker.png.import
  gui/translation/text.csv
  gui/translation/text.csv.import
  gui/translation/translation_demo.tscn
Labels: update

#711 Adding settings for mix_rate, stereo and format for Mic Record Demo 4.0-dev
  audio/mic_record/MicRecord.gd
  audio/mic_record/MicRecord.tscn
  audio/mic_record/README.md
  audio/mic_record/project.godot
  audio/mic_record/screenshots/mic_record.png
Labels: enhancement

#706 Tested and fixed Scene Instancing Demo for 4.0-dev
  2d/instancing/README.md
  2d/instancing/bowling_ball.png.import
  2d/instancing/icon.png.import
  2d/instancing/project.godot
  2d/instancing/scene_instancing.tscn
Labels: update

#708 Fixed Script Errors for GUI Input Mapping Demo - 4.0-dev
  gui/input_mapping/ActionRemapButton.gd
  gui/input_mapping/InputRemapMenu.tscn
  gui/input_mapping/README.md
  gui/input_mapping/icon.png.import
  gui/input_mapping/project.godot
Labels: update

#712 Update for Bullet Shower to 4.0-dev
  2d/bullet_shower/README.md
  2d/bullet_shower/bullet.png.import
  2d/bullet_shower/bullets.gd
  2d/bullet_shower/face_happy.png.import
  2d/bullet_shower/face_sad.png.import
  2d/bullet_shower/icon.png.import
  2d/bullet_shower/player.gd
  2d/bullet_shower/project.godot
  2d/bullet_shower/shower.tscn
Labels: update

#714 GUI in 3D: Always process GUI even when the scene tree is paused
  viewport/gui_in_3d/gui_panel_3d.tscn
Labels: bug

#715 Pause demo: Showcase new pause features in Godot 4.0
  misc/pause/process_mode.gd
  misc/pause/project.godot
  misc/pause/spinpause.tscn
Labels: enhancement

#716 Added run-time translation example for Translation Demo 4.0-dev
  gui/translation/text.csv
  gui/translation/translation_demo.gd
  gui/translation/translation_demo.tscn
Labels: enhancement

#717 Port Multiplayer bomber to replication system.
  networking/multiplayer_bomber/bomb.gd
  networking/multiplayer_bomber/bomb.tscn
  networking/multiplayer_bomber/bomb_spawner.gd
  networking/multiplayer_bomber/brickfloor.png.import
  networking/multiplayer_bomber/charwalk.png.import
  networking/multiplayer_bomber/explosion.png.import
  networking/multiplayer_bomber/gamestate.gd
  networking/multiplayer_bomber/icon.png.import
  networking/multiplayer_bomber/lobby.gd
  networking/multiplayer_bomber/lobby.tscn
  networking/multiplayer_bomber/montserrat.otf.import
  networking/multiplayer_bomber/player.gd
  networking/multiplayer_bomber/player.tscn
  networking/multiplayer_bomber/player_controls.gd
  networking/multiplayer_bomber/project.godot
  networking/multiplayer_bomber/rock.gd
  networking/multiplayer_bomber/rock.tscn
  networking/multiplayer_bomber/rock_bit.png.import
  networking/multiplayer_bomber/score.gd
  networking/multiplayer_bomber/tile_scene.tscn
  networking/multiplayer_bomber/tileset.tres
  networking/multiplayer_bomber/world.tscn
Labels: update, topic:network

#713 Add a 3D settings demo (Graphical settings) for 4.0-dev
  3d/graphics_settings/3d_scene.tscn
  3d/graphics_settings/README.md
  3d/graphics_settings/control.tscn
  3d/graphics_settings/icon.png
  3d/graphics_settings/icon.png.import
  3d/graphics_settings/project.godot
  3d/graphics_settings/screenshots/interface.png
  3d/graphics_settings/screenshots/interface.png.import
  3d/graphics_settings/settings.gd
Labels: new demo

#723 Tweak Multiplayer Pong demo icons to be different from singleplayer
  mono/multiplayer_pong/icon.png
  networking/multiplayer_pong/icon.png
Labels: enhancement

#724 New Icons for some of the 4.0-dev demos
  2d/physics_tests/icon.png
  3d/graphics_settings/icon.png
  3d/physics_tests/icon.png
  audio/device_changer/icon.png
  audio/mic_record/icon.png
  gui/control_gallery/icon.png
  gui/pseudolocalization/icon.png
Labels: enhancement

#721 Add a demo on supporting multiple resolutions and aspect ratios
  gui/multiple_resolutions/README.md
  gui/multiple_resolutions/icon.png
  gui/multiple_resolutions/icon.png.import
  gui/multiple_resolutions/main.gd
  gui/multiple_resolutions/main.tscn
  gui/multiple_resolutions/noto_sans_ui_regular.tres
  gui/multiple_resolutions/noto_sans_ui_regular.ttf
  gui/multiple_resolutions/project.godot
  gui/multiple_resolutions/screenshots/.gdignore
  gui/multiple_resolutions/screenshots/multiple_resolutions.png
Labels: new demo

#726 Update Dodge the Creeps to 4.0
  2d/dodge_the_creeps/HUD.tscn
  2d/dodge_the_creeps/Main.tscn
  2d/dodge_the_creeps/Mob.tscn
  2d/dodge_the_creeps/Player.tscn
  2d/dodge_the_creeps/art/House In a Forest Loop.ogg.import
  2d/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
  2d/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
  2d/dodge_the_creeps/art/enemySwimming_1.png.import
  2d/dodge_the_creeps/art/enemySwimming_2.png.import
  2d/dodge_the_creeps/art/enemyWalking_1.png.import
  2d/dodge_the_creeps/art/enemyWalking_2.png.import
  2d/dodge_the_creeps/art/gameover.wav.import
  2d/dodge_the_creeps/art/playerGrey_up1.png.import
  2d/dodge_the_creeps/art/playerGrey_up2.png.import
  2d/dodge_the_creeps/art/playerGrey_walk1.png.import
  2d/dodge_the_creeps/art/playerGrey_walk2.png.import
  2d/dodge_the_creeps/fonts/Xolonium-Regular.tres
  2d/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
  2d/dodge_the_creeps/icon.png.import
  2d/dodge_the_creeps/project.godot
Labels: update

#727 Updated Kinematic Character 2D Demo to Godot 4
  2d/kinematic_character/icon.png.import
  2d/kinematic_character/level/circle.png.import
  2d/kinematic_character/level/long_obstacle.png.import
  2d/kinematic_character/level/obstacle.png.import
  2d/kinematic_character/level/princess.png.import
  2d/kinematic_character/player/player.gd
  2d/kinematic_character/player/player.png.import
  2d/kinematic_character/project.godot
  2d/kinematic_character/world.tscn
Labels: update

#728 Revert accidental change in camera script in Global illumination demo
  3d/global_illumination/camera.gd
  3d/global_illumination/test.tscn
Labels: enhancement

#719 Improve the 3D graphics settings demo
  3d/graphics_settings/3d_scene.tscn
  3d/graphics_settings/README.md
  3d/graphics_settings/control.tscn
  3d/graphics_settings/project.godot
  3d/graphics_settings/screenshots/.gdignore
  3d/graphics_settings/screenshots/interface.png
  3d/graphics_settings/screenshots/interface.png.import
  3d/graphics_settings/settings.gd
Labels: enhancement
