Repository godotengine/godot-demo-projects, pull requests merged in 2022-05, with the labels that each got.

#729 Including *.json files to fix #725
  .github/dist/export_presets.cfg
Labels: bug

#730 Merge recent changes from master into the 4.0-dev branch
  .github/dist/export_presets.cfg
  gui/multiple_resolutions/README.md
  gui/multiple_resolutions/icon.png
  gui/multiple_resolutions/icon.png.import
  gui/multiple_resolutions/main.gd
  gui/multiple_resolutions/main.tscn
  gui/multiple_resolutions/noto_sans_ui_regular.tres
  gui/multiple_resolutions/noto_sans_ui_regular.ttf
  gui/multiple_resolutions/project.godot
  gui/multiple_resolutions/screenshots/.gdignore
  gui/multiple_resolutions/screenshots/multiple_resolutions.png
  mono/multiplayer_pong/icon.png
  networking/multiplayer_pong/icon.png
Labels: enhancement

#734 GD Paint Demo Update to 4.0
  2d/gd_paint/README.md
  2d/gd_paint/icon.png.import
  2d/gd_paint/paint_control.gd
  2d/gd_paint/paint_root.tscn
  2d/gd_paint/paint_tools.png.import
  2d/gd_paint/project.godot
  2d/gd_paint/tools_panel.gd
Labels: update

#735 Screen Space Shader Update to 4.0
  2d/screen_space_shaders/README.md
  2d/screen_space_shaders/art/burano.jpg.import
  2d/screen_space_shaders/art/filmgrain.png.import
  2d/screen_space_shaders/art/forest.jpg.import
  2d/screen_space_shaders/art/mountains.jpg.import
  2d/screen_space_shaders/art/platformer.jpg.import
  2d/screen_space_shaders/art/vignette.png.import
  2d/screen_space_shaders/art/white.png.import
  2d/screen_space_shaders/icon.png.import
  2d/screen_space_shaders/project.godot
  2d/screen_space_shaders/screen_shaders.tscn
Labels: update

#732 Making Demo Dodge the Creeps ready for 4.0-dev
  2d/dodge_the_creeps/README.md
  2d/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
  2d/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
  2d/dodge_the_creeps/art/enemySwimming_1.png.import
  2d/dodge_the_creeps/art/enemySwimming_2.png.import
  2d/dodge_the_creeps/art/enemyWalking_1.png.import
  2d/dodge_the_creeps/art/enemyWalking_2.png.import
  2d/dodge_the_creeps/art/playerGrey_up1.png.import
  2d/dodge_the_creeps/art/playerGrey_up2.png.import
  2d/dodge_the_creeps/art/playerGrey_walk1.png.import
  2d/dodge_the_creeps/art/playerGrey_walk2.png.import
  2d/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
  2d/dodge_the_creeps/icon.png.import
  2d/dodge_the_creeps/project.godot
Labels: update

#736 Fixed some issues in Pseudo localization Demo 4.0-dev
  gui/pseudolocalization/Pseudolocalization.gd
  gui/pseudolocalization/Pseudolocalization.tscn
  gui/pseudolocalization/README.md
  gui/pseudolocalization/icon.png.import
  gui/pseudolocalization/project.godot
Labels: bug

#737 Window Management Update 4.0
  misc/window_management/README.md
  misc/window_management/control.gd
  misc/window_management/icon.png.import
  misc/window_management/project.godot
  misc/window_management/window_management.tscn
Labels: update

#738 [4.0-dev] GUI Input Mapping Demo Persistent Key Mapping- Fixes #629
  gui/input_mapping/ActionRemapButton.gd
  gui/input_mapping/ActionRemapButton.tscn
  gui/input_mapping/InputRemapMenu.tscn
  gui/input_mapping/KeyPersistence.gd
  gui/input_mapping/project.godot
Labels: enhancement

#739 [3.x] GUI Input Mapping Demo Persistent Key Mapping- Fixes #629
  gui/input_mapping/ActionRemapButton.gd
  gui/input_mapping/KeyPersistence.gd
  gui/input_mapping/project.godot
Labels: enhancement

#733 Update Multiple Resolutions demo for Godot 4.0
  gui/multiple_resolutions/README.md
  gui/multiple_resolutions/icon.png.import
  gui/multiple_resolutions/main.gd
  gui/multiple_resolutions/main.tscn
  gui/multiple_resolutions/noto_sans_ui_regular.tres
  gui/multiple_resolutions/noto_sans_ui_regular.ttf
  gui/multiple_resolutions/project.godot
  gui/multiple_resolutions/screenshots/multiple_resolutions.png
Labels: update

#741 Fixing GD Paint Issues in 4.0-dev
  2d/gd_paint/paint_root.tscn
  2d/gd_paint/project.godot
Labels: bug

#740 Fix window management demo for 4.0
  misc/window_management/control.gd
  misc/window_management/project.godot
  misc/window_management/window_management.tscn
Labels: bug

#742 Convert some 2D nodes to Control nodes in GDPaint and Pseudolocalization demos
  gui/gd_paint/README.md
  gui/gd_paint/icon.png
  gui/gd_paint/icon.png.import
  gui/gd_paint/paint_control.gd
  gui/gd_paint/paint_root.tscn
  gui/gd_paint/paint_tools.png
  gui/gd_paint/paint_tools.png.import
  gui/gd_paint/project.godot
  gui/gd_paint/screenshots/.gdignore
  gui/gd_paint/screenshots/gdpaint.png
  gui/gd_paint/tools_panel.gd
  gui/pseudolocalization/Pseudolocalization.gd
  gui/pseudolocalization/Pseudolocalization.tscn
Labels: enhancement
