Repository godotengine/godot-demo-projects, pull requests merged in 2022-07, with the labels that each got.

#754 Docs: 2D Platformer - Update Pause Mode Comments
  2d/platformer/src/Main/Game.gd
Labels: bug

#747 Update loading in a thread demo for 4.0
  loading/threads/README.md
  loading/threads/mona.png.import
  loading/threads/project.godot
  loading/threads/thread.gd
  loading/threads/thread.tscn
Labels: update

#720 Improve visual appearance in the 2D Sprite Shaders demo
  2d/sprite_shaders/godotea.png.import
  2d/sprite_shaders/screenshots/sprite.png
  2d/sprite_shaders/sprite_shaders.tscn
Labels: enhancement

#743 Add a 3D antialiasing demo
  3d/antialiasing/README.md
  3d/antialiasing/anti_aliasing.gd
  3d/antialiasing/anti_aliasing.tscn
  3d/antialiasing/default_env.tres
  3d/antialiasing/icon.png
  3d/antialiasing/icon.png.import
  3d/antialiasing/polyhaven/dutch_ship_medium.bin
  3d/antialiasing/polyhaven/dutch_ship_medium_1k.gltf
  3d/antialiasing/polyhaven/dutch_ship_medium_1k.gltf.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_arm_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_diff_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_nor_gl_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_nor_gl_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_arm_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_diff_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_nor_gl_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_nor_gl_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_arm_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_diff_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_nor_gl_1k.jpg
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_nor_gl_1k.jpg.import
  3d/antialiasing/project.godot
  3d/antialiasing/screenshots/.gdignore
  3d/antialiasing/screenshots/3d_anti_aliasing.png
  3d/antialiasing/textures/checker.LICENSE.md
  3d/antialiasing/textures/checker.png
  3d/antialiasing/textures/checker.png.import
  3d/antialiasing/textures/paint.LICENSE.md
  3d/antialiasing/textures/paint.png
  3d/antialiasing/textures/paint.png.import
  3d/antialiasing/textures/paint_normal.png
  3d/antialiasing/textures/paint_normal.png.import
  3d/antialiasing/thin_lines.tscn
Labels: new demo
