Repository godotengine/godot-demo-projects, pull requests merged in 2022-12, with the labels that each got.

#792 Update multiplayer pong to godot 4 beta 5
  networking/multiplayer_pong/ball.png.import
  networking/multiplayer_pong/ball.tscn
  networking/multiplayer_pong/icon.png.import
  networking/multiplayer_pong/lobby.tscn
  networking/multiplayer_pong/logic/ball.gd
  networking/multiplayer_pong/logic/lobby.gd
  networking/multiplayer_pong/logic/paddle.gd
  networking/multiplayer_pong/logic/pong.gd
  networking/multiplayer_pong/paddle.png.import
  networking/multiplayer_pong/paddle.tscn
  networking/multiplayer_pong/pong.tscn
  networking/multiplayer_pong/project.godot
  networking/multiplayer_pong/separator.png.import
Labels: update

#802 Change to correct RPC syntax in Multiplayer bomber demo
  networking/multiplayer_bomber/bomb.gd
  networking/multiplayer_bomber/gamestate.gd
Labels: bug

#804 Update 4.0 status to beta in the README
  README.md
Labels: bug

#803 New Tween demo
  2d/tween/README.md
  2d/tween/godot.png.import
  2d/tween/icon.png.import
  2d/tween/main.gd
  2d/tween/main.tscn
  2d/tween/noto_sans_ui_regular.ttf
  2d/tween/project.godot
  2d/tween/screenshots/tween.png
Labels: update, new demo

#801 Add an occlusion culling and mesh LOD demo
  3d/occlusion_culling_mesh_lod/README.md
  3d/occlusion_culling_mesh_lod/camera.gd
  3d/occlusion_culling_mesh_lod/icon.png
  3d/occlusion_culling_mesh_lod/icon.png.import
  3d/occlusion_culling_mesh_lod/node_3d.gd
  3d/occlusion_culling_mesh_lod/node_3d.occ
  3d/occlusion_culling_mesh_lod/node_3d.tscn
  3d/occlusion_culling_mesh_lod/project.godot
  3d/occlusion_culling_mesh_lod/room.blend
  3d/occlusion_culling_mesh_lod/room.blend.import
  3d/occlusion_culling_mesh_lod/room.glb
  3d/occlusion_culling_mesh_lod/room.glb.import
  3d/occlusion_culling_mesh_lod/screenshots/.gdignore
  3d/occlusion_culling_mesh_lod/screenshots/occlusion_culling_mesh_lod.webp
Labels: new demo
