Repository godotengine/godot-demo-projects, pull requests merged in 2023-03, with the labels that each got.

#865 Update 2D physics platformer for 4.0
  2d/physics_platformer/README.md
  2d/physics_platformer/Stage.tscn
  2d/physics_platformer/Tileset.tres
  2d/physics_platformer/background/Seesaw.tscn
  2d/physics_platformer/background/parallax_bg.tscn
  2d/physics_platformer/background/plank.png.import
  2d/physics_platformer/background/plankpin.png.import
  2d/physics_platformer/background/scroll_bg_cloud_1.png.import
  2d/physics_platformer/background/scroll_bg_cloud_2.png.import
  2d/physics_platformer/background/scroll_bg_cloud_3.png.import
  2d/physics_platformer/background/scroll_bg_fg_1.png.import
  2d/physics_platformer/background/scroll_bg_fg_2.png.import
  2d/physics_platformer/background/scroll_bg_sky.png.import
  2d/physics_platformer/background/seesaw.tscn
  2d/physics_platformer/coin/coin.png.import
  2d/physics_platformer/coin/coin.tscn
  2d/physics_platformer/enemy/enemy.gd
  2d/physics_platformer/enemy/enemy.png.import
  2d/physics_platformer/enemy/enemy.tscn
  2d/physics_platformer/icon.png
  2d/physics_platformer/icon.webp
  2d/physics_platformer/icon.webp.import
  2d/physics_platformer/platform/MovingPlatform.tscn
  2d/physics_platformer/platform/OneWayPlatform.tscn
  2d/physics_platformer/platform/moving_platform.gd
  2d/physics_platformer/platform/moving_platform.png.import
  2d/physics_platformer/platform/moving_platform.tscn
  2d/physics_platformer/platform/one_way_platform.png.import
  2d/physics_platformer/platform/one_way_platform.tscn
  2d/physics_platformer/player/bullet.png.import
  2d/physics_platformer/player/bullet.tscn
  2d/physics_platformer/player/osb_fire.png.import
  2d/physics_platformer/player/osb_jump.png.import
  2d/physics_platformer/player/osb_left.png.import
  2d/physics_platformer/player/osb_right.png.import
  2d/physics_platformer/player/player.gd
  2d/physics_platformer/player/player.tscn
  2d/physics_platformer/player/player.webp
  2d/physics_platformer/player/player.webp.import
  2d/physics_platformer/player/robot_demo.png
  2d/physics_platformer/project.godot
  2d/physics_platformer/stage.tscn
  2d/physics_platformer/tiles_demo.png.import
  2d/physics_platformer/tileset.tres
  2d/physics_platformer/tileset_edit.tscn
Labels: update

#866 Update "Dodge the Creeps" demo
  2d/dodge_the_creeps/HUD.gd
  2d/dodge_the_creeps/Main.gd
  2d/dodge_the_creeps/Mob.gd
  2d/dodge_the_creeps/Player.gd
  2d/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
  2d/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
  2d/dodge_the_creeps/art/enemySwimming_1.png.import
  2d/dodge_the_creeps/art/enemySwimming_2.png.import
  2d/dodge_the_creeps/art/enemyWalking_1.png.import
  2d/dodge_the_creeps/art/enemyWalking_2.png.import
  2d/dodge_the_creeps/art/playerGrey_up1.png.import
  2d/dodge_the_creeps/art/playerGrey_up2.png.import
  2d/dodge_the_creeps/art/playerGrey_walk1.png.import
  2d/dodge_the_creeps/art/playerGrey_walk2.png.import
  2d/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
  2d/dodge_the_creeps/icon.png.import
  2d/dodge_the_creeps/project.godot
Labels: update

#874 Fix GDScript code style regarding colon (demos)
  2d/physics_tests/tests.gd
  2d/physics_tests/tests/functional/test_character.gd
  2d/physics_tests/tests/functional/test_character_tilemap.gd
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/physics_tests/tests_menu.gd
  2d/role_playing_game/dialogue/dialogue_data/npc.json
  2d/role_playing_game/dialogue/dialogue_data/object.json
  2d/role_playing_game/dialogue/dialogue_data/player_lose.json
  2d/role_playing_game/dialogue/dialogue_data/player_won.json
  3d/antialiasing/anti_aliasing.tscn
  3d/material_testers/tester.gd
  3d/physics_tests/tests.gd
  3d/physics_tests/tests/functional/test_moving_platform.gd
  3d/physics_tests/tests_menu.gd
  networking/multiplayer_bomber/player_controls.gd
  networking/websocket_chat/client.gd
  networking/websocket_chat/server.gd
  networking/websocket_chat/websocket/WebSocketClient.gd
  networking/websocket_chat/websocket/WebSocketServer.gd
  plugins/addons/material_import_plugin/import.gd
Labels: enhancement

#877 loading/serialization demo fixed to work with Godot 4 stable
  loading/serialization/save_load_json.gd
Labels: bug

#876 disconnect unused signal connected to a removed method
  gui/rich_text_bbcode/rich_text_bbcode.tscn
Labels: bug

#878 fix getter/setter usage of AudioServer object
  audio/device_changer/Changer.gd
Labels: bug, topic:audio

#875 GUI/InputRemapMenu demo fixed to work with Godot 4 stable
  gui/input_mapping/KeyPersistence.gd
Labels: bug

#880 audio/text_to_speech demo fixed to work with Godot 4 stable
  audio/text_to_speech/voice_list.gd
Labels: enhancement

#882 Change Icon header ordering for 2.5d GD Script Demo
  misc/2.5d/addons/node25d/node_25d.gd
  misc/2.5d/addons/node25d/shadow_math_25d.gd
  misc/2.5d/addons/node25d/y_sort_25d.gd
Labels: bug

#899 Add editor-only roughness and metallic testers to Material Testers
  3d/material_testers/hide_on_startup.gd
  3d/material_testers/material_tester.tscn
  3d/material_testers/models/test_bed/test_bed_2.tscn
  3d/material_testers/test_materials/aluminium_albedo.png.import
  3d/material_testers/test_materials/aluminium_flow.png.import
  3d/material_testers/test_materials/aluminium_normal.png.import
  3d/material_testers/test_materials/marble_albedo.png.import
  3d/material_testers/test_materials/rock_albedo.jpg.import
  3d/material_testers/test_materials/rock_ao.jpg.import
  3d/material_testers/test_materials/rock_depth.jpg.import
  3d/material_testers/test_materials/rock_metal.jpg.import
  3d/material_testers/test_materials/rock_rough.jpg.import
  3d/material_testers/test_materials/sand_albedo.jpg.import
  3d/material_testers/test_materials/sand_metal.jpg.import
  3d/material_testers/test_materials/sand_normal.jpg.import
  3d/material_testers/test_materials/sand_rough.jpg.import
  3d/material_testers/test_materials/sand_shine.jpg.import
  3d/material_testers/test_materials/texture_bricks.jpg.import
  3d/material_testers/test_materials/texture_bricks_ao.jpg.import
  3d/material_testers/test_materials/texture_bricks_depth.jpg.import
  3d/material_testers/test_materials/texture_bricks_metal.jpg.import
  3d/material_testers/test_materials/texture_bricks_normal.jpg.import
  3d/material_testers/test_materials/texture_cheese_albedo.png.import
  3d/material_testers/test_materials/texture_cheese_ao.png.import
  3d/material_testers/test_materials/texture_cheese_depth.png.import
  3d/material_testers/test_materials/texture_cheese_normal.png.import
  3d/material_testers/test_materials/texture_rock_albedo.png.import
  3d/material_testers/test_materials/texture_rock_ao.png.import
  3d/material_testers/test_materials/texture_rock_depth.png.import
  3d/material_testers/test_materials/texture_rock_metal.png.import
  3d/material_testers/test_materials/texture_rock_normal.png.import
  3d/material_testers/test_materials/texture_wood.png.import
  3d/material_testers/test_materials/wool_albedo.png.import
  3d/material_testers/test_materials/wool_depth.png.import
  3d/material_testers/test_materials/wool_normal.png.import
Labels: enhancement

#892 Add an optional extra RESET step in Tween demo
  2d/tween/main.gd
  2d/tween/main.tscn
Labels: enhancement

#852 Add a variable rate shading demo
  3d/variable_rate_shading/README.md
  3d/variable_rate_shading/icon.webp
  3d/variable_rate_shading/icon.webp.import
  3d/variable_rate_shading/information.gd
  3d/variable_rate_shading/project.godot
  3d/variable_rate_shading/screenshots/.gdignore
  3d/variable_rate_shading/screenshots/variable_rate_shading.webp
  3d/variable_rate_shading/vrs.gd
  3d/variable_rate_shading/vrs.tscn
  3d/variable_rate_shading/vrs_texture.gdshader
  3d/variable_rate_shading/vrs_texture.png
  3d/variable_rate_shading/vrs_texture.png.import
  3d/variable_rate_shading/vrs_texture_original.png
  3d/variable_rate_shading/vrs_texture_original.png.import
Labels: new demo
