Repository godotengine/godot-demo-projects, pull requests merged in 2023-02, with the labels that each got.

#835 Improve and update Control Gallery for Godot 4.0
  gui/control_gallery/README.md
  gui/control_gallery/control_gallery.tscn
  gui/control_gallery/icon.png.import
  gui/control_gallery/noto_sans_ui_regular.ttf
  gui/control_gallery/noto_sans_ui_regular.ttf.import
  gui/control_gallery/project.godot
  gui/control_gallery/screenshots/control_gallery.png
  gui/control_gallery/screenshots/control_gallery.webp
  gui/control_gallery/tree.gd
Labels: enhancement

#838 Add quotes to rpc flags
  networking/multiplayer_bomber/gamestate.gd
  networking/multiplayer_bomber/player.gd
  networking/multiplayer_bomber/rock.gd
  networking/multiplayer_pong/logic/ball.gd
  networking/multiplayer_pong/logic/paddle.gd
  networking/multiplayer_pong/logic/pong.gd
  networking/webrtc_signaling/demo/client_ui.gd
  networking/websocket_multiplayer/script/game.gd
Labels: update

#839 Update Global Illumination demo for 4.0.rc1
  3d/global_illumination/project.godot
  3d/global_illumination/test.tscn
  3d/global_illumination/zdm2_all.exr.import
  3d/global_illumination/zdm2_indirect.exr.import
Labels: update

#842 Change warning ignores to use a string identifier
  3d/voxel/settings.gd
  audio/bpm_sync/bpm_sync.gd
  audio/spectrum/show_spectrum.gd
Labels: bug

#847 Update Operating System Testing demo for 4.0.rc2
  misc/os_test/icon.png.import
  misc/os_test/os_test.gd
  misc/os_test/os_test.tscn
Labels: update

#791 opensimplexnoise: Fix persistence, tweak documentation URL and layout
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.gd
  misc/opensimplexnoise/OpenSimplexNoise_Viewer.tscn
Labels: bug

#848 misc/window_management: Fix screen size and label order
  misc/window_management/control.gd
  misc/window_management/window_management.tscn
Labels: bug

#763 Update Bidi and Font Features demo for 4.0.rc4
  gui/bidi_and_font_features/README.md
  gui/bidi_and_font_features/bidi.tscn
  gui/bidi_and_font_features/custom_st_parser.gd
  gui/bidi_and_font_features/fonts/LinLibertine_R.otf.import
  gui/bidi_and_font_features/fonts/NotoNaskhArabicUI_Regular.ttf.import
  gui/bidi_and_font_features/fonts/NotoSansHebrew_Regular.ttf.import
  gui/bidi_and_font_features/fonts/NotoSansThaiUI_Regular.ttf.import
  gui/bidi_and_font_features/fonts/NotoSansUI_Regular.ttf.import
  gui/bidi_and_font_features/icon.png.import
  gui/bidi_and_font_features/lib_font.tres
  gui/bidi_and_font_features/noto_font.tres
  gui/bidi_and_font_features/project.godot
  gui/bidi_and_font_features/screenshots/.gdignore
  gui/bidi_and_font_features/screenshots/bidi.png.import
  gui/bidi_and_font_features/screenshots/font_features.png.import
  gui/bidi_and_font_features/screenshots/line_break_and_fill.png.import
Labels: update

#806 Convert 3D navmesh demo to use NavigationAgents
  3d/navmesh/character.gd
  3d/navmesh/line3d.gd
  3d/navmesh/navigation.gd
  3d/navmesh/navmesh.gd
  3d/navmesh/navmesh.tscn
  3d/navmesh/particle.png
  3d/navmesh/particle.png.import
Labels: enhancement

#744 Add a text-to-speech demo
  audio/text_to_speech/README.md
  audio/text_to_speech/control.tscn
  audio/text_to_speech/icon.png
  audio/text_to_speech/icon.png.import
  audio/text_to_speech/project.godot
  audio/text_to_speech/screenshots/.gdignore
  audio/text_to_speech/screenshots/text_to_speech.webp
  audio/text_to_speech/voice_list.gd
Labels: new demo

#771 Check for obstacle before teleporting player in Grid-based Pathfinding with Astar
  2d/navigation_astar/character.gd
  2d/navigation_astar/pathfind_astar.gd
Labels: enhancement

#850 Update finite state machine demo for 4.0.rc4
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/README.md
  2d/finite_state_machine/debug/ControlsPanel.tscn
  2d/finite_state_machine/debug/StatesStackDiplayer.tscn
  2d/finite_state_machine/debug/states_stack_displayer.gd
  2d/finite_state_machine/fonts/SourceCodePro-Black.ttf.import
  2d/finite_state_machine/fonts/SourceCodePro-Bold.ttf.import
  2d/finite_state_machine/icon.png.import
  2d/finite_state_machine/player/Player.tscn
  2d/finite_state_machine/player/body.png.import
  2d/finite_state_machine/player/shadow.png.import
  2d/finite_state_machine/player/states/motion/in_air/jump.gd
  2d/finite_state_machine/player/states/motion/on_ground/move.gd
  2d/finite_state_machine/player/weapon/sword.gd
  2d/finite_state_machine/player/weapon/sword.png.import
  2d/finite_state_machine/project.godot
  2d/finite_state_machine/state_machine/state_machine.gd
Labels: update

#765 Rework basic 2D navigation demo for Godot 3.5 and later
  2d/navigation/character.gd
  2d/navigation/level.tscn
  2d/navigation/navigation.gd
Labels: enhancement

#862 Remove unnecessary `randomize()`
  2d/bullet_shower/bullets.gd
  2d/dodge_the_creeps/Main.gd
  networking/webrtc_signaling/demo/client_ui.gd
  viewport/dynamic_split_screen/wall_coloring.gd
Labels: enhancement

#863 Fix `SCREEN_TEXTURE` in "Screen Space Shaders" demo
  2d/screen_space_shaders/art/filmgrain.png.import
  2d/screen_space_shaders/art/vignette.png.import
  2d/screen_space_shaders/screen_shaders.tscn
  2d/screen_space_shaders/shaders/BCS.gdshader
  2d/screen_space_shaders/shaders/blur.gdshader
  2d/screen_space_shaders/shaders/contrasted.gdshader
  2d/screen_space_shaders/shaders/mirage.gdshader
  2d/screen_space_shaders/shaders/negative.gdshader
  2d/screen_space_shaders/shaders/normalized.gdshader
  2d/screen_space_shaders/shaders/old_film.gdshader
  2d/screen_space_shaders/shaders/pixelize.gdshader
  2d/screen_space_shaders/shaders/sepia.gdshader
  2d/screen_space_shaders/shaders/vignette.gdshader
  2d/screen_space_shaders/shaders/whirl.gdshader
Labels: bug, topic:shaders, refactor

#858 Fix "is mount_event" check in gui_in_3d to work with both 4 beta and 4 rc
  plugins/addons/main_screen/main_screen_plugin.gd
  viewport/gui_in_3d/gui_3d.gd
Labels: bug

#859 Improve Audio Spectrum demo
  audio/spectrum/README.md
  audio/spectrum/icon.png
  audio/spectrum/icon.png.import
  audio/spectrum/maldita.wav.import
  audio/spectrum/project.godot
  audio/spectrum/screenshots/spectrum.png
  audio/spectrum/screenshots/spectrum.webp
  audio/spectrum/show_spectrum.gd
  audio/spectrum/show_spectrum.tscn
Labels: enhancement

#795 [3.x] [WebSocket] Fix peer disconnection not closing the network layer.
  networking/websocket_multiplayer/script/main.gd
Labels: bug, topic:network

#861 Rework "Grid-based Navigation with Astar" demo
  2d/navigation_astar/README.md
  2d/navigation_astar/character.gd
  2d/navigation_astar/game.tscn
  2d/navigation_astar/pathfind_astar.gd
  2d/navigation_astar/project.godot
  2d/navigation_astar/tileset.tres
  2d/navigation_astar/tileset/tileset_source.tscn
Labels: enhancement
