Repository godotengine/godot-demo-projects, pull requests merged in 2023-01, with the labels that each got.

#810 Add a compute shader demo
  misc/compute_shader_heightmap/README.md
  misc/compute_shader_heightmap/compute_shader.glsl
  misc/compute_shader_heightmap/compute_shader.glsl.import
  misc/compute_shader_heightmap/icon.svg
  misc/compute_shader_heightmap/icon.svg.import
  misc/compute_shader_heightmap/main.gd
  misc/compute_shader_heightmap/main.tscn
  misc/compute_shader_heightmap/project.godot
  misc/compute_shader_heightmap/screenshots/.gdignore
  misc/compute_shader_heightmap/screenshots/compute_shader_heightmap.webp
Labels: new demo

#811 Fix property name of viewport width/height settings in Multiple resolutions
  gui/multiple_resolutions/main.gd
Labels: bug

#812 Fix misleading comment in WebRTC Signaling
  networking/webrtc_signaling/client/ws_webrtc_client.gd
Labels: bug

#813 Fix method names in GD Paint that have changed in 4.0
  gui/gd_paint/paint_control.gd
  gui/gd_paint/tools_panel.gd
Labels: update

#819 Fix canvas size having a 1-frame delay in Multiple resolutions
  gui/multiple_resolutions/main.gd
  gui/multiple_resolutions/main.tscn
  gui/multiple_resolutions/project.godot
Labels: bug

#825 [Net] Fix Multiplayer Bomber custom spawner.
  networking/multiplayer_bomber/bomb_spawner.gd
Labels: bug, topic:network

#814 Improve 2D in 3D demo
  viewport/2d_in_3d/2d_in_3d.gd
  viewport/2d_in_3d/2d_in_3d.tscn
  viewport/2d_in_3d/README.md
  viewport/2d_in_3d/project.godot
  viewport/2d_in_3d/screenshots/2d_in_3d.webp
  viewport/2d_in_3d/screenshots/pong.png
Labels: bug, enhancement

#821 Improve Regular Expressions (RegEx) demo
  gui/regex/README.md
  gui/regex/icon.png
  gui/regex/icon.png.import
  gui/regex/project.godot
  gui/regex/regex.gd
  gui/regex/regex.tscn
  gui/regex/screenshots/regex.png
  gui/regex/screenshots/regex.webp
Labels: enhancement, update

#820 Add camera selection to Truck Town
  3d/truck_town/README.md
  3d/truck_town/project.godot
  3d/truck_town/town/town_scene.tscn
  3d/truck_town/vehicles/car_base.tscn
  3d/truck_town/vehicles/follow_camera.gd
  3d/truck_town/vehicles/tow_truck.tscn
  3d/truck_town/vehicles/trailer_truck.tscn
Labels: enhancement

#817 Update and improve GUI Theming Override demo
  gui/theming_override/README.md
  gui/theming_override/icon.png.import
  gui/theming_override/project.godot
  gui/theming_override/screenshots/.gdignore
  gui/theming_override/screenshots/theming_override.png
  gui/theming_override/screenshots/theming_override.png.import
  gui/theming_override/screenshots/theming_override.webp
  gui/theming_override/test.gd
  gui/theming_override/test.tscn
Labels: enhancement, update

#816 Improve the Rich Text Label with BBCode demo
  gui/rich_text_bbcode/README.md
  gui/rich_text_bbcode/SIL Open Font License.txt
  gui/rich_text_bbcode/Titillium-Bold.otf
  gui/rich_text_bbcode/Titillium-BoldItalic.otf
  gui/rich_text_bbcode/Titillium-Regular.otf
  gui/rich_text_bbcode/Titillium-RegularItalic.otf
  gui/rich_text_bbcode/icon.png.import
  gui/rich_text_bbcode/project.godot
  gui/rich_text_bbcode/rich_text_bbcode.gd
  gui/rich_text_bbcode/rich_text_bbcode.tscn
  gui/rich_text_bbcode/screenshots/rich_text.png
  gui/rich_text_bbcode/screenshots/rich_text_bbcode.webp
  gui/rich_text_bbcode/unicorn_icon.png.import
Labels: enhancement

#815 Improve dynamic split screen demo
  viewport/dynamic_split_screen/README.md
  viewport/dynamic_split_screen/camera_controller.gd
  viewport/dynamic_split_screen/player.gd
  viewport/dynamic_split_screen/project.godot
  viewport/dynamic_split_screen/screenshots/dynamic_split_screen.webp
  viewport/dynamic_split_screen/screenshots/splitscreen.png
  viewport/dynamic_split_screen/split_screen.gdshader
  viewport/dynamic_split_screen/split_screen.tscn
Labels: enhancement

#756 Add a 3D decals demo
  3d/decals/README.md
  3d/decals/decal.tscn
  3d/decals/default_env.tres
  3d/decals/icon.png
  3d/decals/icon.png.import
  3d/decals/project.godot
  3d/decals/screenshots/.gdignore
  3d/decals/screenshots/decals.png
  3d/decals/test.tscn
  3d/decals/tester.gd
  3d/decals/textures/checker.LICENSE.md
  3d/decals/textures/checker.png
  3d/decals/textures/checker.png.import
  3d/decals/textures/circle_blob.png
  3d/decals/textures/circle_blob.png.import
  3d/decals/textures/circle_blob_emissive.png
  3d/decals/textures/circle_blob_emissive.png.import
  3d/decals/textures/icon_outlined.png
  3d/decals/textures/icon_outlined.png.import
  3d/decals/textures/icon_outlined_normal.png
  3d/decals/textures/icon_outlined_normal.png.import
  3d/decals/textures/paint.LICENSE.md
  3d/decals/textures/paint.png
  3d/decals/textures/paint.png.import
  3d/decals/textures/paint_normal.png
  3d/decals/textures/paint_normal.png.import
  3d/decals/textures/paintedarrow.LICENSE.md
  3d/decals/textures/paintedarrow.png
  3d/decals/textures/paintedarrow.png.import
  3d/decals/textures/paintedarrow_normal.png
  3d/decals/textures/paintedarrow_normal.png.import
  3d/decals/textures/plasma_emissive.png
  3d/decals/textures/plasma_emissive.png.import
  3d/decals/textures/plasma_stain.png
  3d/decals/textures/plasma_stain.png.import
  3d/decals/textures/puddles_albedo.png
  3d/decals/textures/puddles_albedo.png.import
  3d/decals/textures/puddles_orm.png
  3d/decals/textures/puddles_orm.png.import
  3d/decals/textures/scifi.LICENSE.md
  3d/decals/textures/scifi_1_albedo.png
  3d/decals/textures/scifi_1_albedo.png.import
  3d/decals/textures/scifi_1_normal.png
  3d/decals/textures/scifi_1_normal.png.import
  3d/decals/textures/scifi_2_albedo.png
  3d/decals/textures/scifi_2_albedo.png.import
  3d/decals/textures/scifi_2_normal.png
  3d/decals/textures/scifi_2_normal.png.import
  3d/decals/textures/scifi_3_albedo.png
  3d/decals/textures/scifi_3_albedo.png.import
  3d/decals/textures/scifi_3_normal.png
  3d/decals/textures/scifi_3_normal.png.import
  3d/decals/textures/scifi_4_albedo.png
  3d/decals/textures/scifi_4_albedo.png.import
  3d/decals/textures/scifi_4_normal.png
  3d/decals/textures/scifi_4_normal.png.import
Labels: new demo

#757 Add a 3D particles demo
  3d/particles/README.md
  3d/particles/checker.LICENSE.md
  3d/particles/checker.png
  3d/particles/checker.png.import
  3d/particles/default_env.tres
  3d/particles/icon.png
  3d/particles/icon.png.import
  3d/particles/kenney/smoke_05.png
  3d/particles/kenney/smoke_05.png.import
  3d/particles/project.godot
  3d/particles/screenshots/.gdignore
  3d/particles/screenshots/3d_particles.png
  3d/particles/test.GPUParticlesCollisionSDF3D_data.exr
  3d/particles/test.GPUParticlesCollisionSDF3D_data.exr.import
  3d/particles/test.tscn
  3d/particles/tester.gd
Labels: new demo

#826 Add a 3D lights and shadows demo
  3d/lights_and_shadows/README.md
  3d/lights_and_shadows/checker.LICENSE.md
  3d/lights_and_shadows/checker.png
  3d/lights_and_shadows/checker.png.import
  3d/lights_and_shadows/day_night_cycle.gd
  3d/lights_and_shadows/default_env.tres
  3d/lights_and_shadows/icon.png
  3d/lights_and_shadows/icon.png.import
  3d/lights_and_shadows/logo_projector.png
  3d/lights_and_shadows/logo_projector.png.import
  3d/lights_and_shadows/project.godot
  3d/lights_and_shadows/screenshots/.gdignore
  3d/lights_and_shadows/screenshots/3d_lights_and_shadows.webp
  3d/lights_and_shadows/spin.gd
  3d/lights_and_shadows/test.tscn
  3d/lights_and_shadows/tester.gd
Labels: new demo

#761 Add a 3D labels and texts demo
  3d/labels_and_texts/3d_labels_and_texts.gd
  3d/labels_and_texts/3d_labels_and_texts.tscn
  3d/labels_and_texts/README.md
  3d/labels_and_texts/curvature.gdshader
  3d/labels_and_texts/default_env.tres
  3d/labels_and_texts/fonts/Xolonium-Regular-MSDF-Mipmaps.ttf
  3d/labels_and_texts/fonts/Xolonium-Regular-MSDF-Mipmaps.ttf.import
  3d/labels_and_texts/fonts/Xolonium-Regular-MSDF.ttf
  3d/labels_and_texts/fonts/Xolonium-Regular-MSDF.ttf.import
  3d/labels_and_texts/fonts/Xolonium-Regular-Mipmaps.ttf
  3d/labels_and_texts/fonts/Xolonium-Regular-Mipmaps.ttf.import
  3d/labels_and_texts/fonts/Xolonium-Regular.ttf
  3d/labels_and_texts/fonts/Xolonium-Regular.ttf.import
  3d/labels_and_texts/fonts/config.json
  3d/labels_and_texts/fonts/fontello-godot.woff2
  3d/labels_and_texts/fonts/fontello-godot.woff2.import
  3d/labels_and_texts/icon.png
  3d/labels_and_texts/icon.png.import
  3d/labels_and_texts/label_3d_layout.gd
  3d/labels_and_texts/project.godot
  3d/labels_and_texts/screenshots/.gdignore
  3d/labels_and_texts/screenshots/3d_labels_and_texts.png
  3d/labels_and_texts/textures/checker.LICENSE.md
  3d/labels_and_texts/textures/checker.png
  3d/labels_and_texts/textures/checker.png.import
  3d/labels_and_texts/textures/textmesh_texture.LICENSE.md
  3d/labels_and_texts/textures/textmesh_texture.png
  3d/labels_and_texts/textures/textmesh_texture.png.import
Labels: new demo

#805 Add a constructive solid geometry (CSG) demo
  3d/csg/README.md
  3d/csg/blue_material.tres
  3d/csg/csg.gd
  3d/csg/csg.tscn
  3d/csg/icon.png
  3d/csg/icon.png.import
  3d/csg/indigo_material.tres
  3d/csg/project.godot
  3d/csg/screenshots/.gdignore
  3d/csg/screenshots/csg.webp
  3d/csg/textures/checker.LICENSE.md
  3d/csg/textures/checker.png
  3d/csg/textures/checker.png.import
Labels: new demo

#818 Fix and update the Operating System Testing demo
  misc/os_test/actions.gd
  misc/os_test/os_test.gd
Labels: bug, update

#828 Fix joypads demo button/axis mappings for 4.0
  misc/joypads/joypad_diagram.tscn
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
  misc/joypads/project.godot
Labels: bug, update

#829 Update multiple resolutions README with an asset library link
  gui/multiple_resolutions/README.md
Labels: update

#831 Fix bomb collisions through walls on 3.5
  networking/multiplayer_bomber/bomb.gd
Labels: enhancement

#832 Fix bomb collisions through walls on 4.0-dev
  networking/multiplayer_bomber/bomb.gd
Labels: bug

#833 Fix bomb animation
  networking/multiplayer_bomber/bomb.tscn
Labels: bug

#830 Improve joypads demo
  misc/joypads/README.md
  misc/joypads/joypads.gd
  misc/joypads/joypads.tscn
  misc/joypads/project.godot
  misc/joypads/screenshots/joypads.png
  misc/joypads/screenshots/joypads.webp
Labels: enhancement
