Repository godotengine/godot-demo-projects, pull requests merged in 2023-10, with the labels that each got.

#971 3D Physics Tests, test_collision_pairs, HSlider bugfix
  3d/physics_tests/project.godot
  3d/physics_tests/tests/functional/test_collision_pairs.tscn
Labels: bug

#980 Add glass material to Procedural materials demo
  3d/procedural_materials/materials/glass.tres
  3d/procedural_materials/materials/textures/glass_normal.tres
  3d/procedural_materials/materials/textures/glass_refraction.tres
  3d/procedural_materials/materials/textures/trypophobia_albedo.tres
  3d/procedural_materials/materials/textures/trypophobia_normal.tres
  3d/procedural_materials/materials/textures/trypophobia_roughness.tres
  3d/procedural_materials/materials/trypophobia.tres
  3d/procedural_materials/project.godot
  3d/procedural_materials/test.tscn
Labels: enhancement

#970 3D Graphics Settings, Limit FPS
  3d/graphics_settings/control.tscn
  3d/graphics_settings/project.godot
  3d/graphics_settings/settings.gd
Labels: enhancement

#972 Audio Spectrum: added smoother animations
  audio/spectrum/project.godot
  audio/spectrum/show_spectrum.gd
Labels: enhancement, topic:audio

#968 3D Anti-Aliasing, added 'FPS Counter', VSync, Limit FPS
  3d/antialiasing/anti_aliasing.gd
  3d/antialiasing/anti_aliasing.tscn
  3d/antialiasing/project.godot
Labels: enhancement

#958 Physics-Based Platformer 2D, fixed "Debugger Errors"
  2d/physics_platformer/background/parallax_bg.tscn
  2d/physics_platformer/coin/coin.tscn
  2d/physics_platformer/enemy/enemy.tscn
  2d/physics_platformer/project.godot
  2d/physics_platformer/stage.tscn
Labels: update

#955 'Navigation Polygon 2D' ported to Godot 4.1.1
  2d/navigation/README.md
  2d/navigation/character.gd
  2d/navigation/character.png.import
  2d/navigation/character.tscn
  2d/navigation/level.tscn
  2d/navigation/map.png.import
  2d/navigation/navigation.gd
  2d/navigation/navigation.tscn
  2d/navigation/navigation_polygon.res
  2d/navigation/project.godot
Labels: update

#978 Matrix Transform: ported to Godot 4.2
  misc/matrix_transform/marker/AxisMarker2D.gd
  misc/matrix_transform/marker/AxisMarker2D.svg.import
  misc/matrix_transform/marker/AxisMarker3D.gd
  misc/matrix_transform/marker/AxisMarker3D.svg.import
  misc/matrix_transform/project.godot
Labels: update

#937 fsm: Map attack to gamepad X; revise text
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/debug/StatesStackDiplayer.tscn
  2d/finite_state_machine/project.godot
Labels: enhancement

#947 Update main.gd
  mobile/sensors/main.gd
Labels: bug

#954 Add dynamic TileMap layer demo
  2d/dynamic_tilemap_layers/README.md
  2d/dynamic_tilemap_layers/icon.png
  2d/dynamic_tilemap_layers/icon.png.import
  2d/dynamic_tilemap_layers/level/obstacle.png
  2d/dynamic_tilemap_layers/level/obstacle.png.import
  2d/dynamic_tilemap_layers/level/tile_map.gd
  2d/dynamic_tilemap_layers/player/player.gd
  2d/dynamic_tilemap_layers/player/player.png
  2d/dynamic_tilemap_layers/player/player.png.import
  2d/dynamic_tilemap_layers/player/player.tscn
  2d/dynamic_tilemap_layers/project.godot
  2d/dynamic_tilemap_layers/screenshots/.gdignore
  2d/dynamic_tilemap_layers/screenshots/fake_wall.png
  2d/dynamic_tilemap_layers/world.tscn
Labels: new demo

#975 Use NavigationAgent3D in 3d/navigation demo
  3d/navigation/character.gd
  3d/navigation/line3d.gd
  3d/navigation/navmesh.gd
  3d/navigation/navmesh.res
  3d/navigation/navmesh.tscn
  3d/navigation/particle.png
  3d/navigation/particle.png.import
Labels: enhancement

#962 2D Physics Tests, fixed "one-way collision script error"
  2d/physics_tests/project.godot
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/physics_tests/tests/functional/test_one_way_collision.tscn
Labels: bug

#982 Example of "webrtc_signaling" not working on the web
  networking/webrtc_signaling/client/ws_webrtc_client.gd
Labels: bug, topic:network

#987 Multiplayer Bomber, fixes PhysicsRayQuery
  networking/multiplayer_bomber/bomb.gd
  networking/multiplayer_bomber/bomb.tscn
  networking/multiplayer_bomber/player.tscn
  networking/multiplayer_bomber/project.godot
Labels: bug

#989 Multitouch Cubes: ported to Godot 4.1
  mobile/multitouch_cubes/CubeScene.tscn
  mobile/multitouch_cubes/GestureArea.gd
  mobile/multitouch_cubes/Main.tscn
  mobile/multitouch_cubes/default_env.tres
  mobile/multitouch_cubes/project.godot
Labels: update

#976 Port 2D Skeleton demo to Godot 4.1
  2d/skeleton/README.md
  2d/skeleton/level.tscn
  2d/skeleton/level/background/cloud_1.png.import
  2d/skeleton/level/background/cloud_2.png.import
  2d/skeleton/level/background/cloud_3.png.import
  2d/skeleton/level/background/distant_platforms_1.png.import
  2d/skeleton/level/background/distant_platforms_2.png.import
  2d/skeleton/level/background/sky.png.import
  2d/skeleton/level/level.gd
  2d/skeleton/level/parallax_background.tscn
  2d/skeleton/level/tileset/tiles_demo.png.import
  2d/skeleton/level/tileset/tileset.tres
  2d/skeleton/player/gBot.png.import
  2d/skeleton/player/player.gd
  2d/skeleton/player/player.tscn
  2d/skeleton/project.godot
Labels: update

#992 Mobile Sensors: ported to Godot 4.1
  mobile/sensors/README.md
  mobile/sensors/cube_6.png.import
  mobile/sensors/default_env.tres
  mobile/sensors/main.gd
  mobile/sensors/main.tscn
  mobile/sensors/project.godot
  mobile/sensors/screenshots/sensors.png
  mobile/sensors/screenshots/sensors.webp
Labels: update

#990 WebSocket Minimal: ported to Godot 4.1
  networking/websocket_minimal/Main.tscn
  networking/websocket_minimal/README.md
  networking/websocket_minimal/client.gd
  networking/websocket_minimal/project.godot
  networking/websocket_minimal/server.gd
Labels: enhancement, update

#986 Fix Trail(GPUParticles2D) in Dodge The Creeps
  2d/dodge_the_creeps/Player.gd
  2d/dodge_the_creeps/Player.tscn
  2d/dodge_the_creeps/project.godot
Labels: bug
