Repository godotengine/godot-demo-projects, pull requests merged in 2023-05, with the labels that each got.

#912 Add demo submission guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: enhancement

#883 Update 3D Graphics Settings demo for 4.0
  3d/graphics_settings/control.tscn
  3d/graphics_settings/polyhaven/dutch_ship_medium_1k.gltf.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_arm_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_diff_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_nor_gl_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_arm_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_diff_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_nor_gl_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_arm_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_diff_1k.jpg.import
  3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_nor_gl_1k.jpg.import
  3d/graphics_settings/settings.gd
Labels: enhancement, update

#871 Add AMD FidelityFX Super Resolution 1.0 toggle to the 3D antialiasing demo
  3d/antialiasing/README.md
  3d/antialiasing/anti_aliasing.gd
  3d/antialiasing/anti_aliasing.tscn
  3d/antialiasing/polyhaven/dutch_ship_medium_1k.gltf.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_hull_nor_gl_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_rigging_nor_gl_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_arm_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_diff_1k.jpg.import
  3d/antialiasing/polyhaven/textures/dutch_ship_medium_sails_nor_gl_1k.jpg.import
  3d/antialiasing/project.godot
  3d/antialiasing/screenshots/3d_anti_aliasing.png
  3d/antialiasing/screenshots/antialiasing.webp
  3d/antialiasing/textures/checker.png.import
  3d/antialiasing/textures/paint.png.import
  3d/antialiasing/textures/paint_normal.png.import
Labels: enhancement

#908 Fix particles in Platformer 3D demo, add coin glow
  3d/platformer/coin/coin.tscn
  3d/platformer/enemy/enemy.tscn
  3d/platformer/particle_material.tres
  3d/platformer/player/bullet/bullet.tscn
  3d/platformer/player/player.tscn
Labels: bug, enhancement

#907 Use a different color for moving platforms in platformer demos
  2d/kinematic_character/level/circle.png.import
  2d/kinematic_character/level/long_obstacle.png.import
  2d/kinematic_character/level/obstacle.png.import
  2d/kinematic_character/level/princess.png.import
  2d/kinematic_character/player/player.png.import
  2d/kinematic_character/project.godot
  2d/kinematic_character/world.tscn
  3d/kinematic_character/cubelib.tres
  3d/kinematic_character/level.tscn
  3d/kinematic_character/models/cube.glb.import
  3d/kinematic_character/models/cube.mesh
  3d/kinematic_character/models/mushroom.glb.import
  3d/kinematic_character/models/white_wood.png.import
  3d/kinematic_character/project.godot
  3d/rigidbody_character/cubelib.tres
  3d/rigidbody_character/level.tscn
  3d/rigidbody_character/models/cube.glb.import
  3d/rigidbody_character/models/cube.mesh
  3d/rigidbody_character/models/mushroom.glb.import
  3d/rigidbody_character/models/white_wood.png.import
  3d/rigidbody_character/project.godot
Labels: enhancement

#918 [WebSocket] Fix chat demo to updated TLS function.
  networking/websocket_chat/chat.tscn
  networking/websocket_chat/client.tscn
  networking/websocket_chat/combo.tscn
  networking/websocket_chat/project.godot
  networking/websocket_chat/server.tscn
  networking/websocket_chat/websocket/WebSocketClient.gd
  networking/websocket_chat/websocket/WebSocketServer.gd
Labels: update, cherrypick:4.0

#902 Change copyright year to "present" in LICENSE.md
  LICENSE.md
Labels: enhancement
