Repository godotengine/godot-demo-projects, pull requests merged in 2024-07, with the labels that each got.

#973 Add OpenXR hand tracking demo
  xr/openxr_hand_tracking_demo/.gitignore
  xr/openxr_hand_tracking_demo/README.md
  xr/openxr_hand_tracking_demo/assets/gltf/LeftHandHumanoid.bin
  xr/openxr_hand_tracking_demo/assets/gltf/LeftHandHumanoid.gltf
  xr/openxr_hand_tracking_demo/assets/gltf/LeftHandHumanoid.gltf.import
  xr/openxr_hand_tracking_demo/assets/gltf/RightHandHumanoid.bin
  xr/openxr_hand_tracking_demo/assets/gltf/RightHandHumanoid.gltf
  xr/openxr_hand_tracking_demo/assets/gltf/RightHandHumanoid.gltf.import
  xr/openxr_hand_tracking_demo/assets/gltf/hand.png
  xr/openxr_hand_tracking_demo/assets/gltf/hand.png.import
  xr/openxr_hand_tracking_demo/assets/images/pattern.png
  xr/openxr_hand_tracking_demo/assets/images/pattern.png.import
  xr/openxr_hand_tracking_demo/hand_info.gd
  xr/openxr_hand_tracking_demo/hand_info.tscn
  xr/openxr_hand_tracking_demo/icon.svg
  xr/openxr_hand_tracking_demo/icon.svg.import
  xr/openxr_hand_tracking_demo/main.tscn
  xr/openxr_hand_tracking_demo/objects/box.tscn
  xr/openxr_hand_tracking_demo/objects/table.tscn
  xr/openxr_hand_tracking_demo/openxr_action_map.tres
  xr/openxr_hand_tracking_demo/pickup/pickup_able_body.gd
  xr/openxr_hand_tracking_demo/pickup/pickup_handler.gd
  xr/openxr_hand_tracking_demo/pickup/pickup_handler.tscn
  xr/openxr_hand_tracking_demo/project.godot
  xr/openxr_hand_tracking_demo/screenshots/hand_tracking_demo.png
  xr/openxr_hand_tracking_demo/screenshots/hand_tracking_demo.png.import
  xr/openxr_hand_tracking_demo/shaders/highlight_material.tres
  xr/openxr_hand_tracking_demo/shaders/highlight_shader.tres
  xr/openxr_hand_tracking_demo/start_vr.gd
Labels: new demo, topic:xr

#1084 Rename Dodge The Creeps files to snake case
  2d/dodge_the_creeps/hud.gd
  2d/dodge_the_creeps/hud.tscn
  2d/dodge_the_creeps/main.gd
  2d/dodge_the_creeps/main.tscn
  2d/dodge_the_creeps/mob.gd
  2d/dodge_the_creeps/mob.tscn
  2d/dodge_the_creeps/player.gd
  2d/dodge_the_creeps/player.tscn
  2d/dodge_the_creeps/project.godot
Labels: enhancement

#1082 Add a 2D polygons and lines demo
  2d/polygons_lines/README.md
  2d/polygons_lines/icon.webp
  2d/polygons_lines/icon.webp.import
  2d/polygons_lines/line_10px.png
  2d/polygons_lines/line_10px.png.import
  2d/polygons_lines/line_30px.png
  2d/polygons_lines/line_30px.png.import
  2d/polygons_lines/polygons_lines.gd
  2d/polygons_lines/polygons_lines.tscn
  2d/polygons_lines/project.godot
  2d/polygons_lines/screenshots/.gdignore
  2d/polygons_lines/screenshots/polygons_lines.webp
Labels: new demo, cherrypick:4.2

#1094 Add JetBrains IDE files to .gitignore
  .gitignore
Labels: enhancement

#1096 Fix typing errors in webrtc_signaling demo
  networking/webrtc_signaling/client/multiplayer_client.gd
  networking/webrtc_signaling/client/ws_webrtc_client.gd
  networking/webrtc_signaling/demo/client_ui.gd
  networking/webrtc_signaling/server/ws_webrtc_server.gd
Labels: bug
