Repository godotengine/godot-demo-projects, pull requests merged in 2024-11, with the labels that each got.

#1129 Update some GDScript files
  2d/dynamic_tilemap_layers/level/tile_map.gd
  2d/dynamic_tilemap_layers/project.godot
  2d/dynamic_tilemap_layers/world.tscn
  2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd
  2d/finite_state_machine/state_machine/state.gd
  2d/isometric/player/goblin.gd
  2d/physics_tests/tests/functional/test_one_way_collision.gd
  2d/role_playing_game/combat/combat.gd
  2d/role_playing_game/combat/turn_queue.gd
  2d/role_playing_game/project.godot
  2d/role_playing_game/theme/fonts/montserrat_extra_bold.otf.import
  3d/squash_the_creeps/Main.gd
  audio/midi_piano/piano.gd
  audio/midi_piano/project.godot
  gui/gd_paint/paint_control.gd
  misc/2.5d/addons/node25d/.broken-gdscripts/Basis25D.gd
  misc/2.5d/addons/node25d/y_sort_25d.gd
  misc/2.5d/assets/player/player_sprite.gd
  misc/joypads/project.godot
  misc/joypads/remap/remap_wizard.gd
  networking/multiplayer_bomber/bomb.gd
  networking/multiplayer_bomber/montserrat.otf.import
  networking/multiplayer_bomber/project.godot
  xr/openxr_composition_layers/main.gd
Labels: enhancement, topic:gdscript

#1130 Disable non-functional XR demos in web exports
  .github/dist/footer.html
  .github/dist/header.html
  .github/workflows/export_web.yml
Labels: bug, topic:xr

#1131 OpenXR fix character centric recenter code
  xr/openxr_character_centric_movement/player.gd
Labels: bug, topic:xr

#1133 Use TileMapLayer in demo dynamic_tilemap_layers since TileMap is deprecated
  2d/dynamic_tilemap_layers/level/tile_map.gd
  2d/dynamic_tilemap_layers/player/player.tscn
  2d/dynamic_tilemap_layers/world.tscn
Labels: update, cherrypick:4.3

#1135 Update 2D navigation demo NavigationPolygon for 4.3+
  2d/navigation/navigation.tscn
  2d/navigation/navigation_polygon.res
Labels: bug, topic:navigation

#1110 Improve Truck Town model, fix issues, use OMI glTF Physics
  3d/truck_town/town/materials/cement.tres
  3d/truck_town/town/materials/cement.webp
  3d/truck_town/town/materials/grass.tres
  3d/truck_town/town/materials/grass.webp
  3d/truck_town/town/model/racetrack_csg.tscn
  3d/truck_town/town/model/textures/cement_lossy.webp
  3d/truck_town/town/model/textures/cement_lossy.webp.import
  3d/truck_town/town/model/textures/grass_lossy.webp
  3d/truck_town/town/model/textures/grass_lossy.webp.import
  3d/truck_town/town/model/town_model.gltf
  3d/truck_town/town/model/town_model.gltf.import
  3d/truck_town/town/model/town_model0.bin
  3d/truck_town/town/town_scene.tscn
  3d/truck_town/town/truck_town.glb
  3d/truck_town/town/truck_town.glb.import
  3d/truck_town/vehicles/meshes/meshes.glb.import
  3d/truck_town/vehicles/vehicle.gd
Labels: bug, enhancement

#1140 Improve GUI in 3D demo
  viewport/gui_in_3d/gui_panel_3d.tscn
  viewport/gui_in_3d/project.godot
Labels: enhancement, cherrypick:4.3

#1138 Add moods (times of day) to Truck Town demo
  3d/truck_town/README.md
  3d/truck_town/car_select/car_select.gd
  3d/truck_town/car_select/car_select.tscn
  3d/truck_town/project.godot
  3d/truck_town/town/sky_day.tres
  3d/truck_town/town/sky_morning.tres
  3d/truck_town/town/sky_night.tres
  3d/truck_town/town/sky_sunset.tres
  3d/truck_town/town/town_scene.gd
  3d/truck_town/town/town_scene.tscn
  3d/truck_town/vehicles/meshes/minivan.res
  3d/truck_town/vehicles/meshes/tow_truck.res
  3d/truck_town/vehicles/meshes/truck_cab.res
  3d/truck_town/vehicles/meshes/truck_trailer.res
  3d/truck_town/vehicles/meshes/wheel.res
Labels: enhancement, cherrypick:4.3
