Repository godotengine/godot-demo-projects, pull requests merged in 2024-02, with the labels that each got.

#1014 Improve volumetric fog demo
  3d/volumetric_fog/README.md
  3d/volumetric_fog/camera.gd
  3d/volumetric_fog/project.godot
  3d/volumetric_fog/screenshots/volumetric_fog.png
  3d/volumetric_fog/screenshots/volumetric_fog.webp
  3d/volumetric_fog/volumetric_fog.tscn
Labels: enhancement, cherrypick:4.2

#1015 Fix Web platform checks in WebRTC signaling demo
  networking/webrtc_signaling/demo/main.gd
  networking/webrtc_signaling/server/ws_webrtc_server.gd
Labels: bug

#925 Rewrite Gui in 3D demo to use Physics Picking for mouse events
  viewport/gui_in_3d/gui_3d.gd
  viewport/gui_in_3d/gui_in_3d.tscn
Labels: enhancement
