Repository godotengine/godot-demo-projects, pull requests merged in 2024-08, with the labels that each got.

#1099 Add navigation mesh chunks demos
  2d/navigation_mesh_chunks/README.md
  2d/navigation_mesh_chunks/icon.webp
  2d/navigation_mesh_chunks/navmesh_chhunks_demo_2d.gd
  2d/navigation_mesh_chunks/navmesh_chhunks_demo_2d.tscn
  2d/navigation_mesh_chunks/project.godot
  2d/navigation_mesh_chunks/screenshots/.gdignore
  2d/navigation_mesh_chunks/screenshots/navigation_mesh_chunks.webp
  3d/navigation_mesh_chunks/README.md
  3d/navigation_mesh_chunks/icon.webp
  3d/navigation_mesh_chunks/navmesh_chhunks_demo_3d.gd
  3d/navigation_mesh_chunks/navmesh_chhunks_demo_3d.tscn
  3d/navigation_mesh_chunks/project.godot
  3d/navigation_mesh_chunks/screenshots/.gdignore
  3d/navigation_mesh_chunks/screenshots/navigation_mesh_chunks.webp
Labels: new demo

#1100 Fix incorrect asset library link
  3d/lights_and_shadows/README.md
Labels: bug, cherrypick:4.2

#1080 OpenXR composition layer example
  xr/openxr_composition_layers/.gitignore
  xr/openxr_composition_layers/README.md
  xr/openxr_composition_layers/assets/pattern.png
  xr/openxr_composition_layers/assets/pattern.png.import
  xr/openxr_composition_layers/cursor.gdshader
  xr/openxr_composition_layers/handle_pointers.gd
  xr/openxr_composition_layers/icon.svg
  xr/openxr_composition_layers/icon.svg.import
  xr/openxr_composition_layers/main.gd
  xr/openxr_composition_layers/main.tscn
  xr/openxr_composition_layers/openxr_action_map.tres
  xr/openxr_composition_layers/pointer.gdshader
  xr/openxr_composition_layers/pointer.tscn
  xr/openxr_composition_layers/project.godot
  xr/openxr_composition_layers/screenshots/xr_composition_layer_demo.png
  xr/openxr_composition_layers/screenshots/xr_composition_layer_demo.png.import
  xr/openxr_composition_layers/start_vr.gd
  xr/openxr_composition_layers/ui.gd
  xr/openxr_composition_layers/ui.tscn
Labels: enhancement, topic:xr

#1104 Update Android IAP in C# project to Godot 4.3
  mono/android_iap/Android in-app purchases with C#.csproj
  mono/android_iap/GodotGooglePlayBilling/BillingResult.cs
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/GodotGooglePlayBilling/Purchase.cs
  mono/android_iap/GodotGooglePlayBilling/PurchasesResult.cs
  mono/android_iap/GodotGooglePlayBilling/SkuDetails.cs
  mono/android_iap/Main.cs
  mono/android_iap/main.tscn
  mono/android_iap/project.godot
Labels: update, topic:dotnet

#1102 Change semi-truck in Truck Town demo to use 6DOF joint
  3d/truck_town/vehicles/trailer_truck.tscn
Labels: enhancement, topic:physics

#1107 updated meshes to OBJ instead of RES for 3d/navigation
  3d/navigation/level_mesh.res
  3d/navigation/models/level_mesh/level_mesh.mtl
  3d/navigation/models/level_mesh/level_mesh.obj
  3d/navigation/models/level_mesh/level_mesh.obj.import
  3d/navigation/models/robot/robot.mtl
  3d/navigation/models/robot/robot.obj
  3d/navigation/models/robot/robot.obj.import
  3d/navigation/navmesh.tscn
  3d/navigation/project.godot
  3d/navigation/robot.res
Labels: bug, enhancement, topic:navigation

#1036 3D Inverse Kinematics Godot 4 Conversion (Partial)
  3d/ik/addons/sade/ik_fabrik.gd
  3d/ik/addons/sade/ik_look_at.gd
  3d/ik/button_change_scene.gd
  3d/ik/fabrik_ik.tscn
  3d/ik/fps/example_player.gd
  3d/ik/fps/fps_example.tscn
  3d/ik/fps/simple_bullet.gd
  3d/ik/fps/simple_bullet.tscn
  3d/ik/look_at_ik.tscn
  3d/ik/skeleton_ik.tscn
  3d/ik/target_from_mousepos.gd
Labels: update

#1068 Improve Material Testers demo project
  3d/material_testers/material_tester.tscn
  3d/material_testers/models/test_bed/large_material.tres
  3d/material_testers/models/test_bed/small_material.tres
  3d/material_testers/project.godot
  3d/material_testers/test_materials/aluminium_albedo.png.import
  3d/material_testers/test_materials/aluminium_flow.png.import
  3d/material_testers/test_materials/aluminium_normal.png.import
  3d/material_testers/test_materials/ice.tres
  3d/material_testers/test_materials/marble_albedo.png.import
  3d/material_testers/test_materials/rock_albedo.jpg.import
  3d/material_testers/test_materials/rock_ao.jpg.import
  3d/material_testers/test_materials/rock_depth.jpg.import
  3d/material_testers/test_materials/rock_metal.jpg.import
  3d/material_testers/test_materials/rock_rough.jpg.import
  3d/material_testers/test_materials/sand_albedo.jpg.import
  3d/material_testers/test_materials/sand_metal.jpg.import
  3d/material_testers/test_materials/sand_normal.jpg.import
  3d/material_testers/test_materials/sand_rough.jpg.import
  3d/material_testers/test_materials/texture_bricks.jpg.import
  3d/material_testers/test_materials/texture_bricks_ao.jpg.import
  3d/material_testers/test_materials/texture_bricks_depth.jpg.import
  3d/material_testers/test_materials/texture_bricks_metal.jpg.import
  3d/material_testers/test_materials/texture_bricks_normal.jpg.import
  3d/material_testers/test_materials/texture_cheese_albedo.png.import
  3d/material_testers/test_materials/texture_cheese_ao.png.import
  3d/material_testers/test_materials/texture_cheese_depth.png.import
  3d/material_testers/test_materials/texture_cheese_normal.png.import
  3d/material_testers/test_materials/texture_rock_albedo.png.import
  3d/material_testers/test_materials/texture_rock_ao.png.import
  3d/material_testers/test_materials/texture_rock_depth.png.import
  3d/material_testers/test_materials/texture_rock_metal.png.import
  3d/material_testers/test_materials/texture_rock_normal.png.import
  3d/material_testers/test_materials/texture_wood.png.import
  3d/material_testers/test_materials/wool_albedo.png.import
  3d/material_testers/test_materials/wool_depth.png.import
  3d/material_testers/test_materials/wool_normal.png.import
  3d/material_testers/tester.gd
Labels: enhancement

#1105 Fix updated Android IAP project in c#
  mono/android_iap/Android in-app purchases with C#.csproj
  mono/android_iap/Android in-app purchases with C#.sln
  mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
  mono/android_iap/android/.build_version
  mono/android_iap/android/plugins/GodotGooglePlayBilling.1.2.0.release.aar
  mono/android_iap/android/plugins/GodotGooglePlayBilling.gdap
  mono/android_iap/main.tscn
  mono/android_iap/project.godot
Labels: bug

#1008 Add static types in 2D Navigation A Star demo
  2d/navigation_astar/character.gd
  2d/navigation_astar/pathfind_astar.gd
Labels: enhancement
