Repository godotengine/godot-demo-projects, pull requests merged in 2024-03, with the labels that each got.

#1019 Fix squash_the_creeps hitboxes
  3d/squash_the_creeps/Mob.tscn
  3d/squash_the_creeps/Player.gd
  3d/squash_the_creeps/Player.tscn
Labels: bug

#1020 Fix player and mob animations not looping in Squash the Creeps
  3d/squash_the_creeps/Main.tscn
  3d/squash_the_creeps/Mob.tscn
  3d/squash_the_creeps/Player.tscn
Labels: bug, cherrypick:4.2

#966 Update Pong with C# to Godot 4.2.1
  mono/pong/Logic/Ball.cs
  mono/pong/Logic/Paddle.cs
  mono/pong/Pong with C#.csproj
  mono/pong/ball.png.import
  mono/pong/paddle.png.import
  mono/pong/pong.tscn
  mono/pong/project.godot
  mono/pong/separator.png.import
Labels: update, topic:dotnet
