Repository godotengine/godot-demo-projects, pull requests merged in 2024-06, with the labels that each got.

#855 [3.x] Add a 2D polygons and lines demo
  2d/polygons_lines/README.md
  2d/polygons_lines/icon.webp
  2d/polygons_lines/icon.webp.import
  2d/polygons_lines/line_10px.png
  2d/polygons_lines/line_10px.png.import
  2d/polygons_lines/line_30px.png
  2d/polygons_lines/line_30px.png.import
  2d/polygons_lines/polygons_lines.tscn
  2d/polygons_lines/project.godot
  2d/polygons_lines/screenshots/.gdignore
  2d/polygons_lines/screenshots/polygons_lines.webp
Labels: new demo

#1066 Add turbulence example to 3D Particles demo
  3d/particles/test.tscn
Labels: enhancement

#1067 Use higher shadow filtering quality settings in 3D demos
  3d/antialiasing/project.godot
  3d/decals/project.godot
  3d/global_illumination/project.godot
  3d/global_illumination/test.tscn
  3d/kinematic_character/project.godot
  3d/labels_and_texts/project.godot
  3d/material_testers/project.godot
  3d/navigation/project.godot
  3d/occlusion_culling_mesh_lod/project.godot
  3d/particles/project.godot
  3d/physical_light_camera_units/test.tscn
  3d/procedural_materials/project.godot
  3d/rigidbody_character/project.godot
  3d/squash_the_creeps/project.godot
  3d/variable_rate_shading/project.godot
  3d/volumetric_fog/project.godot
  3d/voxel/menu/ingame/pause_menu.tscn
  3d/voxel/project.godot
  3d/voxel/world/world.tscn
  3d/waypoints/main.tscn
  3d/waypoints/project.godot
  misc/large_world_coordinates/project.godot
  misc/large_world_coordinates/test.tscn
  viewport/3d_scaling/project.godot
Labels: enhancement

#1058 Compute demo for compositor effect
  compute/post_shader/README.md
  compute/post_shader/icon.svg
  compute/post_shader/icon.svg.import
  compute/post_shader/main.gd
  compute/post_shader/main.tscn
  compute/post_shader/pattern.png
  compute/post_shader/pattern.png.import
  compute/post_shader/post_process_grayscale.gd
  compute/post_shader/post_process_grayscale.glsl
  compute/post_shader/post_process_grayscale.glsl.import
  compute/post_shader/post_process_shader.gd
  compute/post_shader/project.godot
  compute/post_shader/screenshots/.gdignore
  compute/post_shader/screenshots/post_process_shader.webp
Labels: enhancement, topic:shaders

#1081 Fix incorrect typed Array assignment in XR demo scripts
  xr/openxr_character_centric_movement/start_vr.gd
  xr/openxr_origin_centric_movement/start_vr.gd
Labels: bug, topic:xr
