Repository godotengine/godot-demo-projects, pull requests merged in 2024-04, with the labels that each got.

#1026 Correct font setup in Dodge The Creeps 2D.
  2d/dodge_the_creeps/HUD.tscn
  2d/dodge_the_creeps/fonts/Xolonium-Regular.tres
Labels: bug, needs testing

#1027 Update font code for Godot 4.0
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/debug/StatesStackDiplayer.tscn
  2d/finite_state_machine/fonts/SourceCodePro-Black.ttf
  2d/finite_state_machine/fonts/SourceCodePro-Black.ttf.import
  2d/finite_state_machine/fonts/source_code_pro_explanations.tres
  2d/finite_state_machine/fonts/source_code_pro_explanations_bold.tres
Labels: bug

#1038 Switch to single safe threaded model in TextureRD demo
  compute/texture/project.godot
Labels: bug

#1039 Only print MIDI device list if any are found.
  audio/midi_piano/piano.gd
Labels: enhancement

#1041 Update 2.5D GDScript demo to display the editor plugin in Godot 4.
  misc/2.5d/addons/node25d/main_screen/gizmo_25d.gd
  misc/2.5d/addons/node25d/main_screen/gizmo_25d.tscn
  misc/2.5d/addons/node25d/main_screen/main_screen_25d.tscn
  misc/2.5d/addons/node25d/main_screen/viewport_25d.gd
  misc/2.5d/addons/node25d/node25d_plugin.gd
  misc/2.5d/addons/node25d/node_25d.gd
  misc/2.5d/addons/node25d/shadow_math_25d.gd
  misc/2.5d/assets/cube/cube_math.gd
  misc/2.5d/assets/demo_scene.tscn
  misc/2.5d/assets/player/player_25d.tscn
  misc/2.5d/assets/player/player_math_25d.gd
  misc/2.5d/assets/player/player_sprite.gd
  misc/2.5d/assets/shadow/shadow_25d.tscn
  misc/2.5d/assets/ui/overlay.tscn
  misc/2.5d/project.godot
Labels: bug

#807 Add doors as an example of dynamic occluders in the Occlusion culling demo
  3d/occlusion_culling_mesh_lod/door.gd
  3d/occlusion_culling_mesh_lod/door.tscn
  3d/occlusion_culling_mesh_lod/node_3d.gd
  3d/occlusion_culling_mesh_lod/node_3d.tscn
  3d/occlusion_culling_mesh_lod/project.godot
Labels: enhancement

#1000 Updated Dodge the Creeps C# to Godot mono 4.2
  2d/dodge_the_creeps/Player.gd
  2d/dodge_the_creeps/Player.tscn
  mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
  mono/dodge_the_creeps/HUD.cs
  mono/dodge_the_creeps/HUD.tscn
  mono/dodge_the_creeps/Main.cs
  mono/dodge_the_creeps/Main.tscn
  mono/dodge_the_creeps/Mob.cs
  mono/dodge_the_creeps/Mob.tscn
  mono/dodge_the_creeps/Player.cs
  mono/dodge_the_creeps/Player.tscn
  mono/dodge_the_creeps/art/House In a Forest Loop.ogg.import
  mono/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
  mono/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
  mono/dodge_the_creeps/art/enemySwimming_1.png.import
  mono/dodge_the_creeps/art/enemySwimming_2.png.import
  mono/dodge_the_creeps/art/enemyWalking_1.png.import
  mono/dodge_the_creeps/art/enemyWalking_2.png.import
  mono/dodge_the_creeps/art/gameover.wav.import
  mono/dodge_the_creeps/art/playerGrey_up1.png.import
  mono/dodge_the_creeps/art/playerGrey_up2.png.import
  mono/dodge_the_creeps/art/playerGrey_walk1.png.import
  mono/dodge_the_creeps/art/playerGrey_walk2.png.import
  mono/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
  mono/dodge_the_creeps/project.godot
Labels: update, topic:dotnet

#1035 Remove tiles outside of texture to elliminate these errors on loading:
  2d/dynamic_tilemap_layers/world.tscn
Labels: bug

#1022 XR demos: Add check for VRS/foveation in start vr script
  xr/openxr_character_centric_movement/.gitattributes
  xr/openxr_character_centric_movement/.gitignore
  xr/openxr_character_centric_movement/README.md
  xr/openxr_character_centric_movement/project.godot
  xr/openxr_character_centric_movement/start_vr.gd
  xr/openxr_origin_centric_movement/.gitattributes
  xr/openxr_origin_centric_movement/.gitignore
  xr/openxr_origin_centric_movement/README.md
  xr/openxr_origin_centric_movement/project.godot
  xr/openxr_origin_centric_movement/start_vr.gd
Labels: enhancement, topic:xr

#943 Fix joypad demo for Godot 4.x
  misc/joypads/joypads.tscn
  misc/joypads/remap/remap_wizard.gd
  misc/joypads/remap/remap_wizard.tscn
Labels: bug

#1049 change upward movement key to W instead of Z
  networking/multiplayer_bomber/project.godot
Labels: bug

#1048 Add missing tags
  2d/dynamic_tilemap_layers/project.godot
  3d/physical_light_camera_units/project.godot
  3d/procedural_materials/project.godot
  3d/squash_the_creeps/project.godot
  compute/texture/project.godot
  xr/openxr_character_centric_movement/project.godot
  xr/openxr_origin_centric_movement/project.godot
Labels: bug
