Repository godotengine/godot-demo-projects, pull requests merged in 2024-01, with the labels that each got.

#1010 Fixed typo in start vr script for selecting refresh rate
  xr/openxr_character_centric_movement/start_vr.gd
  xr/openxr_origin_centric_movement/start_vr.gd
Labels: bug, topic:xr

#998 Add mobile controls and optimized settings to Truck Town
  3d/truck_town/README.md
  3d/truck_town/car_select/car_select.tscn
  3d/truck_town/car_select/choose_tow.png.import
  3d/truck_town/car_select/choose_trailer.png.import
  3d/truck_town/car_select/choose_van.png.import
  3d/truck_town/project.godot
  3d/truck_town/town/materials/cement.webp.import
  3d/truck_town/town/materials/grass.webp.import
  3d/truck_town/town/town_scene.tscn
  3d/truck_town/town/truck_town.glb.import
  3d/truck_town/vehicles/blob_shadow.png.import
  3d/truck_town/vehicles/car_base.tscn
  3d/truck_town/vehicles/meshes/meshes.glb.import
  3d/truck_town/vehicles/meshes/minivan.res
  3d/truck_town/vehicles/meshes/tow_truck.res
  3d/truck_town/vehicles/meshes/truck_cab.res
  3d/truck_town/vehicles/meshes/truck_trailer.res
  3d/truck_town/vehicles/meshes/wheel.res
  3d/truck_town/vehicles/particle_smoke.png.import
  3d/truck_town/vehicles/tow_truck.tscn
  3d/truck_town/vehicles/trailer_truck.tscn
  3d/truck_town/vehicles/truck_trailer.png.import
  3d/truck_town/vehicles/vehicle.gd
Labels: bug, enhancement, topic:mobile

#994 Add alpha antialiasing example to 3D Antialiasing demo
  3d/antialiasing/README.md
  3d/antialiasing/anti_aliasing.tscn
  3d/antialiasing/project.godot
Labels: enhancement

#993 Add a run-time saving/loading demo project
  loading/runtime_save_load/README.md
  loading/runtime_save_load/examples/.gdignore
  loading/runtime_save_load/examples/3d_scenes/plastic_monobloc_chair_01_1k/plastic_monobloc_chair_01.bin
  loading/runtime_save_load/examples/3d_scenes/plastic_monobloc_chair_01_1k/plastic_monobloc_chair_01_1k.gltf
  loading/runtime_save_load/examples/3d_scenes/plastic_monobloc_chair_01_1k/textures/plastic_monobloc_chair_01_arm_1k.jpg
  loading/runtime_save_load/examples/3d_scenes/plastic_monobloc_chair_01_1k/textures/plastic_monobloc_chair_01_diff_1k.jpg
  loading/runtime_save_load/examples/3d_scenes/plastic_monobloc_chair_01_1k/textures/plastic_monobloc_chair_01_nor_gl_1k.jpg
  loading/runtime_save_load/examples/audio/item_spawn.ogg
  loading/runtime_save_load/examples/fonts/LICENSE.txt
  loading/runtime_save_load/examples/fonts/hack_regular.woff2
  loading/runtime_save_load/examples/fonts/inter_black.otf
  loading/runtime_save_load/examples/fonts/newsreader_9pt_regular.ttf
  loading/runtime_save_load/examples/images/godot_icon.bmp
  loading/runtime_save_load/examples/images/godot_icon.jpg
  loading/runtime_save_load/examples/images/godot_icon.png
  loading/runtime_save_load/examples/images/godot_icon.svg
  loading/runtime_save_load/examples/images/godot_icon.tga
  loading/runtime_save_load/examples/images/godot_icon.webp
  loading/runtime_save_load/examples/misc/example.zip
  loading/runtime_save_load/examples/misc/file.txt
  loading/runtime_save_load/icon.svg
  loading/runtime_save_load/icon.svg.import
  loading/runtime_save_load/project.godot
  loading/runtime_save_load/runtime_save_load.gd
  loading/runtime_save_load/runtime_save_load.tscn
  loading/runtime_save_load/screenshots/.gdignore
  loading/runtime_save_load/screenshots/runtime_save_load.webp
  loading/serialization/README.md
Labels: new demo
