Repository godotengine/godot-demo-projects, pull requests merged in 2025-07, with the labels that each got.

#1229 Add FoldableContainer to the Control Gallery demo
  gui/control_gallery/control_gallery.tscn
  gui/control_gallery/project.godot
  gui/control_gallery/screenshots/control_gallery.webp
Labels: enhancement

#1218 Added an OpenXR render models demo
  xr/openxr_render_models/.gitattributes
  xr/openxr_render_models/.gitignore
  xr/openxr_render_models/README.md
  xr/openxr_render_models/assets/pattern.png
  xr/openxr_render_models/assets/pattern.png.import
  xr/openxr_render_models/box.tscn
  xr/openxr_render_models/collision_hands.gd
  xr/openxr_render_models/collision_hands.gd.uid
  xr/openxr_render_models/icon.svg
  xr/openxr_render_models/icon.svg.import
  xr/openxr_render_models/main.tscn
  xr/openxr_render_models/openxr_action_map.tres
  xr/openxr_render_models/project.godot
  xr/openxr_render_models/screenshots/render_model_demo.png
  xr/openxr_render_models/screenshots/render_model_demo.png.import
  xr/openxr_render_models/start_vr.gd
  xr/openxr_render_models/start_vr.gd.uid
  xr/openxr_render_models/wall.tscn
Labels: enhancement, topic:xr

#1209 Fix "Parse message failed" error in WebRTC Signaling Demo Project
  networking/webrtc_signaling/server/ws_webrtc_server.gd
Labels: bug

#1231 Simplify mesh custom drawing demo
  2d/custom_drawing/meshes.gd
Labels: enhancement
