Repository godotengine/godot-demo-projects, pull requests merged in 2025-09, with the labels that each got.

#1247 Fix uniform sets in "Compute Texture"
  compute/texture/water_plane/water_plane.gd
Labels: bug

#1248 Get role_playing_game working again: Gamepad, TileMapLayer, fix bugs
  2d/role_playing_game/combat/combat.gd
  2d/role_playing_game/combat/combat.tscn
  2d/role_playing_game/combat/combatants/combatant.gd
  2d/role_playing_game/combat/combatants/sprites/sprite.tscn
  2d/role_playing_game/combat/interface/ui.gd
  2d/role_playing_game/decoration/wind_sway.tres
  2d/role_playing_game/game.gd
  2d/role_playing_game/game.tscn
  2d/role_playing_game/grid_movement/exploration.tscn
  2d/role_playing_game/grid_movement/grid/grid.gd
  2d/role_playing_game/grid_movement/pawns/actor.gd
  2d/role_playing_game/grid_movement/pawns/actor.gd.uid
  2d/role_playing_game/grid_movement/pawns/anim_opponent.tres
  2d/role_playing_game/grid_movement/pawns/anim_player.tres
  2d/role_playing_game/grid_movement/pawns/character.tscn
  2d/role_playing_game/grid_movement/pawns/opponent.gd
  2d/role_playing_game/grid_movement/pawns/player.gd
  2d/role_playing_game/grid_movement/pawns/player.gd.uid
  2d/role_playing_game/grid_movement/pawns/walker.gd
  2d/role_playing_game/project.godot
Labels: bug, enhancement

#1242 Add a custom logging demo
  misc/custom_logging/README.md
  misc/custom_logging/custom_logger_ui.gd
  misc/custom_logging/custom_logger_ui.gd.uid
  misc/custom_logging/custom_logger_ui.tscn
  misc/custom_logging/jetbrains_mono_bold.woff2
  misc/custom_logging/jetbrains_mono_bold.woff2.import
  misc/custom_logging/jetbrains_mono_regular.woff2
  misc/custom_logging/jetbrains_mono_regular.woff2.import
  misc/custom_logging/main.gd
  misc/custom_logging/main.gd.uid
  misc/custom_logging/main.tscn
  misc/custom_logging/project.godot
  misc/custom_logging/screenshots/.gdignore
  misc/custom_logging/screenshots/custom_logging.webp
Labels: new demo

#1223 Add 3D physics interpolation demo
  3d/physics_interpolation/.editorconfig
  3d/physics_interpolation/README.md
  3d/physics_interpolation/box.tscn
  3d/physics_interpolation/bullet.gd
  3d/physics_interpolation/bullet.gd.uid
  3d/physics_interpolation/bullet.tscn
  3d/physics_interpolation/icon.png.import
  3d/physics_interpolation/icon.svg
  3d/physics_interpolation/icon.svg.import
  3d/physics_interpolation/player.gd
  3d/physics_interpolation/player.gd.uid
  3d/physics_interpolation/project.godot
  3d/physics_interpolation/root.tscn
  3d/physics_interpolation/screenshots/.gdignore
  3d/physics_interpolation/screenshots/physics_interpolation.webp
  3d/physics_interpolation/spark_particle.png
  3d/physics_interpolation/spark_particle.png.import
  3d/physics_interpolation/wall.tscn
Labels: new demo

#1234 Add a 3D ragdoll physics demo
  3d/ragdoll_physics/README.md
  3d/ragdoll_physics/characters/mannequiny.LICENSE.md
  3d/ragdoll_physics/characters/mannequiny.glb
  3d/ragdoll_physics/characters/mannequiny.glb.import
  3d/ragdoll_physics/characters/mannequiny_ragdoll.gd
  3d/ragdoll_physics/characters/mannequiny_ragdoll.gd.uid
  3d/ragdoll_physics/characters/mannequiny_ragdoll.tscn
  3d/ragdoll_physics/materials/black.tres
  3d/ragdoll_physics/materials/blue.tres
  3d/ragdoll_physics/materials/white.tres
  3d/ragdoll_physics/project.godot
  3d/ragdoll_physics/ragdoll_physics.exr
  3d/ragdoll_physics/ragdoll_physics.exr.import
  3d/ragdoll_physics/ragdoll_physics.gd
  3d/ragdoll_physics/ragdoll_physics.gd.uid
  3d/ragdoll_physics/ragdoll_physics.lmbake
  3d/ragdoll_physics/ragdoll_physics.tscn
  3d/ragdoll_physics/screenshots/.gdignore
  3d/ragdoll_physics/screenshots/ragdoll_physics.webp
  3d/ragdoll_physics/sounds/impact_big.LICENSE.md
  3d/ragdoll_physics/sounds/impact_big.wav
  3d/ragdoll_physics/sounds/impact_big.wav.import
  3d/ragdoll_physics/sounds/impact_small.LICENSE.md
  3d/ragdoll_physics/sounds/impact_small.wav
  3d/ragdoll_physics/sounds/impact_small.wav.import
  3d/ragdoll_physics/textures/checker.LICENSE.md
  3d/ragdoll_physics/textures/checker.png
  3d/ragdoll_physics/textures/checker.png.import
Labels: new demo
