Repository godotengine/godot-demo-projects, pull requests merged in 2025-04, with the labels that each got.

#1182 Fix block face checks and explicitly define normals in voxel demo
  3d/voxel/menu/debug.gd
  3d/voxel/menu/options/option_buttons.gd
  3d/voxel/player/player.tscn
  3d/voxel/project.godot
  3d/voxel/settings.gd
  3d/voxel/world/chunk.gd
  3d/voxel/world/voxel_world.gd
Labels: bug

#1186 remove broken int type check in webrtc
  networking/webrtc_signaling/client/ws_webrtc_client.gd
Labels: bug

#1187 Fix camera colliding with the player in 3D platformer demo
  3d/kinematic_character/cubelib.tres
  3d/kinematic_character/level.tscn
  3d/kinematic_character/player/cubio.gd
  3d/kinematic_character/player/cubio.tscn
  3d/platformer/player/follow_camera.gd
  3d/rigidbody_character/cubelib.tres
  3d/rigidbody_character/level.tscn
  3d/rigidbody_character/player/cubio.gd
  3d/rigidbody_character/player/cubio.tscn
Labels: bug

#1070 Enable physics interpolation in all 2D demos
  2d/dynamic_tilemap_layers/project.godot
  2d/dynamic_tilemap_layers/world.tscn
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/player/bullet/bullet_spawner.gd
  2d/finite_state_machine/project.godot
  2d/hexagonal_map/project.godot
  2d/hexagonal_map/troll.tscn
  2d/instancing/project.godot
  2d/instancing/scene_instancing.tscn
  2d/isometric/player/goblin.tscn
  2d/isometric/project.godot
  2d/isometric/tileset/tileset.tres
  2d/kinematic_character/project.godot
  2d/kinematic_character/world.tscn
  2d/navigation/navigation.tscn
  2d/navigation/project.godot
  2d/physics_platformer/player/player.tscn
  2d/physics_platformer/project.godot
  2d/physics_platformer/tileset.tres
  2d/physics_tests/project.godot
  2d/platformer/game_singleplayer.tscn
  2d/platformer/game_splitscreen.tscn
  2d/platformer/player/player.gd
  2d/platformer/player/player.tscn
  2d/platformer/project.godot
  2d/skeleton/level/tileset/tileset.tres
  2d/skeleton/player/player.tscn
  2d/skeleton/project.godot
  networking/multiplayer_bomber/project.godot
  networking/multiplayer_bomber/world.tscn
Labels: enhancement

#1177 Change physics joint tests to freeze bodies as kinematic
  2d/physics_tests/tests/functional/test_joints.gd
  3d/physics_tests/tests/functional/test_joints.gd
Labels: bug, topic:physics

#1188 Fix incorrect `class_name` declaration in 2D physics tests demo
  2d/physics_tests/tests/functional/test_character.gd
  compute/post_shader/post_process_grayscale.gd
  compute/post_shader/post_process_shader.gd
  xr/openxr_hand_tracking_demo/pickup/pickup_able_body.gd
  xr/openxr_hand_tracking_demo/pickup/pickup_handler.gd
Labels: bug

#1189 Improve flat terrain generation in the Voxel demo
  3d/voxel/world/terrain_generator.gd
Labels: enhancement

#1190 Add block placement preview to Voxel demo, improve debug display
  3d/voxel/menu/debug.gd
  3d/voxel/player/player.gd
  3d/voxel/player/player.tscn
  3d/voxel/world/world.tscn
Labels: enhancement

#1074 Enable physics interpolation in all 3D demos
  3d/graphics_settings/3d_scene.tscn
  3d/graphics_settings/control.tscn
  3d/ik/fabrik_ik.tscn
  3d/ik/fps/fps_example.tscn
  3d/ik/fps/simple_bullet.tscn
  3d/ik/look_at_ik.tscn
  3d/ik/skeleton_ik.tscn
  3d/kinematic_character/player/cubio.gd
  3d/kinematic_character/project.godot
  3d/navigation/project.godot
  3d/physics_tests/project.godot
  3d/platformer/coin/coin.tscn
  3d/platformer/player/bullet/bullet.tscn
  3d/platformer/player/player.gd
  3d/platformer/player/player.tscn
  3d/platformer/project.godot
  3d/rigidbody_character/player/cubio.gd
  3d/rigidbody_character/project.godot
  3d/squash_the_creeps/Mob.tscn
  3d/squash_the_creeps/Player.tscn
  3d/squash_the_creeps/project.godot
  3d/truck_town/project.godot
  3d/truck_town/vehicles/follow_camera.gd
  3d/truck_town/vehicles/meshes/meshes.glb.import
  3d/voxel/project.godot
Labels: enhancement

#1198 Fix Sprite3D shader effect bug
  3d/sprites/shaders/paper_emission.gdshader
  3d/sprites/shaders/paper_material.gdshader
  3d/sprites/shaders/paper_rainbow.gdshader
Labels: bug
