Repository godotengine/godot-demo-projects, pull requests merged in 2025-10, with the labels that each got.

#1252 Use GodotPhysics3D in Voxel demo to work around performance issue
  3d/voxel/project.godot
Labels: enhancement, topic:physics

#1238 Add basic accessibility features demo.
  gui/accessibility/README.md
  gui/accessibility/clear.svg
  gui/accessibility/clear.svg.import
  gui/accessibility/controls.gd
  gui/accessibility/controls.gd.uid
  gui/accessibility/controls.tscn
  gui/accessibility/controls.uid
  gui/accessibility/custom_control.gd
  gui/accessibility/custom_control.gd.uid
  gui/accessibility/icon.svg
  gui/accessibility/icon.svg.import
  gui/accessibility/project.godot
  gui/accessibility/screenshots/.gdignore
  gui/accessibility/screenshots/ui_access.webp
Labels: enhancement, new demo

#1227 Fix FPS-dependent movement in Navigation AStar demo
  2d/navigation_astar/character.gd
  2d/navigation_astar/game.tscn
  2d/navigation_astar/project.godot
Labels: bug

#1184 Fix `content_scale_*` updates: properties are in `Window` not `(Sub-)Viewport`
  gui/multiple_resolutions/main.gd
Labels: bug

#1143 Add player_state dictionary to manage player state names for FSM demo
  2d/finite_state_machine/Demo.tscn
  2d/finite_state_machine/debug/states_stack_displayer.gd.uid
  2d/finite_state_machine/fonts/SourceCodePro-Bold.ttf.import
  2d/finite_state_machine/icon.webp.import
  2d/finite_state_machine/player/body.png.import
  2d/finite_state_machine/player/bullet/bullet.gd.uid
  2d/finite_state_machine/player/bullet/bullet_spawner.gd
  2d/finite_state_machine/player/bullet/bullet_spawner.gd.uid
  2d/finite_state_machine/player/player_controller.gd.uid
  2d/finite_state_machine/player/player_state.gd
  2d/finite_state_machine/player/player_state.gd.uid
  2d/finite_state_machine/player/player_state_machine.gd
  2d/finite_state_machine/player/player_state_machine.gd.uid
  2d/finite_state_machine/player/shadow.png.import
  2d/finite_state_machine/player/states/combat/attack.gd
  2d/finite_state_machine/player/states/combat/attack.gd.uid
  2d/finite_state_machine/player/states/combat/stagger.gd
  2d/finite_state_machine/player/states/combat/stagger.gd.uid
  2d/finite_state_machine/player/states/debug/state_name_displayer.gd.uid
  2d/finite_state_machine/player/states/die.gd
  2d/finite_state_machine/player/states/die.gd.uid
  2d/finite_state_machine/player/states/motion/in_air/jump.gd
  2d/finite_state_machine/player/states/motion/in_air/jump.gd.uid
  2d/finite_state_machine/player/states/motion/motion.gd
  2d/finite_state_machine/player/states/motion/motion.gd.uid
  2d/finite_state_machine/player/states/motion/on_ground/idle.gd
  2d/finite_state_machine/player/states/motion/on_ground/idle.gd.uid
  2d/finite_state_machine/player/states/motion/on_ground/move.gd
  2d/finite_state_machine/player/states/motion/on_ground/move.gd.uid
  2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd
  2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd.uid
  2d/finite_state_machine/player/weapon/sword.gd
  2d/finite_state_machine/player/weapon/sword.gd.uid
  2d/finite_state_machine/player/weapon/sword.png.import
  2d/finite_state_machine/player/weapon/weapon_pivot.gd.uid
  2d/finite_state_machine/project.godot
  2d/finite_state_machine/state_machine/state.gd
  2d/finite_state_machine/state_machine/state.gd.uid
  2d/finite_state_machine/state_machine/state_machine.gd
  2d/finite_state_machine/state_machine/state_machine.gd.uid
Labels: enhancement

#860 Add a 3D visibility ranges (HLOD) demo
  3d/visibility_ranges/README.md
  3d/visibility_ranges/camera.gd
  3d/visibility_ranges/camera.gd.uid
  3d/visibility_ranges/fps_label.gd
  3d/visibility_ranges/fps_label.gd.uid
  3d/visibility_ranges/project.godot
  3d/visibility_ranges/screenshots/.gdignore
  3d/visibility_ranges/screenshots/visibility_ranges.webp
  3d/visibility_ranges/test.tscn
  3d/visibility_ranges/tree.tscn
  3d/visibility_ranges/tree_cluster.tscn
  3d/visibility_ranges/tree_clusters.gd
  3d/visibility_ranges/tree_clusters.gd.uid
  3d/visibility_ranges/tree_material.tres
  3d/visibility_ranges/trunk_material.tres
Labels: new demo

#1045 Updated Multiplayer Pong C# to Godot 4.2
  mono/multiplayer_pong/Pong Multiplayer with C#.csproj
  mono/multiplayer_pong/Pong Multiplayer with C#.sln
  mono/multiplayer_pong/lobby.tscn
  mono/multiplayer_pong/logic/Ball.cs
  mono/multiplayer_pong/logic/Lobby.cs
  mono/multiplayer_pong/logic/Paddle.cs
  mono/multiplayer_pong/logic/Pong.cs
  mono/multiplayer_pong/project.godot
Labels: update

#1023 Add Split Screen Demo showing input handling
  viewport/split_screen_input/README.md
  viewport/split_screen_input/icon.svg
  viewport/split_screen_input/icon.svg.import
  viewport/split_screen_input/player.gd
  viewport/split_screen_input/player.gd.uid
  viewport/split_screen_input/project.godot
  viewport/split_screen_input/root.gd
  viewport/split_screen_input/root.gd.uid
  viewport/split_screen_input/screenshots/.gdignore
  viewport/split_screen_input/screenshots/split_screen_input.webp
  viewport/split_screen_input/split_screen.gd
  viewport/split_screen_input/split_screen.gd.uid
  viewport/split_screen_input/split_screen.tscn
  viewport/split_screen_input/split_screen_demo.tscn
  viewport/split_screen_input/sub_viewport_container.gd
  viewport/split_screen_input/sub_viewport_container.gd.uid
Labels: new demo

#1253 Make Voxel demo player responsive without using unrealistic global gravity
  3d/voxel/icon.webp.import
  3d/voxel/menu/button.png.import
  3d/voxel/menu/button_focus.png.import
  3d/voxel/menu/button_hover.png.import
  3d/voxel/menu/button_pressed.png.import
  3d/voxel/menu/main/dark_dirt.png.import
  3d/voxel/menu/main/title.png.import
  3d/voxel/menu/theme/TinyUnicode.ttf.import
  3d/voxel/player/crosshair.svg.import
  3d/voxel/player/player.gd
  3d/voxel/player/player.tscn
  3d/voxel/project.godot
  3d/voxel/world/textures/texture_sheet.png.import
Labels: enhancement

#1257 Switch back to Jolt Physics in Voxel demo
  3d/voxel/player/player.gd
  3d/voxel/project.godot
  3d/voxel/world/chunk.gd
  3d/voxel/world/terrain_generator.gd
  3d/voxel/world/voxel_world.gd
Labels: enhancement, topic:physics

#1255 Simplify list of branches in the README
  README.md
Labels: enhancement

#762 [3.x] Add a 2D version of the dynamic split screen demo
  viewport/dynamic_split_screen/.gitignore
  viewport/dynamic_split_screen/2d/level.tscn
  viewport/dynamic_split_screen/2d/player.gd
  viewport/dynamic_split_screen/2d/player.png
  viewport/dynamic_split_screen/2d/player.png.import
  viewport/dynamic_split_screen/2d/split_screen.tscn
  viewport/dynamic_split_screen/2d/square.png
  viewport/dynamic_split_screen/2d/square.png.import
  viewport/dynamic_split_screen/2d/wall_coloring.gd
  viewport/dynamic_split_screen/3d/level.tscn
  viewport/dynamic_split_screen/3d/player.gd
  viewport/dynamic_split_screen/3d/split_screen.tscn
  viewport/dynamic_split_screen/3d/wall_coloring.gd
  viewport/dynamic_split_screen/README.md
  viewport/dynamic_split_screen/camera_controller.gd
  viewport/dynamic_split_screen/exit_to_menu.gd
  viewport/dynamic_split_screen/menu.gd
  viewport/dynamic_split_screen/menu.tscn
  viewport/dynamic_split_screen/noto_sans_ui_regular.ttf
  viewport/dynamic_split_screen/project.godot
  viewport/dynamic_split_screen/screenshots/splitscreen_2d.png
  viewport/dynamic_split_screen/screenshots/splitscreen_3d.png
Labels: new demo

#1137 Add XR demo for binding modifier logic
  xr/openxr_binding_modifier_demo/README.md
  xr/openxr_binding_modifier_demo/assets/pattern.png
  xr/openxr_binding_modifier_demo/assets/pattern.png.import
  xr/openxr_binding_modifier_demo/controller_state.gd
  xr/openxr_binding_modifier_demo/controller_state.gd.uid
  xr/openxr_binding_modifier_demo/controller_state.tscn
  xr/openxr_binding_modifier_demo/icon.svg
  xr/openxr_binding_modifier_demo/icon.svg.import
  xr/openxr_binding_modifier_demo/main.tscn
  xr/openxr_binding_modifier_demo/openxr_action_map.tres
  xr/openxr_binding_modifier_demo/project.godot
  xr/openxr_binding_modifier_demo/screenshots/analog_binding_modifier.png
  xr/openxr_binding_modifier_demo/screenshots/analog_binding_modifier.png.import
  xr/openxr_binding_modifier_demo/screenshots/binding_modifier_demo.png
  xr/openxr_binding_modifier_demo/screenshots/binding_modifier_demo.png.import
  xr/openxr_binding_modifier_demo/screenshots/dpad_modifier.png
  xr/openxr_binding_modifier_demo/screenshots/dpad_modifier.png.import
  xr/openxr_binding_modifier_demo/start_vr.gd
  xr/openxr_binding_modifier_demo/start_vr.gd.uid
Labels: enhancement, topic:xr

#1001 Add Squash the Creeps 3D C# demo for Godot mono 4.2
  mono/squash_the_creeps/Main.cs
  mono/squash_the_creeps/Main.cs.uid
  mono/squash_the_creeps/Main.tscn
  mono/squash_the_creeps/Mob.cs
  mono/squash_the_creeps/Mob.cs.uid
  mono/squash_the_creeps/Mob.tscn
  mono/squash_the_creeps/MusicPlayer.tscn
  mono/squash_the_creeps/Player.cs
  mono/squash_the_creeps/Player.cs.uid
  mono/squash_the_creeps/Player.tscn
  mono/squash_the_creeps/README.md
  mono/squash_the_creeps/ScoreLabel.cs
  mono/squash_the_creeps/ScoreLabel.cs.uid
  mono/squash_the_creeps/Squash the Creeps (3D).csproj
  mono/squash_the_creeps/Squash the Creeps (3D).sln
  mono/squash_the_creeps/art/House In a Forest Loop.ogg
  mono/squash_the_creeps/art/House In a Forest Loop.ogg.import
  mono/squash_the_creeps/art/body.material
  mono/squash_the_creeps/art/eye.material
  mono/squash_the_creeps/art/mob.glb
  mono/squash_the_creeps/art/mob.glb.import
  mono/squash_the_creeps/art/mob_body.material
  mono/squash_the_creeps/art/mob_eye.material
  mono/squash_the_creeps/art/player.glb
  mono/squash_the_creeps/art/player.glb.import
  mono/squash_the_creeps/art/pupil.material
  mono/squash_the_creeps/fonts/LICENSE.txt
  mono/squash_the_creeps/fonts/Montserrat-Medium.ttf
  mono/squash_the_creeps/fonts/Montserrat-Medium.ttf.import
  mono/squash_the_creeps/icon.png
  mono/squash_the_creeps/icon.png.import
  mono/squash_the_creeps/icon.svg
  mono/squash_the_creeps/icon.svg.import
  mono/squash_the_creeps/project.godot
  mono/squash_the_creeps/screenshots/.gdignore
  mono/squash_the_creeps/screenshots/squash_the_creeps.webp
Labels: new demo, topic:dotnet

#1204 Update README.md - Indicate demo obsolete for godot 4.3+
  2d/dynamic_tilemap_layers/README.md
Labels: enhancement

#1219 Refactor Material Creator Plugin Demo to use custom resource-based data
  plugins/addons/material_creator/README.md
  plugins/addons/material_creator/material_creator.gd
  plugins/addons/material_creator/material_format_loader.gd
  plugins/addons/material_creator/material_format_saver.gd
  plugins/addons/material_creator/material_plugin.gd
  plugins/addons/material_creator/material_resource.gd
Labels: enhancement
