Repository godotengine/godot-demo-projects, pull requests merged in 2025-01, with the labels that each got.

#1154 Fix typo in WebSocketServer class name
  networking/websocket_chat/websocket/WebSocketServer.gd
Labels: bug, regression, topic:network

#1151 Update main.gd
  2d/dodge_the_creeps/main.gd
Labels: enhancement

#1155 Update to TileMapLayer on multiplayer bomber.
  networking/multiplayer_bomber/tileset.tres
  networking/multiplayer_bomber/world.tscn
Labels: enhancement

#1159 Fix invalid icon reference in C# Android IAP demo
  mono/android_iap/project.godot
Labels: bug
