Repository godotengine/godot-demo-projects, pull requests merged in 2025-05, with the labels that each got.

#1202 Fix nonexistent function error in multiplayer bomber
  networking/multiplayer_bomber/gamestate.gd
Labels: bug

#1205 Disable GH `export_web` workflow in forks
  .github/workflows/export_web.yml
Labels: enhancement

#1197 Add a simple rhythm game demo
  audio/rhythm_game/README.md
  audio/rhythm_game/game_state/conductor.gd
  audio/rhythm_game/game_state/conductor.gd.uid
  audio/rhythm_game/game_state/metronome.gd
  audio/rhythm_game/game_state/metronome.gd.uid
  audio/rhythm_game/game_state/note_manager.gd
  audio/rhythm_game/game_state/note_manager.gd.uid
  audio/rhythm_game/game_state/play_stats.gd
  audio/rhythm_game/game_state/play_stats.gd.uid
  audio/rhythm_game/globals/chart_data.gd
  audio/rhythm_game/globals/chart_data.gd.uid
  audio/rhythm_game/globals/enums.gd
  audio/rhythm_game/globals/enums.gd.uid
  audio/rhythm_game/globals/global_settings.gd
  audio/rhythm_game/globals/global_settings.gd.uid
  audio/rhythm_game/globals/one_euro_filter.gd
  audio/rhythm_game/globals/one_euro_filter.gd.uid
  audio/rhythm_game/icon.webp
  audio/rhythm_game/icon.webp.import
  audio/rhythm_game/music/Perc_MetronomeQuartz_hi.wav
  audio/rhythm_game/music/Perc_MetronomeQuartz_hi.wav.import
  audio/rhythm_game/music/the_comeback2.ogg
  audio/rhythm_game/music/the_comeback2.ogg.import
  audio/rhythm_game/objects/guide/guide.gd
  audio/rhythm_game/objects/guide/guide.gd.uid
  audio/rhythm_game/objects/guide/guide.png
  audio/rhythm_game/objects/guide/guide.png.import
  audio/rhythm_game/objects/guide/guide.tscn
  audio/rhythm_game/objects/note/note.gd
  audio/rhythm_game/objects/note/note.gd.uid
  audio/rhythm_game/objects/note/note.png
  audio/rhythm_game/objects/note/note.png.import
  audio/rhythm_game/objects/note/note.tscn
  audio/rhythm_game/project.godot
  audio/rhythm_game/scenes/main/main.gd
  audio/rhythm_game/scenes/main/main.gd.uid
  audio/rhythm_game/scenes/main/main.tscn
  audio/rhythm_game/scenes/main/pause_handler.gd
  audio/rhythm_game/scenes/main/pause_handler.gd.uid
  audio/rhythm_game/screenshots/.gdignore
  audio/rhythm_game/screenshots/rhythm_game.webp
Labels: new demo, topic:audio

#1201 Add an audio effects demo
  audio/audio_effects/README.md
  audio/audio_effects/audio_effects.gd
  audio/audio_effects/audio_effects.gd.uid
  audio/audio_effects/audio_effects.tscn
  audio/audio_effects/default_bus_layout.tres
  audio/audio_effects/icon.webp
  audio/audio_effects/icon.webp.import
  audio/audio_effects/project.godot
  audio/audio_effects/screenshots/.gdignore
  audio/audio_effects/screenshots/audio_effects.webp
  audio/audio_effects/sfx/Ding.wav
  audio/audio_effects/sfx/Ding.wav.import
  audio/audio_effects/sfx/Meow.wav
  audio/audio_effects/sfx/Meow.wav.import
  audio/audio_effects/sfx/Static.wav
  audio/audio_effects/sfx/Static.wav.import
  audio/audio_effects/sfx/Whistle.wav
  audio/audio_effects/sfx/Whistle.wav.import
  audio/audio_effects/sfx/glass_breaking.wav
  audio/audio_effects/sfx/glass_breaking.wav.import
  audio/audio_effects/sfx/music_monkeys_spinning_monkeys.ogg
  audio/audio_effects/sfx/music_monkeys_spinning_monkeys.ogg.import
  audio/audio_effects/sfx/negative_beeps.wav
  audio/audio_effects/sfx/negative_beeps.wav.import
  audio/audio_effects/sfx/sad_trombone.wav
  audio/audio_effects/sfx/sad_trombone.wav.import
Labels: new demo
